/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneltpu;

import Paneles.*;
import DAO.daoAgentes;
import DAO.daoClientes;
import DAO.daocfdi;
import DAO.daoempresa;
import DAO.daofactura;
import DAO.daokardexrcpt;
import DAO.daopedimentos;
import DAO.daoxmlE;
import Modelo.Agentes;
import Modelo.Cliente;
import Modelo.Dfactura;
import Modelo.Empresas;
import Modelo.Formadepago;
import Modelo.Formateo_Nempresas;
import Modelo.Formateodedatos;
import Modelo.Nocolision;
import Modelo.Poliza;
import Modelo.Sellofiscal;
import Modelo.Usuarios;
import Modelo.cargo;
import Modelo.convertirNumeros;
import Modelo.convertnum;
import Modelo.factura;
import Modelo.metodopago;
import Modelo.pedimento;
import Modelo.usocfdi;
import Server.Serverprod;
import Server.Serverylite;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import mx.sat.cfd40.timbrarXML;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author GATEWAY1-
 */
public class fac3tpu extends javax.swing.JPanel {

    public String nombre, empresa, empresarcpt, empresacob;
    public Connection sqlcfdi, sqlempresa;
    public Connection ACobranza, rcpt, cpt, cpttpu;
    Serverylite slite = new Serverylite();
    Serverprod prod = new Serverprod();
    public ArrayList<Formadepago> arrfpago = new ArrayList<>();
    public ArrayList<usocfdi> arruso = new ArrayList<>();
    public ArrayList<metodopago> arrmetodo = new ArrayList<>();
    public ArrayList<Agentes> arragente = new ArrayList<>();
    public ArrayList<Cliente> arrcliente = new ArrayList<>();
    daocfdi dcfdi = new daocfdi();
    double descuentos;
    double impuestos;
    double subtotal;
    double total;
    public Usuarios u;
    String relacion = "";
    String traslado = "1";

    //kardex para fac
//    ArrayList<Kardexrcpt> k = new ArrayList<>();
//    ArrayList<Kardexrcpt> k0 = new ArrayList<>();
    ArrayList<pedimento> k1 = new ArrayList<>();
    ArrayList<pedimento> k2 = new ArrayList<>();
    //para factura relacionada
    ArrayList<cargo> arrcargo = new ArrayList<>();
    ArrayList<cargo> arrcargoseleccion = new ArrayList<>();//cargos seleccionados

    /**
     * Creates new form Cliente1
     */
    public fac3tpu() {
        initComponents();
        JtCliente.requestFocus();
        JcPublico.setVisible(false);
        JtFolio1.setVisible(false);
        setdolar();
//        iniciarconexiones();  Solo si se usa solo la clase si no se pasan directamente desde facturacion
// carga en combos los catalogos del sat

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        JtDescuento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JtCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        JtFolio1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        JcMetodo = new javax.swing.JComboBox<>();
        JcForma = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        JcUso = new javax.swing.JComboBox<>();
        Jlfp = new javax.swing.JLabel();
        JlUso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtDetalle = new javax.swing.JTable();
        JcPublico = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Jlsub = new javax.swing.JLabel();
        JlDesc = new javax.swing.JLabel();
        JlIva = new javax.swing.JLabel();
        JlTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtObs = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        JsRel = new javax.swing.JScrollPane();
        JlRel = new javax.swing.JList<>();
        JlTcambio1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JsRel1 = new javax.swing.JScrollPane();
        JlCliente1 = new javax.swing.JList<>();
        JcAgente = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        JcTraslado = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        JcCliente = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        JcUsd1 = new javax.swing.JCheckBox();
        JtTCambio1 = new javax.swing.JTextField();
        JlTcambio2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        JtDescuento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JtDescuento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtDescuento.setText("0");
        JtDescuento.setBorder(null);
        JtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtDescuentoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Descuento");

        JtCliente.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        JtCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtCliente.setBorder(null);
        JtCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtClienteMousePressed(evt);
            }
        });
        JtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtClienteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Pedimento");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JtFolio1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JtFolio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtFolio1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Metodo de Pago");

        JcMetodo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JcMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcMetodoActionPerformed(evt);
            }
        });

        JcForma.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JcForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcFormaActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Forma de Pago");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Uso Cfdi");

        JcUso.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JcUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcUsoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JcMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JcForma, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Jlfp, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JcUso, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlUso, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JcMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(JcForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(JcUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jlfp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlUso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        JtDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JtDetalle.setSelectionBackground(new java.awt.Color(213, 215, 250));
        JtDetalle.setSelectionForeground(new java.awt.Color(0, 0, 0));
        JtDetalle.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JtDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtDetalleMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(JtDetalle);

        JcPublico.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JcPublico.setText("Sin iva");
        JcPublico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcPublicoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Subtotal");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Descuento");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Iva");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Total");

        Jlsub.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Jlsub.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        JlDesc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JlDesc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        JlIva.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JlIva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        JlTotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JlTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jlsub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlIva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jlsub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JlDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JlIva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(JlTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ic_send_128_28719.png"))); // NOI18N
        jLabel2.setToolTipText("Procesar factura");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        JtObs.setColumns(20);
        JtObs.setRows(5);
        jScrollPane2.setViewportView(JtObs);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Observaciones");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Refresh_36729.png"))); // NOI18N
        jLabel3.setToolTipText("Actualiza datos");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        JlRel.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        JlRel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JlRelMousePressed(evt);
            }
        });
        JlRel.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                JlRelValueChanged(evt);
            }
        });
        JsRel.setViewportView(JlRel);

        JlTcambio1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        JlTcambio1.setText("Relacion de factura");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JlTcambio1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(JsRel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JlTcambio1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JsRel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/propagation_calculator_calc_6110.png"))); // NOI18N
        jLabel13.setToolTipText("Relacion de facturas");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });

        JlCliente1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        JlCliente1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JlCliente1.setAutoscrolls(false);
        JlCliente1.setValueIsAdjusting(true);
        JlCliente1.setVisibleRowCount(10);
        JlCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JlCliente1MousePressed(evt);
            }
        });
        JlCliente1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                JlCliente1ValueChanged(evt);
            }
        });
        JsRel1.setViewportView(JlCliente1);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel18.setText("Agentes");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel19.setText("Traslado");

        JcTraslado.setToolTipText("Genera una factura extra para el transporte de mercancia");
        JcTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcTrasladoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel20.setText("Cliente");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        JcUsd1.setText("USD - Dolares");
        JcUsd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcUsd1ActionPerformed(evt);
            }
        });

        JtTCambio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtTCambio1ActionPerformed(evt);
            }
        });

        JlTcambio2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JlTcambio2.setText("Tipo de cambio");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JcUsd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JtTCambio1)
                    .addComponent(JlTcambio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JcUsd1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(JlTcambio2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JtTCambio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JtCliente)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(JtFolio1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JsRel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JcAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JcCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JcTraslado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)
                        .addGap(48, 48, 48))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JtDescuento)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(JcPublico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JsRel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JtFolio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(JcAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel19))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(JcCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(JcTraslado)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JcPublico)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void cargacombos() {//catalogos de Sat
        DefaultComboBoxModel metodo = new DefaultComboBoxModel();
        DefaultComboBoxModel forma = new DefaultComboBoxModel();
        DefaultComboBoxModel uso = new DefaultComboBoxModel();
        DefaultComboBoxModel cliente = new DefaultComboBoxModel();

        daoClientes dc = new daoClientes();
        arrcliente = dc.getClientes(ACobranza);
        for (Formadepago arrfpago1 : arrfpago) {
            forma.addElement(arrfpago1.getFormapago() + " - " + arrfpago1.getConcepto());
        }
        for (metodopago arrmetodo1 : arrmetodo) {
            metodo.addElement(arrmetodo1.getMetodopago() + " - " + arrmetodo1.getDescripcion());
        }
        for (usocfdi arruso1 : arruso) {
            uso.addElement(arruso1.getusocfdi() + " - " + arruso1.getDescripcion());
        }
        for (Cliente arruso1 : arrcliente) {
            cliente.addElement(arruso1.getNombre());
        }
        JcForma.setModel(forma);
        JcMetodo.setModel(metodo);
        JcUso.setModel(uso);
        JcCliente.setModel(cliente);
    }

    /**
     * Se obtienen todos los cliente, se cargan y se busca cual es el agente que
     * llega con la salida y da la opcion de elegir cualquier otro
     */
    private void setAgentes() {
        DefaultComboBoxModel ag = new DefaultComboBoxModel();
        daoAgentes da = new daoAgentes();
        arragente = da.getAgentes(ACobranza);
        for (Agentes agent : arragente) {
            ag.addElement(agent.getNombre());
        }
        JcAgente.setModel(ag);
        for (int i = 0; i < arragente.size(); i++) {
            if (arrcliente.get(JcCliente.getSelectedIndex()).getAgente() == arragente.get(i).getIdagente()) {
                JcAgente.setSelectedIndex(i);
            }
        }
    }

    private void JtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtDescuentoActionPerformed
        if (verificafloat(JtDescuento.getText())) {
//            generatabla();
        } else {
            JOptionPane.showMessageDialog(null, "Error, solo colocar numeros enteros en el descuento");
        }
    }//GEN-LAST:event_JtDescuentoActionPerformed

    private void JtClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtClienteMousePressed
        JtCliente.setText("");
    }//GEN-LAST:event_JtClienteMousePressed

    private void JtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtClienteActionPerformed
        String r = JtCliente.getText();
        //daokardexrcpt dk = new daokardexrcpt();
        daopedimentos dk1 = new daopedimentos();
        //k0 = dk.getkardexfacsimple(rcpt, r, empresacob);
        k1 = dk1.getpedimentosimple(cpttpu, empresacob, r);
//        DefaultComboBoxModel model = new DefaultComboBoxModel();
//        int folio = 0;
//        for (int i = 0; i < k0.size(); i++) {
//            if (folio != k0.get(i).getFolio()) {
//                model.addElement(k0.get(i).getFolio() + " - " + k0.get(i).getCli().getNombre());
//            }
//            folio = k0.get(i).getFolio();
//        }
//        JtFolio1.setModel(model);
//        JtFolio1.requestFocus();
        llenalistasalida();
        cargacombos();
    }//GEN-LAST:event_JtClienteActionPerformed

    private void JcMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcMetodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcMetodoActionPerformed

    private void JcFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcFormaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcFormaActionPerformed

    private void JcUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcUsoActionPerformed
        String regimen = arrcliente.get(JcCliente.getSelectedIndex()).getRegimen();
        String uso = arruso.get(JcUso.getSelectedIndex()).getusocfdi();
        verificaregimen(sqlcfdi, regimen, uso);
    }//GEN-LAST:event_JcUsoActionPerformed

    private void JtFolio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtFolio1ActionPerformed
//        seleccionfolio();
    }//GEN-LAST:event_JtFolio1ActionPerformed

    private void JcPublicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcPublicoActionPerformed
//        generatabla();
    }//GEN-LAST:event_JcPublicoActionPerformed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        if (!k2.isEmpty()) {
            String regimen = arrcliente.get(JcCliente.getSelectedIndex()).getRegimen();
            String uso = arruso.get(JcUso.getSelectedIndex()).getusocfdi();

            boolean a = verificafloat(JtDescuento.getText());
            boolean a1 = verificadetalle();
            boolean a2 = verificaregimen(sqlcfdi, regimen, uso);
            if (!a) {
                JOptionPane.showMessageDialog(null, "Error, solo colocar numeros enteros en el descuento");
            }
            if (!a1) {
                JOptionPane.showMessageDialog(null, "Error, Verifica los precios");
            }
//            System.out.println(a + " - " + a1);
            if (!a || !a1 || !a2) {
                JtDescuento.requestFocus();
            } else {
                traslado = (JcTraslado.isSelected()) ? "1" : "0";
                factura f = new factura();
                int row = 0;
                String condicion;
                java.util.Date date = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
                daofactura dfac = new daofactura();
                ArrayList<Dfactura> arrf = new ArrayList<>();
                Formateo_Nempresas fn= new Formateo_Nempresas();
                DecimalFormat formateador = new DecimalFormat("####.##");//para los decimales
                if (JcPublico.isSelected()) {//Setear impuestos
                    f.setIva(0);
                    f.setImpuestos(0);
                } else {
                    f.setIva(16);
                }
                // fin setear impuestos
//                Funcion exclusiva paar evitar que colisiones 2 peticiones al instante
//                Provisional en lo que se programa una funcion de turnos en el servidor
                Nocolision n = new Nocolision();
                f.setFolio(dfac.getmaxfolio(rcpt, "FAC"));//Obtiene y setea el foliomaximo de *documentos pero de cpt ath no de tpu
                n.setConnecxiones(rcpt, f.getFolio());
                n.start();
//                JOptionPane.showMessageDialog(null, "Espera al msj de Aceptacion de folio "+n.isAlive());
                do {

                } while (n.isAlive());
                int rowc = JcCliente.getSelectedIndex();
                f.setExportacion("01");
                f.setFolio(n.getfolio());
                daokardexrcpt dk = new daokardexrcpt();
//                Se obtiene el folio del kardex
                f.setFoliokardex(dk.maxkardexsincuenta(cpttpu));// folio del kardex
                f.setClaveusuario(u.getUsuario());
                f.setSerie("FAC");
                f.setTurno(u.getTurno());
                f.setConceptos(15);
                f.setFecha(sdf.format(date));
                f.setIdcliente(arrcliente.get(rowc).getCvecliente());
                f.setNombre(arrcliente.get(rowc).getNombre());
                f.setRfc(arrcliente.get(rowc).getRfc());
                f.setCalle(arrcliente.get(rowc).getCalle());
                f.setNexterior("0");
                f.setNinterior("0");
                f.setColonia(arrcliente.get(rowc).getColonia());
                f.setMunicipio(arrcliente.get(rowc).getCiudad());
                f.setEstado(arrcliente.get(rowc).getEstado());
                f.setPais(arrcliente.get(rowc).getPais());
                f.setCp(arrcliente.get(rowc).getCp());
                f.setRegimen(arrcliente.get(rowc).getRegimen());
                f.setPlazo(arrcliente.get(rowc).getPlazo());
                f.setObservaciones(JtObs.getText().toUpperCase());
                f.setTotalcajas(0);
                f.setCantidadxcaja(0);
                f.setFormapago(arrfpago.get(JcForma.getSelectedIndex()).getFormapago());
                f.setMetodopago(arrmetodo.get(JcMetodo.getSelectedIndex()).getMetodopago());
                f.setDescmetodop(arrmetodo.get(JcMetodo.getSelectedIndex()).getDescripcion());
                f.setUsocfdi(arruso.get(JcUso.getSelectedIndex()).getusocfdi());
                condicion = (f.getMetodopago().equals("PUE")) ? "Contado" : "Credito";
                f.setCondicion(condicion);
                f.setLugarexpedicion(fn.getLugar_exp());
//                f.setAgente(k.get(row).getCli().getAgente());
                f.setAgente(arrcliente.get(rowc).getAgente());

                if (JcUsd1.isSelected()) {
                    f.setMoneda("USD");
                    f.setTipocambio(Double.parseDouble(JtTCambio1.getText()));
                } else {
                    f.setMoneda("MXN");
                    f.setTipocambio(1);
                }
                f.setTiporelacion(relacion);
                f.setEmpresa(fn.getEmpresa(u.getTurno(), ""));
                String folios = "";
                String facturas = "";
                ArrayList<String> arruuid = new ArrayList<>();
//                almacenar en un array los folios fiscales por si hay una relacion a la factura
                if (!relacion.equals("")) {
                    for (int i = 0; i < arrcargoseleccion.size(); i++) {
                        if (i == 0) {
                            folios = arrcargoseleccion.get(i).getFoliofiscal();
                            facturas = arrcargoseleccion.get(i).getReferencia();
                        } else {
                            folios += ", " + arrcargoseleccion.get(i).getFoliofiscal();
                            facturas += ", " + arrcargoseleccion.get(i).getReferencia();
                        }
                        arruuid.add(arrcargoseleccion.get(i).getFoliofiscal());
                    }
                    f.setRefncredito(facturas);
                    f.setSeriefoliofiscalorig(folios);
                    f.setArruuid(arruuid);
                }
                double iva = 0.00;
                if (!JcPublico.isSelected()) {// verifica 
                    iva = 0.16;
                }
                int totalpares = 0;// Se usa para la tabla facturas
                impuestos = 0;
                descuentos = 0;
//                Detallado de productos selecionados
                for (int i = 0; i < k2.size(); i++) {
                    Dfactura df = new Dfactura();
                    if (JtDetalle.getValueAt(i, 7).toString().equals("*")) {
                        double precio = Double.parseDouble(formateador.format(Double.parseDouble(JtDetalle.getValueAt(i, 3).toString())));
                        double tpares = Double.parseDouble(formateador.format(Double.parseDouble(JtDetalle.getValueAt(i, 2).toString())));
                        double desc = Double.parseDouble(JtDescuento.getText()) / 100;
                        double descuento = Double.parseDouble(formateador.format((tpares * precio) * desc));
                        df.setDescripcion(k2.get(i).getDp().getMatped());
                        df.setRenglon(i + 1);
                        df.setProducto(k2.get(i).getDp().getId_material());
                        df.setCantidadfloat(tpares);
                        df.setCodigo(k2.get(i).getDp().getCodigosat());
                        df.setUmedida(k2.get(i).getDp().getUnidad());
                        df.setDureza(k2.get(i).getDp().getDureza());
                        df.setId_dpedimento(k2.get(i).getDp().getId_dpedimento());
                        df.setId_pedimento(k2.get(i).getId_pedimento());
                        df.setDescumedida(k2.get(i).getDp().getUnidad());
                        df.setPrecio(Double.parseDouble(formateador.format(precio)));
                        df.setBase(Double.parseDouble(formateador.format(precio * tpares)));
                        df.setImpuesto("002");
                        df.setTipofactor("Tasa");
//                        Este en especial por cuestion de centavos
                        String as = formateador.format(((tpares * precio) - descuento) * iva);
                        df.setImporta(Double.parseDouble(as));
                        String as1 = formateador.format(descuento);
                        df.setDescuento(Double.parseDouble(as1));
                        df.setTasaocuota(iva + "");
                        arrf.add(df);
                        totalpares += tpares;
                        impuestos += Double.parseDouble(as);
                        descuentos += Double.parseDouble(as1);
                    }
                }
                total = subtotal - descuentos + impuestos;
                f.setTotalpares(totalpares);
                f.setArr(arrf);
                f.setImpuestos(formatdecimal(impuestos));
                f.setDescuento(formatdecimal(descuentos));
                f.setSubtotal(formatdecimal(subtotal));
                f.setTotal(formatdecimal(total));
                //id del documento recien añadido
//                Obtiene y guarda en una lista lols asientos contables de cobranza
                ArrayList<Poliza> arrpoliza = dfac.getasientoscontable(ACobranza);
                ArrayList<Poliza> arrpolizas = new ArrayList<>();
                int conta = 0;
//                Clase para formateo de datos
                Formateodedatos fd = new Formateodedatos();
//                Polizas
                for (int i = 0; i < arrpoliza.size(); i++) {
                    String c = arrpoliza.get(i).getCuentalarga();
//                    Formatea el numero de cliente a un formato en especifc
                    String cuenta = fd.convertcliente(c + fd.formatclientedigito(arrcliente.get(rowc).getCvecliente() + ""));
                    Poliza p = new Poliza();
                    p.setCuenta(1);
                    p.setSub(5);
                    p.setFecha(sdf.format(date));
                    p.setFolio(f.getFolio() + "");
                    p.setIdcliente(arrcliente.get(rowc).getCvecliente());
                    p.setIdentificacion("M");
                    p.setCuentalarga(cuenta);
                    p.setCa(arrpoliza.get(i).getCa());
                    p.setOrden(arrpoliza.get(i).getOrden());
                    p.setDiario("000");
                    p.setMext("            0.00");
                    p.setAcumulativo(arrpoliza.get(i).getAcumulativo());
                    p.setConcepto(arrpoliza.get(i).getConcepto() + f.getFolio() + "");
                    if (arrpoliza.get(i).getCuentalarga().equals("4005")) {
                        p.setReferencia(arrcliente.get(rowc).getAg().getIdcanal() + "1" + fd.convierteagente(String.valueOf(arrcliente.get(rowc).getAgente())) + " 4.001");
                    } else {
                        p.setReferencia("4.001");
                    }
                    switch (conta) {
                        case 0:
                            p.setImporte(fd.ftotal(String.valueOf(formatdecimal(total))));
                            conta++;
                            break;
                        case 1:
                            p.setImporte(fd.ftotal(String.valueOf(formatdecimal(impuestos))));
                            conta++;
                            break;
                        case 2:
                            p.setImporte(fd.ftotal(String.valueOf(formatdecimal(subtotal - descuentos))));
                            conta = 0;
                            break;
                    }
                    arrpolizas.add(p);
                }
                f.setArrpolizas(arrpolizas);

//                Tiene 3 procesos de commit, 1. la fatura. 2. los sellos y cadena original, 3. sellos fiscales
                if (arrf.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Error al realizar factura, intente capturar de nuevo");
                    vaciarcampos();
                } else {
//                    Insertar en la bd todos los movimientos relacionados donde aqui en tpu
//                    para tpu se insertará en el (kardex,pedidos y actualizacion de pedimento)
//                    para ath se cargan(documentos y cargos), por lo tanto, en tpu no podra ver la factura
//                    y desde ath no se podra ver la salida pero ambas estarán relacionadas
                    int id = dfac.nuevafactpuATH(cpt, f, ACobranza, cpttpu, rcpt);
                    if (id != 0) {
//                        System.out.println("Exito");
//                    La factura en ath entrará como especial y no como pares porque no afecta en stock para ese sistema
                        daoxmlE dx = new daoxmlE();
                        f.setId(id);
                        dx.generarfac(f, cpt, sqlempresa);
                        timbrarXML tim = new timbrarXML();
                        Sellofiscal s = tim.timbrar(f.getSerie() + "_" + f.getFolio(), nombre, sqlempresa, f.getEmpresa());
//                    Sellofiscal s = tim.timbrar(f.getSerie() + "_" + f.getFolio(), "", sqlempresa, "2");
//                      Actualiza los sellos e informacion del sat de acuerdo a la factura
                        dfac.Updatesellofiscal(cpt, s, id);
                        setreport(f.getFolio(), f.getRegimen(), f.getMoneda(), "FAC");
                        if (traslado.equals("0")) {
                            JOptionPane.showMessageDialog(null, "Proceso terminado: \n " + s.getEstado());
                            vaciarcampos();
                            JtCliente.requestFocus();
                        }
                    }
//                    if (traslado.equals("1")) {
//                        int nfolio = dfac.getmaxtraslado(cpt) + 1;
//                        f.setFolio(nfolio);
//                        f.setSerie("T");
//                        f.setTiporelacion("05");
//                        f.setFoliofiscalorig(s.getUuid());
//                        id = dfac.nuevafacTraslado(cpt, rcpt, f);
//                        if (id != 0) {
////                            System.out.println("Exito traslado");
//                            daoxmlTraslado dx = new daoxmlTraslado();
//                            f.setId(id);
//                            dx.generarfac(f, cpt, sqlempresa);
//                            timbrarXML tim = new timbrarXML();
//                            s = tim.timbrar(f.getSerie() + "_" + f.getFolio(), nombre, sqlempresa, f.getEmpresa());
//                            dfac.Updatesellofiscal(cpt, s, id);
//                            setreport(f.getFolio(), f.getRegimen(), "XXX", "T");
//                            JOptionPane.showMessageDialog(null, "Proceso de facturacion y traslado terminado: \n " + s.getEstado());
//                            vaciarcampos();
//                            JtCliente.requestFocus();
//                        }
//                    }
                }

            }
        }
    }//GEN-LAST:event_jLabel2MousePressed

    /**
     * Funcion para determinar si la cantidad decimal es redondeada o truncada
     * ya que el sat maneja ambos y no solo uno porque si no aveces saldran mal
     * los calculos de los centavos
     *
     * @param cant cantidad en decimal
     * @return Cantidad redondeada o truncada
     */
    private double formatdecimal(double cant) {
        int dato = 0;
        int punto = 0;
        boolean band = false;
        double resp;
        String c = String.valueOf(cant);
//        String cadena = "";
        for (int i = 0; i < c.length(); i++) {
//            Empieza a tomar datos despues del punto
            if (c.charAt(i) == '.') {
                band = true;
            }
            if (band) {
//                3 digitos de decimal para saber qe hacer con los decimales
                if (punto == 3) {
                    dato = Integer.parseInt(c.charAt(i) + "");
                    i = c.length();
                    break;
                }
//                cadena += c.charAt(i);
                punto++;
            }
        }
        if ((dato <= 5)) {
            resp = BigDecimal.valueOf(cant).setScale(2, RoundingMode.FLOOR).doubleValue();
        } else {
            resp = BigDecimal.valueOf(cant).setScale(2, RoundingMode.HALF_UP).doubleValue();
        }
        return resp;
    }

    /**
     *
     * @param folio Folio de la factura
     * @param arrmetodo Array que contiene el metodo de pago
     * @param arruso Array que contiene el uso de cfdi
     * @see Despliegue y creacion del archivo pdf con los datos previamente
     * creados El reporte fue previamente creado en un modulo anterior que solo
     * creaba el pdf el proyecto se llama "Facturas"
     *
     */
    private void setreport(int folio, String regimen, String moneda, String serie) {
        try {
            daoempresa d = new daoempresa();
//            Identificar si es de ath o uptown
            String n = "1";
            String logo = "AF.png";
            String ser;
            String report;

            Empresas e = d.getempresarfc(sqlempresa, n);
            String lugar = "BLVD LAS TORRES 516 DEL VALLE SAN FRANCISCO DEL RINCON GUANAJUATO " + e.getCp();
//             fin identificar empresa
            Map parametros = new HashMap();
//            Clase que contiene el numero convertido a caracter
            convertnum conv = new convertnum();
            convertirNumeros cnum = new convertirNumeros();
            DecimalFormat formateador = new DecimalFormat("####.##");//para los decimales
            String numeros = formateador.format(total);
            String letratotal = "";
            if (serie.equals("T")) {
                letratotal = "CERO PESOS, 00/100";
                ser = "T";
                report = "index_traslado";
            } else {
                letratotal = cnum.Convertir(numeros, true, moneda);
                ser = "FAC";
                report = "indextpu";
            }
//            Agregar parametros al reporte
            parametros.put("folio", folio);
//            parametros.put("totalletra", conv.controlconversion(total).toUpperCase());
            parametros.put("totalletra", letratotal);
            parametros.put("nombre", e.getNombre());
            parametros.put("rfc", e.getRfc());
            parametros.put("regimen", e.getRegimen());
            parametros.put("lugar", lugar);
            parametros.put("comprobante", e.getNumcertificado());
            parametros.put("logo", "C:\\af\\bin\\" + logo);// direcion predefinida, posible cambiar en un futuro
            parametros.put("metodo", arrmetodo.get(JcMetodo.getSelectedIndex()).getDescripcion());
            parametros.put("uso", arruso.get(JcUso.getSelectedIndex()).getDescripcion());
            parametros.put("serie", ser);
            parametros.put("regimencliente", regimen);

            JasperReport jasper = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportes/index.jasper"));
            JasperPrint print = JasperFillManager.fillReport(jasper, parametros, cpt);
            JasperViewer ver = new JasperViewer(print, false); //despliegue de reporte
            ver.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            ver.setTitle("FAC " + folio);
            ver.setVisible(true);
//            Exportacion al archivo pdf
            JRExporter exporter = new JRPdfExporter();
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, print);
            exporter.setParameter(JRExporterParameter.OUTPUT_FILE, new java.io.File(e.getXml() + "\\" + ser + "_" + folio + ".pdf"));
            exporter.exportReport();
        } catch (JRException ex) {
            Logger.getLogger(fac1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void JtDetalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtDetalleMousePressed
        String active = JtDetalle.getValueAt(JtDetalle.getSelectedRow(), 7).toString();
        if (active.equals("")) {
            JtDetalle.setValueAt("*", JtDetalle.getSelectedRow(), 7);
        } else {
            JtDetalle.setValueAt("", JtDetalle.getSelectedRow(), 7);
        }
        if (!k2.isEmpty()) {
            actualizaimportes();
        }
    }//GEN-LAST:event_JtDetalleMousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        actualizaimportes();
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        int row = JcCliente.getSelectedIndex();
        if (k1.isEmpty() && JtFolio1.getSelectedIndex() == -1) {

        } else {
            FactsReltpu f = new FactsReltpu(null, true);
            daofactura df = new daofactura();
            arrcargo = df.getfactstoFACReltpu(cpt, arrcliente.get(row).getCvecliente() + "", empresacob);
            f.arrcargo = arrcargo;
            f.setVisible(true);
            arrcargoseleccion = f.arrcargoseleccion;
            if (!arrcargoseleccion.isEmpty()) {
//            DefaultListModel<String> model = new DefaultListModel<>();
//            for (cargo arrcargoseleccion1 : arrcargoseleccion) {
//                model.addElement(arrcargoseleccion1.getReferencia() + " - " + arrcargoseleccion1.getDescuento());
//            }
//            JlRel.setModel(model);
                llenalista();
                relacion = "07";
            }
        }
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed

    }//GEN-LAST:event_jLabel6MousePressed

    private void JlRelValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_JlRelValueChanged

    }//GEN-LAST:event_JlRelValueChanged

    private void JlRelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlRelMousePressed

    }//GEN-LAST:event_JlRelMousePressed

    private void JlCliente1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlCliente1MousePressed

        String folios = "referencia ='0'";
        
        seleccionfolio(folios);
        setAgentes();

    }//GEN-LAST:event_JlCliente1MousePressed

    private void JlCliente1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_JlCliente1ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_JlCliente1ValueChanged

    private void JcTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcTrasladoActionPerformed
        if (JcTraslado.isSelected()) {
            JOptionPane.showMessageDialog(null, "El traslado de productos esta activado, 1");
        } else {
            JOptionPane.showMessageDialog(null, "El traslado esta deesactivado, 0");
        }
    }//GEN-LAST:event_JcTrasladoActionPerformed

    private void JcUsd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcUsd1ActionPerformed
        setdolar();
    }//GEN-LAST:event_JcUsd1ActionPerformed

    private void JtTCambio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtTCambio1ActionPerformed
        if (!verificafloat(JtTCambio1.getText().toUpperCase())) {
            JOptionPane.showMessageDialog(null, "Error, Introduce un valor valido en el tipo de cambio");
            JtTCambio1.requestFocus();
        }
    }//GEN-LAST:event_JtTCambio1ActionPerformed

    private void llenalista() {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (cargo arrcargoseleccion1 : arrcargoseleccion) {
            model.addElement(arrcargoseleccion1.getReferencia() + " - " + arrcargoseleccion1.getDescuento());
        }
        JlRel.setModel(model);
    }

//    Llena la lista con todos los folios de acuerdo al cliente
    private void llenalistasalida() {
        DefaultListModel<String> model = new DefaultListModel<>();
        int folio = 0;
        for (int i = 0; i < k1.size(); i++) {
            if (k1.get(i).getReferencia().equals("0")) {
                model.addElement(k1.get(i).getReferencia() + " - " + k1.get(i).getNprov());
            }
//            folio = k1.get(i).getId_pedimento();
        }
        JlCliente1.setModel(model);
        JlCliente1.requestFocus();
    }

    private void vaciarcampos() {
        if (!k1.isEmpty()) {
            k1.clear();
        }
        if (!k2.isEmpty()) {
            k2.clear();
        }
        if (!arrcargo.isEmpty()) {
            arrcargo.clear();
        }
        if (!arrcargoseleccion.isEmpty()) {
            arrcargoseleccion.clear();
        }
        JcUsd1.setSelected(false);
        setdolar();
        relacion = "";
        JtDescuento.setText("0");
        JtObs.setText("");
        cargacombos();
        generatabla();
        JtCliente.setText("");
        JtCliente.requestFocus();
        llenalista();
        llenalistasalida();
    }

    private void seleccionfolio(String folios) {
//        cpt de tpu
        daopedimentos dk1 = new daopedimentos();
        k2 = dk1.getpedimentoaadv(cpttpu, folios,u.getTurno());
//        String r = k0.get(JtFolio1.getSelectedIndex()).getFolio() + "";
//        k = dk.getkardexfac(rcpt, r, empresacob);// nueva carga de datos
//        k = dk.getkardexfacMulti(rcpt, empresacob, folios);
////        System.out.println(k.size());
        generatabla();
//        setAgentes();
    }

    public final void generatabla() {//Tabla actualizable con respecto al descuento e iva
        subtotal = 0;
        impuestos = 0;
        descuentos = 0;
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Material");//0  estilo combinacion corrida
        model.addColumn("Clave SAT");//1
        model.addColumn("Cantidad");//2
        model.addColumn("Precio");//3
        model.addColumn("Descuento");//4
        model.addColumn("Impuestos");//5
        model.addColumn("Importe");//6
        model.addColumn("Activo");//7
        model.addColumn("Unidad");//8
        model.addColumn("Pedimento");//9
        double iva = 0;
        DecimalFormat formateador = new DecimalFormat("####.##");//para los decimales
        if (!JcPublico.isSelected()) {// verifica 
            iva = 0.16;
        }
        if (!k2.isEmpty()) {// rellena de datos de acuerdo a las lineas que se capturen
            model.setRowCount(k2.size());
            for (int i = 0; i < k2.size(); i++) {
                double tpares = k2.get(i).getDp().getCantrestante();
                double desc = Double.parseDouble(JtDescuento.getText()) / 100;
                double precio = k2.get(i).getDp().getPrecio();
                double descuento = (tpares * precio) * desc;
                model.setValueAt(k2.get(i).getDp().getMatped(), i, 0);
                model.setValueAt(k2.get(i).getDp().getCodigosat(), i, 1);
                model.setValueAt(tpares, i, 2);
                model.setValueAt(formateador.format(precio), i, 3);
                model.setValueAt(formateador.format(descuento), i, 4);
                model.setValueAt(formateador.format(((tpares * precio) - descuento) * iva), i, 5);
                model.setValueAt(formateador.format((tpares * precio) - descuento), i, 6);
                model.setValueAt("", i, 7);
                model.setValueAt(k2.get(i).getDp().getUnidad(), i, 8);
                model.setValueAt(k2.get(i).getReferencia(), i, 9);
                //suma de totales
                subtotal += tpares * precio;
            }
        }
        //Variables para manejo de totales
        descuentos = subtotal * Double.parseDouble(JtDescuento.getText()) / 100;
        impuestos = ((subtotal - descuentos) * iva);
        total = subtotal - descuentos + impuestos;
        //Solo para despliqgue de informacion
        JlIva.setText(formateador.format(impuestos));
        Jlsub.setText(formateador.format(subtotal));
        JlDesc.setText(formateador.format(descuentos));
        JlTotal.setText(formateador.format(total));
        JtDetalle.setModel(model);
    }

    private void actualizaimportes() {
        subtotal = 0;
        impuestos = 0;
        descuentos = 0;
        double iva = 0;
        boolean resp = true;
        if (!JcPublico.isSelected()) {// verifica 
            iva = 0.16;
        }
        DecimalFormat formateador = new DecimalFormat("####.##");
        if (!k2.isEmpty()) {// rellena de datos de acuerdo a las lineas que se capturen
            for (int i = 0; i < k2.size(); i++) {
                String act = JtDetalle.getValueAt(i, 7).toString();// Se obtiene el valor del activo
                if (!verificafloat(JtDetalle.getValueAt(i, 3).toString())) {// que no se pase algo que no sea un numero
                    JOptionPane.showMessageDialog(null, "Error, Verifica los precios");
                    JtDetalle.setValueAt("0", i, 3);
                    resp = false;
                    break;
                } else {
                    if (act.equals("*")) {// tomara en cuanta solo los que estan activos
                        double tpares = Double.parseDouble(JtDetalle.getValueAt(i, 2).toString());
                        if (tpares > k2.get(i).getDp().getCantrestante()) {
                            JOptionPane.showMessageDialog(null, "Error, El valor introducido en cantidad no puede ser mayor a la cantidad restante del material");
                        } else {
                            double desc = Double.parseDouble(JtDescuento.getText()) / 100;
                            double precio = Double.parseDouble(JtDetalle.getValueAt(i, 3).toString());
                            double descuento = (tpares * precio) * desc;
                            JtDetalle.setValueAt(precio, i, 3);
                            JtDetalle.setValueAt(formateador.format(descuento), i, 4);
                            JtDetalle.setValueAt(formateador.format(((tpares * precio) - descuento) * iva), i, 5);
                            JtDetalle.setValueAt(formateador.format((tpares * precio)), i, 6);
                            //suma de totales
                            descuentos += Double.parseDouble(formateador.format(descuento));
//                        subtotal += Double.parseDouble(formateador.format((tpares * precio)));
                            subtotal += tpares * precio;
//                        impuestos += Double.parseDouble(formateador.format(((tpares * precio) - descuento) * iva));
                            impuestos += ((tpares * precio) - descuento) * iva;
                        }

                    }
                }
            }
            if (resp) {// Si, y solo si es un entero o decimal
                //Variables para manejo de totales
//                descuentos = subtotal * Float.parseFloat(JtDescuento.getText()) / 100;
                //impuestos =(float) ((subtotal - descuentos) * iva);
                double desc = Double.parseDouble(JtDescuento.getText()) / 100;
                descuentos = subtotal * desc;
                impuestos = (subtotal - descuentos) * iva;
                total = impuestos + subtotal - descuentos;
//                total = subtotal - descuentos + impuestos;
////                System.out.println(total + " -- " + impuestos + " -- " + subtotal + " -- " + descuentos+" --"+tot);
////                System.out.println(impuestos);
                //Solo para despliqgue de informacion
                JlIva.setText(formateador.format(impuestos));
                Jlsub.setText(formateador.format(subtotal));
                JlDesc.setText(formateador.format(descuentos));
                JlTotal.setText(formateador.format(total));
            }
        }
    }

    private void setdolar() {
        if (JcUsd1.isSelected()) {
            JlTcambio2.setVisible(true);
            JtTCambio1.setVisible(true);
            JtTCambio1.requestFocus();
        } else {
            JlTcambio2.setVisible(false);
            JtTCambio1.setVisible(false);
        }
    }

    private boolean verificaint(String cad) {
        boolean resp = false;
        String patt = "[0-9]+";
        Pattern pat = Pattern.compile(patt);
        Matcher match = pat.matcher(cad);
        if (match.matches()) {
            resp = true;
        }
        return resp;
    }

    private boolean verificafloat(String cad) {
        boolean resp = false;
        String patt = "[0-9]+||[0-9]+.[0-9]+";
        Pattern pat = Pattern.compile(patt);
        Matcher match = pat.matcher(cad);
        if (match.matches()) {
            resp = true;
        }
        return resp;
    }

    private boolean verificadetalle() {
        boolean resp = true;
        for (int i = 0; i < k2.size(); i++) {
            String s = JtDetalle.getValueAt(i, 7).toString();
            if (s.equals("*")) {
                String precio = JtDetalle.getValueAt(i, 3).toString();
                double cantidad = Double.parseDouble(JtDetalle.getValueAt(i, 2).toString());
                if (!verificafloat(precio) || cantidad == 0 || Double.parseDouble(precio) == 0) {
                    JtDetalle.setValueAt("", i, 7);
                    resp = false;
                    break;
                }
            }

        }
        return resp;
    }

    private boolean verificaregimen(Connection cfdi, String regimen, String uso) {
        daocfdi df = new daocfdi();
        boolean a = true;
        String resp = df.getRegimenxuso(cfdi, regimen, uso);
        if (resp.equals("")) {
            JOptionPane.showMessageDialog(null, "Error, El regimen del cliente no se puede usar con este uso cfdi");
            a = false;
        }
        return a;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcAgente;
    private javax.swing.JComboBox<String> JcCliente;
    private javax.swing.JComboBox<String> JcForma;
    private javax.swing.JComboBox<String> JcMetodo;
    private javax.swing.JCheckBox JcPublico;
    private javax.swing.JCheckBox JcTraslado;
    private javax.swing.JCheckBox JcUsd1;
    private javax.swing.JComboBox<String> JcUso;
    private javax.swing.JList<String> JlCliente1;
    private javax.swing.JLabel JlDesc;
    private javax.swing.JLabel JlIva;
    private javax.swing.JList<String> JlRel;
    private javax.swing.JLabel JlTcambio1;
    private javax.swing.JLabel JlTcambio2;
    private javax.swing.JLabel JlTotal;
    private javax.swing.JLabel JlUso;
    private javax.swing.JLabel Jlfp;
    private javax.swing.JLabel Jlsub;
    private javax.swing.JScrollPane JsRel;
    private javax.swing.JScrollPane JsRel1;
    public javax.swing.JTextField JtCliente;
    private javax.swing.JTextField JtDescuento;
    private javax.swing.JTable JtDetalle;
    private javax.swing.JComboBox<String> JtFolio1;
    private javax.swing.JTextArea JtObs;
    private javax.swing.JTextField JtTCambio1;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
