/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneltpu;

import DAO.daoalmacenes;
import DAO.daodurezas;
import DAO.daomateriales;
import DAO.daopedimentos;
import Modelo.Conexiones;
import Modelo.Usuarios;
import Modelo.pedimento;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author GATEWAY1-
 */
public class Pedimento1 extends javax.swing.JPanel {

    Conexiones c = new Conexiones();
    Usuarios u;
    ArrayList<pedimento> arr = new ArrayList<>();

    /**
     * Creates new form Pedimento1
     *
     * @param co
     * @param u
     */
    public Pedimento1(Conexiones co, Usuarios u) {
        initComponents();
        this.c = co;
        this.u = u;
//        JmAddmaterial.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pop = new javax.swing.JPopupMenu();
        JmImprimir = new javax.swing.JMenuItem();
        JmAddmaterial = new javax.swing.JMenuItem();
        JtCliente = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtDetalle = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        JmImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/file_pdf_download_icon-icons.com_68954.png"))); // NOI18N
        JmImprimir.setText("Imprimir pedimento");
        JmImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmImprimirActionPerformed(evt);
            }
        });
        pop.add(JmImprimir);

        JmAddmaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/add_plus_interface_icon_181584.png"))); // NOI18N
        JmAddmaterial.setText("Añadir nuevo material");
        JmAddmaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmAddmaterialActionPerformed(evt);
            }
        });
        pop.add(JmAddmaterial);

        setBackground(new java.awt.Color(255, 255, 255));

        JtCliente.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        JtCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtCliente.setBorder(null);
        JtCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtClienteMousePressed(evt);
            }
        });
        JtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtClienteActionPerformed(evt);
            }
        });

        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JtDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JtDetalle.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JtDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtDetalleMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(JtDetalle);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Magnifier_29783.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1257, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(JtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(JtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JtClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtClienteMousePressed
        JtCliente.setText("");
    }//GEN-LAST:event_JtClienteMousePressed

    private void JtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtClienteActionPerformed
        settabla();
    }//GEN-LAST:event_JtClienteActionPerformed

    private void JtDetalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtDetalleMousePressed
        if (evt.getButton() == 3) {// activar con clic derecho
            pop.show(evt.getComponent(), evt.getX(), evt.getY());
        }
        String p = arr.get(JtDetalle.getSelectedRow()).getReferencia();
        if (p.equals("0") || u.getTurno().equals("7") || u.getTurno().equals("6")) {
            JmAddmaterial.setVisible(true);
        } else {
            JmAddmaterial.setVisible(false);
        }
    }//GEN-LAST:event_JtDetalleMousePressed

    private void JmImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmImprimirActionPerformed
        try { 
            Map parametros = new HashMap();
            int ped = arr.get(JtDetalle.getSelectedRow()).getId_pedimento();
//            System.out.println(ped);
            parametros.put("id", ped);
            JasperReport jasper = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportestpu/Pedimento.jasper"));
            JasperPrint print = JasperFillManager.fillReport(jasper, parametros, c.getCpttpu());
            JasperViewer ver = new JasperViewer(print, false); //despliegue de reporte
            ver.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            ver.setTitle("Pedimento " + arr.get(JtDetalle.getSelectedRow()).getReferencia());
            ver.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Pedimento1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JmImprimirActionPerformed

    private void JmAddmaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmAddmaterialActionPerformed
        int row = JtDetalle.getSelectedRow();
        if (arr.get(row).getReferencia().equals("0") || arr.get(row).getReferencia().equals("1") 
                || u.getTurno().equals("7") || u.getTurno().equals("6")) {
            NuevomatPedimentoadd n = new NuevomatPedimentoadd(null, true);
            daomateriales am = new daomateriales();
            daoalmacenes da = new daoalmacenes();
            daodurezas dd = new daodurezas();
            n.u=u;
            n.cpt = c.getCpttpu();
            n.ped = arr.get(row);
            n.arrmat = am.getmateriales(c.getCpttpu(), "", u.getTurno());
            n.arralm = da.getalmacenescpt(c.getCpttpu());
            n.arrdur = dd.getdurezas(c.getCpttpu());
            n.setcombos();
            n.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "No se pueden agregar materiales extra a un pedimento que no sea el cero");
        }
    }//GEN-LAST:event_JmAddmaterialActionPerformed

    private void settabla() {
        daopedimentos s = new daopedimentos();
        arr = s.getallpedimento(c.getCpttpu(), JtCliente.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Pedimento");
        model.addColumn("Total");
        model.addColumn("Cantidad");
        model.addColumn("Proveedor");
        model.setNumRows(arr.size());
        for (int i = 0; i < arr.size(); i++) {
            model.setValueAt(arr.get(i).getReferencia(), i, 0);
            model.setValueAt(arr.get(i).getTotal(), i, 1);
            model.setValueAt(arr.get(i).getTcantidad(), i, 2);
            model.setValueAt(arr.get(i).getNprov(), i, 3);
        }
        JtDetalle.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JmAddmaterial;
    private javax.swing.JMenuItem JmImprimir;
    public javax.swing.JTextField JtCliente;
    private javax.swing.JTable JtDetalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu pop;
    // End of variables declaration//GEN-END:variables
}
