/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Avances;

import DAO.daoAvances;
import Modelo.Colsdepartamentos;
import Modelo.Davance;
import Paneles.fac1;
import Server.Serverprod;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author GATEWAY1-
 */
public class Avancesprod extends javax.swing.JDialog {

    public Connection c, sqliteuser;

    /**
     * Creates new form Nuevomaterial
     */
    public Avancesprod(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        grupop.add(JrCondensado);
        grupop.add(JrDetallado);
        bgrupo2.add(JrDia);
        bgrupo2.add(JrSemana);
        bgrupo2.add(JrMes);
        JrDia.setSelected(true);
        JrCondensado.setSelected(true);
        jPanel3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupop = new javax.swing.ButtonGroup();
        bgrupo2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Fecha = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        Fecha1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        JrSemana = new javax.swing.JRadioButton();
        JrDia = new javax.swing.JRadioButton();
        JrMes = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        JrDetallado = new javax.swing.JRadioButton();
        JrCondensado = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/Recursos/bordemorado.png")))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Fecha inicial");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ic_send_128_28719.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Cancel_icon-icons.com_54824.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Avances de produccion");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Fecha inicial");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        JrSemana.setBackground(new java.awt.Color(255, 255, 255));
        JrSemana.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JrSemana.setText("Semanal");
        JrSemana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JrSemanaMousePressed(evt);
            }
        });

        JrDia.setBackground(new java.awt.Color(255, 255, 255));
        JrDia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JrDia.setText("Dia");
        JrDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JrDiaMousePressed(evt);
            }
        });

        JrMes.setBackground(new java.awt.Color(255, 255, 255));
        JrMes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JrMes.setText("Mensual");
        JrMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JrMesMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JrDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JrSemana, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JrMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(JrDia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JrSemana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JrMes)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        JrDetallado.setBackground(new java.awt.Color(255, 255, 255));
        JrDetallado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JrDetallado.setText("Detallado");

        JrCondensado.setBackground(new java.awt.Color(255, 255, 255));
        JrCondensado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JrCondensado.setText("Condensado");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JrCondensado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JrDetallado, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JrCondensado)
                .addGap(18, 18, 18)
                .addComponent(JrDetallado)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(66, 66, 66))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        dispose();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            Serverprod s = new Serverprod();
//            obtiene la conexion a la bd de avances
            c = s.getconexionserver8("Avances");
            daoAvances d = new daoAvances();
            String f1 = sdf.format(Fecha.getDate());
            String f2 = sdf.format(Fecha1.getDate());
//            Se hace seleccion al tipo de operacion
//            Esta opcion es para el reporte semanal
            if (JrSemana.isSelected()) {
//                Se obtienen los registros de acuerdo a la semana seleccionada
                ArrayList<Colsdepartamentos> arr = d.getcolsdepa(c, f1, f2);
                if (!arr.isEmpty()) {
//                    Insertar en bd
                    if (d.insertaregistrosAvances_sem(sqliteuser, arr)) {
//                        Despliegue de reporte y eliminacion de registros
                        setreport(f1, f2);
                        d.deleteregmes(sqliteuser, "Avances_semanal");
                    }
                }
//            Opcion para reporte de mes    
            } else if (JrMes.isSelected()) {
//                Proceso para obtener insertar, desplegar y eliminar registros de sqlite
                setmensual(f1, f2);
                setreport(f1, f2);
                d.deleteregmes(sqliteuser, "Avances_mensual");
//                Ultima opcion que es la del reporte de dia
            } else {
                ArrayList<Colsdepartamentos> arr = d.getcoldepartamentos(c);
                ArrayList<Davance> arra = new ArrayList<>();
                for (Colsdepartamentos arr1 : arr) {
                    arra.add(d.getregsDia(c, f2, arr1.getNmaq(), arr1.getNfecha(), arr1.getDepartamento()));
                }
                d.insertarregsDia(sqliteuser, arra);
                setreport(f1, f2);
                d.deleteregmes(sqliteuser, "Avances_Diario");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Avancesprod.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Avancesprod.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Avancesprod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MousePressed

    private void JrSemanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JrSemanaMousePressed
        settipo_nodia();
    }//GEN-LAST:event_JrSemanaMousePressed

    private void JrMesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JrMesMousePressed
        settipo_nodia();
    }//GEN-LAST:event_JrMesMousePressed

    private void JrDiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JrDiaMousePressed
        settipodia();
    }//GEN-LAST:event_JrDiaMousePressed

    private void settipodia() {
        JrCondensado.setEnabled(true);
        JrDetallado.setEnabled(true);
    }

    private void settipo_nodia() {
        JrCondensado.setEnabled(false);
        JrDetallado.setEnabled(false);
    }

    /**
     * funcion para poder desplegar en reporte
     *
     * @param f1
     * @param f2
     */
    private void setmensual(String f1, String f2) {
        daoAvances d = new daoAvances();
        ArrayList<Davance> arr = new ArrayList<>();
//        Se obtiene el los registros de cada uno de los departamentos para cada fecha
        ArrayList<Colsdepartamentos> arrcor = d.getarrmes(c, f1, f2, "fechacor", "cormaq", "corte", 1);
        ArrayList<Colsdepartamentos> arrprecor = d.getarrmes(c, f1, f2, "fechaprecor", "precormaq", "precorte", 1);
        ArrayList<Colsdepartamentos> arrpes = d.getarrmes(c, f1, f2, "fechapes", "pesmaq", "pespunte", 1);
        ArrayList<Colsdepartamentos> arrdes = d.getarrmes(c, f1, f2, "fechades", "desmaq", "deshebrado", 1);
        ArrayList<Colsdepartamentos> arroji = d.getarrmes(c, f1, f2, "fechaoji", "ojimaq", "ojillado", 1);
        ArrayList<Colsdepartamentos> arrins = d.getarrmes(c, f1, f2, "fechainsp", "inspmaq", "inspeccion", 1);
        ArrayList<Colsdepartamentos> arrprea = d.getarrmes(c, f1, f2, "fechaprea", "preamaq", "preacabado", 1);
        ArrayList<Colsdepartamentos> arrmont = d.getarrmes(c, f1, f2, "fechamont", "montmaq", "montado", 1);
        ArrayList<Colsdepartamentos> arrmont2 = d.getarrmes(c, f1, f2, "fechamont", "montmaq", "montado", 2);
        ArrayList<Colsdepartamentos> arrpt = d.getarrmes(c, f1, f2, "fechapt", "ptmaq", "prodt", 1);
//        Se utiliza el array de corte como base para el ciclo
        for (int i = 0; i < arrcor.size(); i++) {
            Davance av = new Davance();
//            Obtiene la fecha de acuerdo y siempre y cuando haya mas de 1 registro en el array
            String fecha = (arrcor.size() > 0) ? arrcor.get(i).getFecha() : "";
            String fprecor = getfechaarr(arrprecor, fecha);
            String fpes = getfechaarr(arrpes, fecha);
            String fdes = getfechaarr(arrdes, fecha);
            String foji = getfechaarr(arroji, fecha);
            String fins = getfechaarr(arrins, fecha);
            String fprea = getfechaarr(arrprea, fecha);
            String fmont = getfechaarr(arrmont, fecha);
            String fmont2 = getfechaarr(arrmont2, fecha);
            String fpt = getfechaarr(arrpt, fecha);
//            Se asigna el valor de los pares si la fecha concuenrda con la de corte y el array es mayor a 0
            av.setCor((arrcor.size() > 0) ? arrcor.get(i).getPares() : 0);
//            av.setPrecor((fecha.equals(fprecor) && arrprecor.size() > 0) ? arrprecor.get(i).getPares() : 0);
            av.setPrecor(getparesarr(arrprecor,fprecor));
            av.setPes(getparesarr(arrpes,fpes));
            av.setDes(getparesarr(arrdes,fdes));
            av.setOji(getparesarr(arroji,foji));
            av.setInsp(getparesarr(arrins,fins));
            av.setPrea(getparesarr(arrprea,fprea));
            av.setMont(getparesarr(arrmont,fmont));
            av.setMont2(getparesarr(arrmont,fmont2));
            av.setPt(getparesarr(arrpt,fpt));
            av.setFecha(fecha);
            arr.add(av);
        }
//        Se inserta en la bd de Sqlite para su posterior despliegue
        d.inserttarregsmes(sqliteuser, arr);
    }

    /**
     * Funcion que obtiene la fecha indicada del arreglo si no existe va vacio
     *
     * @param arr
     * @param fecha
     * @return
     */
    private String getfechaarr(ArrayList<Colsdepartamentos> arr, String fecha) {
        String f = "";
        if (!arr.isEmpty()) {
            for (Colsdepartamentos arr1 : arr) {
                if (arr1.getFecha().equals(fecha)) {
                    f = arr1.getFecha();
                    break;
                } else {
                    f = "";
                }
            }
        } else {
            f = "";
        }
        return f;
    }

    /**
     * Funcion parecida a la de la fecha solo que en esta verifica que no haya
     * desbordamiento
     *
     * @param arr
     * @param fecha
     * @return
     */
    private int getparesarr(ArrayList<Colsdepartamentos> arr, String fecha) {
        int f = 0;
        if (!arr.isEmpty()) {
            for (Colsdepartamentos arr1 : arr) {
                if (arr1.getFecha().equals(fecha)) {
                    f = arr1.getPares();
                    break;
                } else {
                    f = 0;
                }
            }
        } else {
            f = 0;
        }

        return f;
    }

    private void setreport(String f1, String f2) {
        String repname;
        Connection con;
        if (JrDia.isSelected()) {
//            repname = (JrCondensado.isSelected()) ? "avancespares" : "avancespares_det";
            repname = "Avances_Diario";
//            con = c;
            con = sqliteuser;
        } else {
            repname = (JrSemana.isSelected()) ? "Avancessemanal" : "Avances_Mes";
            con = sqliteuser;
        }
//        System.out.println(repname);
        try {
            Map parametros = new HashMap();
//            Agregar parametros al reporte
            parametros.put("f1", f1);
            parametros.put("f2", f2);
            JasperReport jasper = (JasperReport) JRLoader.loadObject(getClass().getResource("/ReportesAvances/" + repname + ".jasper"));
            JasperPrint print = JasperFillManager.fillReport(jasper, parametros, con);
            JasperViewer ver = new JasperViewer(print, false); //despliegue de reporte
            this.dispose();
            ver.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            ver.setTitle("Avances de produccion");
            ver.setVisible(true);
            c.close();
        } catch (JRException ex) {
            Logger.getLogger(fac1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Avancesprod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Formatear para que no tome en cuenta los espacios
     *
     * @param mat
     * @return
     */
    private String getmatformat(String mat) {
        String resp = "";
        for (int i = 0; i < mat.length(); i++) {
            String caracter = mat.charAt(i) + "";
            if (!caracter.equals(" ")) {
                resp += caracter;
            }
        }
        return resp;
    }

    private boolean verificafloat(String cad) {
        boolean resp = false;
        String patt = "[0-9]+||[0-9]+.[0-9]+";
        Pattern pat = Pattern.compile(patt);
        Matcher match = pat.matcher(cad);
        if (match.matches()) {
            resp = true;
        }
        return resp;
    }

    public void cerraravances() {
        try {
//            System.out.println("cerrar avances");
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(Avancesprod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Avancesprod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Avancesprod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Avancesprod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Avancesprod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Avancesprod dialog = new Avancesprod(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fecha;
    private com.toedter.calendar.JDateChooser Fecha1;
    private javax.swing.JRadioButton JrCondensado;
    private javax.swing.JRadioButton JrDetallado;
    private javax.swing.JRadioButton JrDia;
    private javax.swing.JRadioButton JrMes;
    private javax.swing.JRadioButton JrSemana;
    private javax.swing.ButtonGroup bgrupo2;
    private javax.swing.ButtonGroup grupop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
