/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package athprod;

import DAO.daoAvances;
import Modelo.metadep;
import Server.Serverprod;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GATEWAY1-
 */
public class Hrsavances extends javax.swing.JInternalFrame {

    Connection c;
    ArrayList<metadep> arr = new ArrayList<>();
    public int cantidaddehoras = 0;

    /**
     * Creates new form Respaldos
     */
    public Hrsavances() {
        try {
            initComponents();
            Serverprod s = new Serverprod();
//            c = s.getconexionTPU("Avances");
            c = s.getconexionserver8("Avances");
            setempresas();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Hrsavances.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Hrsavances.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Hrsavances.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPopupMenu();
        JmHr = new javax.swing.JMenuItem();
        JmDia = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtEmpresa = new javax.swing.JTable();

        JmHr.setText("Actualiza cantidad x hora");
        JmHr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmHrActionPerformed(evt);
            }
        });
        Menu.add(JmHr);

        JmDia.setText("Actualiza cant. x dia");
        JmDia.setEnabled(false);
        JmDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmDiaActionPerformed(evt);
            }
        });
        Menu.add(JmDia);

        setClosable(true);
        setIconifiable(true);
        setTitle("Configuracion de hrs para pantallas de avances");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/safety_reader_card_10784.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        JtEmpresa.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        JtEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JtEmpresa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JtEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtEmpresaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(JtEmpresa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1224, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cerrarcon() {
        try {
//            System.out.println("cerrar avances");
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(Hrsavances.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        cerrarcon();
    }//GEN-LAST:event_formInternalFrameClosing

    private void JtEmpresaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtEmpresaMousePressed
        if (evt.getButton() == 3) {
            Menu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_JtEmpresaMousePressed

    private void JmHrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmHrActionPerformed
        String hrs = JOptionPane.showInputDialog(null, "Ingresar nueva hr para el departamento");
        String nombre = arr.get(JtEmpresa.getSelectedRow()).getNombre();
        String meta = Integer.parseInt(hrs) * cantidaddehoras + "";
        if (updatecantidad(Integer.parseInt(hrs), meta, nombre)) {
            JOptionPane.showMessageDialog(null, "Exito al modificar");
            setempresas();
        }
    }//GEN-LAST:event_JmHrActionPerformed

    private void JmDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmDiaActionPerformed
//        String hrs = JOptionPane.showInputDialog(null, "Ingresar nueva cantidad x dia para el departamento");
//        String nombre = arr.get(JtEmpresa.getSelectedRow()).getNombre();
//        if (updatecantidad(Integer.parseInt(hrs), "cantxdia", nombre)) {
//            JOptionPane.showMessageDialog(null, "Exito al modificar");
//            setempresas();
//        }
    }//GEN-LAST:event_JmDiaActionPerformed

    private boolean updatecantidad(int cant, String col, String nombre) {
        daoAvances da = new daoAvances();
        return da.actualizahrs(c, cant, col, nombre);
    }

    private void setempresas() {
        DefaultTableModel model = new DefaultTableModel();
        daoAvances da = new daoAvances();
        arr = da.arrdepp(c);
        model.addColumn("Nombre");
        model.addColumn("Pares x hr");
        model.addColumn("Pares x Dia");
        model.setNumRows(arr.size());
        JtEmpresa.setModel(model);
        for (int i = 0; i < arr.size(); i++) {
            JtEmpresa.setValueAt(arr.get(i).getNombre(), i, 0);
            JtEmpresa.setValueAt(arr.get(i).getCantxhr(), i, 1);
            JtEmpresa.setValueAt(arr.get(i).getCantxdia(), i, 2);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JmDia;
    private javax.swing.JMenuItem JmHr;
    private javax.swing.JTable JtEmpresa;
    private javax.swing.JPopupMenu Menu;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
