/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package athprod;

import DAO.daoClientes;
import DAO.daocfdi;
import DAO.daofactura;
import Modelo.Cliente;
import Modelo.ConceptosES;
import Modelo.Conexiones;
import Modelo.Formadepago;
import Modelo.factura;
import Modelo.metodopago;
import Modelo.relacion;
import Modelo.usocfdi;
import Paneles.ncr1;
import Paneles.ncr2;
import Server.Serverprod;
import Server.Serverylite;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SingleSelectionModel;
import mx.sat.cfd40.generarXML40;
import mx.sat.cfd40.xmlDAO;

/**
 *
 * @author GATEWAY1-
 */
public class Notascr extends javax.swing.JInternalFrame {

    ncr1 c1;
    ncr2 c2;
    String var = "0";
    public String name, empresa;
    Connection rcpt, litecfdi, liteempresa, cobranza, cpt;
    ArrayList<usocfdi> arruso = new ArrayList<>();
    ArrayList<Formadepago> arrforma = new ArrayList<>();
    ArrayList<metodopago> arrmetodo = new ArrayList<>();
    ArrayList<relacion> arrrelacion = new ArrayList<>();

    /**
     * Creates new form Clientes
     *
     * @param cn
     */
    public Notascr(Conexiones cn) {
        initComponents();
        cpt = cn.getCpt();
        rcpt = cn.getRcpt();
        cobranza = cn.getCobranza();
        empresa=cn.getEmpresa();
        generaciontab();//Tabs de facturacion
        conexiones();
        setarraylist();
    }

    private void conexiones() {//Conexiones a servidor
        try {
            Serverylite l = new Serverylite();
            litecfdi = l.getconexioncfdi();
            liteempresa = l.getconexionC();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Notascr.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Notascr.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Notascr.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setarraylist() {
        daocfdi d = new daocfdi();
        arruso = d.getusocfdi(litecfdi);
        arrmetodo = d.getMetodopago(litecfdi);
        arrforma = d.getFormadepago(litecfdi);
        arrrelacion = d.getrelacion(litecfdi);

        c2.arrrelacion = arrrelacion;
        c2.arrfpago = arrforma;
        c2.arrmetodo = arrmetodo;
        c2.arruso = arruso;
        //tambien conexiones
        c2.ACobranza = cobranza;
//        c2.rcpt = rcpt;
        c2.sqlempresa = liteempresa;
        c2.sqlcfdi = litecfdi;
        c2.cpt = cpt;
        c2.empresa=empresa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Tabbed = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Notas de credito");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Tabbed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabbed, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabbed, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public final void generaciontab() {//generar tabs
        c1 = new ncr1();
        c2 = new ncr2();
        Tabbed.addTab("Listado de NCR", c1);
        Tabbed.setSelectedComponent(c1);
        Tabbed.addTab("Nueva NCR", c2);

    }

    private void generarfac() {// solo genera xml
        try {
            daoClientes dc = new daoClientes();
            daofactura df = new daofactura();
            factura f = df.getfac(rcpt, "47140");
            xmlDAO x = new xmlDAO();
            ArrayList<xmlDAO> arr = new ArrayList<>();
            Cliente c = dc.getCliente(cobranza, f.getIdcliente());// Busca
            String descmetodo = "";
            if (f.getDescuento() != 0) {                                    //setear descuento si es distinto de 0
                x.setDescuento(BigDecimal.valueOf(f.getDescuento()));
            }

            for (int i = 0; i < arrmetodo.size(); i++) {//asignar descripcion del metodo de pago
                if (f.getMetodopago().equals(arrmetodo.get(i).getMetodopago())) {
                    descmetodo = arrmetodo.get(i).getDescripcion();
                    break;
                }
            }
            x.setFolio(f.getFolio() + "");                              // Folio
            x.setSerie(f.getSerie());                                   // Serie
            x.setFormaP(f.getFormapago());                              // forma de pago
            x.setDescripcionP(descmetodo);      // metodo descripcion
//            x.setDescuento(BigDecimal.valueOf(0));
            x.setSubT(BigDecimal.valueOf(f.getSubtotal()));             // Subtotal
            x.setMoneda(f.getMoneda());                                 // Moneda
            x.setTotal(BigDecimal.valueOf(f.getTotal()));               // Total
            x.setMetodoPago(f.getMetodopago());                         // MEtodo pago
//            x.setLugarExpedidcion("36400");                             // CP emisor
//Cliente
            x.setReceptor(c.getNombre());                               // Razon social re
//            x.setReceptor("COPPEL");
            x.setRfcR(c.getRfc());                                      // RFC re
            x.setUsoCfdi(f.getUsocfdi());                               // Uso cfdi re
            x.setRegimenFR("612");                                      // regimen re
            x.setDomicilioReceptor(c.getCp());                          // cp re
//Fin Cliente            
// # de Concepto
            for (int i = 0; i < f.getArr().size(); i++) {                       //      numero de renglones
                xmlDAO y = new xmlDAO();
                //Obtener datos de arreglo
                float importe = f.getArr().get(i).getImporta();
                float base = f.getArr().get(i).getBase();
                float unitario = f.getArr().get(i).getPrecio();
                int cantidad = f.getArr().get(i).getCantidad();
                float descuento = f.getArr().get(i).getDescuento();
                String desc = f.getArr().get(i).getDescripcion();
                String clvprov = f.getArr().get(i).getCodigo();
                String unidad = f.getArr().get(i).getUmedida();
                int id = f.getId();
                //
                if (descuento != 0) {// si el descuento es distinto de cero
                    y.setDescuento(BigDecimal.valueOf(descuento));              //Descuento c
                }
                y.setImporte(BigDecimal.valueOf(base));                         //importe c
                y.setValorUnitario(BigDecimal.valueOf(unitario));               //unitario c
                y.setCantidad(BigDecimal.valueOf(cantidad));                    // cantidad c
                y.setDescripcion(desc);                                         // desc prod
                y.setClaveProdServ(clvprov);                                    // clv sat
                y.setClaveUn(unidad);                                           // unidad
                y.setUnidad("PARES");
                y.setBase(BigDecimal.valueOf(base));                            // importe c
                y.setImporteImpuesto(BigDecimal.valueOf(importe));              // iva
                BigDecimal d = new BigDecimal("0.160000");//tomando en cuenta los 6 decimales
                y.setTasaCuota(d);
                y.setNoIdenf(id + "");
                arr.add(y);
            }
// - Fin numero ded concepto

            x.setTotalImpuesto(BigDecimal.valueOf(f.getImpuestos()));           //IMPUESTO TRASLADADO
            x.setBaseImpuesto(BigDecimal.valueOf(f.getSubtotal()));             //BASE TRASLADO
            x.setImpuesto("002");
            BigDecimal d = new BigDecimal("0.160000");//tomando en cuenta los 6 decimales
            x.setTasaCuota(d);
            generarXML40 xml = new generarXML40();
            xml.crearComprobante(x, arr, cpt, liteempresa);
        } catch (Exception ex) {
            Logger.getLogger(Notascr.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabbed;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
