/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package athprod;

import DAO.daoPrincipal;
import Modelo.Conexiones;
import Modelo.Procserie;
import Modelo.Usuarios;
import Paneles.pago1;
import Tpu.Materialestpu;
import Server.ServerProccpt;
import Server.Serverprod;
import Server.Serverylite;
import Tpu.ClientesTpu;
import Tpu.FacturacionTpu;
import Tpu.Pedimento;
import Tpu.Remisiontpu;
import java.awt.AWTException;
import java.awt.Image;
import java.awt.MenuItem;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import mx.sat.cfd40.timbrarXML;

/**
 *
 * @author GATEWAY1-
 */
public final class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    ArrayList<Connection> arr = new ArrayList<>();
    private TrayIcon Ticon;
    private SystemTray ttray;
    MenuItem mi = new MenuItem();
    MenuItem mi2 = new MenuItem();
    MenuItem mi3 = new MenuItem();
    Connection cpt, rcpt, ACobranza;
    Connection concpt, conupcpt, conrcpt, conrcptup, concob, concobup;
    Connection liteusuario;
    Connection litecfdi, liteempresa;
    Conexiones conexion = new Conexiones();
    JPasswordField jp = new JPasswordField();
    String empresa;
    int cont = 0;
    String admin = "0";
    String prod = "1";
    Usuarios u = new Usuarios();

    public Principal() {
        initComponents();
//        JrEmpresa.setSelected(true);
        this.setLocationRelativeTo(null);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/programacion.png"));
        setIconImage(icon);
//        Allsingleton singleton = new Allsingleton();
//        Jlnombre.setText(Allsingleton.getUsuario().getNombre());
//        JlSerie.setText(Allsingleton.getSerie());
        PopMenu.add(JmSesion);
        PopMenu.add(JmOut);
        PopMenu.add(JmConf);
        PopMenu.add(jSeparator1);
        PopMenu.add(JmProd);
        PopMenu.add(JmCobranza);
//        PopMenu.add(JmRespaldos);
        PopMenu.add(JmVentas);
        PopMenu.add(JmTpu);
        popup();
        setinicio();
        grupo.add(JrEmpresa);
        grupo.add(JrEmpresa1);
//        setconexionesglobal();// Cuidado!!! Bases de datos de produccion

        conexiones();
        setconexionprueba();
//        actualizaempresa();
        //setconexiones();
        u.setAth("");
        u.setUsuario("");
        if (prod.equals("0")) {

            JlUsuario.setText("Michel Admin");
            u.setUsuario("Michel");
            u.setGrado("2");
            u.setTurno("0");
            modoadmin();

            JmSesion.setEnabled(false);
            jLabel1.requestFocus();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JmSesion = new javax.swing.JMenuItem();
        JmOut = new javax.swing.JMenuItem();
        JmConf = new javax.swing.JMenu();
        JmRespaldos = new javax.swing.JMenuItem();
        JmCES = new javax.swing.JMenuItem();
        JmEmpresas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        JmProd = new javax.swing.JMenu();
        JmCatalogoprod = new javax.swing.JMenuItem();
        JmFicha = new javax.swing.JMenuItem();
        JmAvances = new javax.swing.JMenu();
        JmReportes = new javax.swing.JMenu();
        JmAvancesPt = new javax.swing.JMenuItem();
        PopMenu = new javax.swing.JPopupMenu();
        JmCobranza = new javax.swing.JMenu();
        JmClientes = new javax.swing.JMenuItem();
        JmNotascr = new javax.swing.JMenuItem();
        JmPagos = new javax.swing.JMenuItem();
        JmVentas = new javax.swing.JMenu();
        JmVerfacts = new javax.swing.JMenuItem();
        JmModcaja = new javax.swing.JMenuItem();
        JmSalidas = new javax.swing.JMenuItem();
        JmFacturacion = new javax.swing.JMenuItem();
        JmFacturacionE = new javax.swing.JMenuItem();
        JmCerrar = new javax.swing.JMenuItem();
        Jmabrir = new javax.swing.JMenuItem();
        JpClose = new java.awt.PopupMenu();
        grupo = new javax.swing.ButtonGroup();
        JmTpu = new javax.swing.JMenu();
        Catalogos = new javax.swing.JMenu();
        JmMaterial = new javax.swing.JMenuItem();
        JmProveedor = new javax.swing.JMenuItem();
        JmCliente = new javax.swing.JMenuItem();
        Jmreportes = new javax.swing.JMenu();
        JtFacturaciontpu = new javax.swing.JMenuItem();
        JmRemision = new javax.swing.JMenuItem();
        JmPedimento = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        JlSerie = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        JrEmpresa = new javax.swing.JRadioButton();
        JrEmpresa1 = new javax.swing.JRadioButton();
        JlUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JdPanel = new javax.swing.JDesktopPane();

        JmSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/key_keys_10804.png"))); // NOI18N
        JmSesion.setText("Iniciar sesion");
        JmSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmSesionActionPerformed(evt);
            }
        });

        JmOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/exit_closethesession_close_6317.png"))); // NOI18N
        JmOut.setText("Cerrar sesion");
        JmOut.setToolTipText("Cierra el programa");
        JmOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmOutActionPerformed(evt);
            }
        });

        JmConf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/1486564402-settings_81520.png"))); // NOI18N
        JmConf.setText("Configuraciones");

        JmRespaldos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Data_settings_theapplication_3364.png"))); // NOI18N
        JmRespaldos.setText("Respaldos BD");
        JmRespaldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmRespaldosActionPerformed(evt);
            }
        });
        JmConf.add(JmRespaldos);

        JmCES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/construction_project_plan_building_architect_design_develop-61_icon-icons.com_60253.png"))); // NOI18N
        JmCES.setText("CES");
        JmCES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmCESActionPerformed(evt);
            }
        });
        JmConf.add(JmCES);

        JmEmpresas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/1492616984-13-setting-configure-repair-support-optimization-google_83419.png"))); // NOI18N
        JmEmpresas.setText("Empresas");
        JmEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmEmpresasActionPerformed(evt);
            }
        });
        JmConf.add(JmEmpresas);

        JmProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/42498factory_99134.png"))); // NOI18N
        JmProd.setText("Produccion");

        JmCatalogoprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Documents_43884.png"))); // NOI18N
        JmCatalogoprod.setText("Catalogos");
        JmCatalogoprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmCatalogoprodActionPerformed(evt);
            }
        });
        JmProd.add(JmCatalogoprod);

        JmFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/1562683-branding-card-pencil-profile_107062.png"))); // NOI18N
        JmFicha.setText("Ficha Tecnica");
        JmFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmFichaActionPerformed(evt);
            }
        });
        JmProd.add(JmFicha);

        JmAvances.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/organizer_calendar_pen_note_6134.png"))); // NOI18N
        JmAvances.setText("Avances");

        JmReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/file_pdf_download_icon-icons.com_68954.png"))); // NOI18N
        JmReportes.setText("Reportes");

        JmAvancesPt.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        JmAvancesPt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ForkliftTruck_Loaded_Black_icon-icons.com_54893.png"))); // NOI18N
        JmAvancesPt.setText("Reporte avances pt");
        JmAvancesPt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmAvancesPtActionPerformed(evt);
            }
        });
        JmReportes.add(JmAvancesPt);

        JmAvances.add(JmReportes);

        JmProd.add(JmAvances);

        JmCobranza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/exchange-dollar_icon-icons.com_53141.png"))); // NOI18N
        JmCobranza.setText("Cobranza");

        JmClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/User_Group-80_icon-icons.com_57247.png"))); // NOI18N
        JmClientes.setText("Clientes");
        JmClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmClientesActionPerformed(evt);
            }
        });
        JmCobranza.add(JmClientes);

        JmNotascr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/1486564168-finance-bank-check_81495.png"))); // NOI18N
        JmNotascr.setText("Notas de credito");
        JmNotascr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmNotascrActionPerformed(evt);
            }
        });
        JmCobranza.add(JmNotascr);

        JmPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/business_table_order_report_history_2332.png"))); // NOI18N
        JmPagos.setText("Pagos");
        JmPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmPagosActionPerformed(evt);
            }
        });
        JmCobranza.add(JmPagos);

        JmVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Ordering_25406.png"))); // NOI18N
        JmVentas.setText("Ventas");

        JmVerfacts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/applicationvnd_103607.png"))); // NOI18N
        JmVerfacts.setText("Generar pdf fac");
        JmVerfacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmVerfactsActionPerformed(evt);
            }
        });
        JmVentas.add(JmVerfacts);

        JmModcaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Documents_43884.png"))); // NOI18N
        JmModcaja.setText("Modificacion de facturas");
        JmModcaja.setToolTipText("Modifica algunos valores de las facturas, solo las autorizadas");
        JmModcaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmModcajaActionPerformed(evt);
            }
        });
        JmVentas.add(JmModcaja);

        JmSalidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/move_23058.png"))); // NOI18N
        JmSalidas.setText("Salidas");
        JmSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmSalidasActionPerformed(evt);
            }
        });
        JmVentas.add(JmSalidas);

        JmFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/surtir.png"))); // NOI18N
        JmFacturacion.setText("Facturación");
        JmFacturacion.setToolTipText("Facturacion");
        JmFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmFacturacionActionPerformed(evt);
            }
        });
        JmVentas.add(JmFacturacion);

        JmFacturacionE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/surtirE.png"))); // NOI18N
        JmFacturacionE.setText("Facturación  Especial");
        JmFacturacionE.setToolTipText("Facturacion  Especial");
        JmFacturacionE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmFacturacionEActionPerformed(evt);
            }
        });
        JmVentas.add(JmFacturacionE);

        JmCerrar.setText("jMenuItem3");

        Jmabrir.setText("jMenuItem2");

        JpClose.setLabel("popupMenu1");

        JmTpu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/factory_robot_manufacturing_industry_robotics_machine_robotic_arm_automation_industrial_production_icon_231898.png"))); // NOI18N
        JmTpu.setText("Tpu");

        Catalogos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/courses_letters_blackboard_board_staff_book_1475.png"))); // NOI18N
        Catalogos.setText("Catalogos");

        JmMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/material_colors_macos_bigsur_icon_189995.png"))); // NOI18N
        JmMaterial.setText("Materiales");
        JmMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmMaterialActionPerformed(evt);
            }
        });
        Catalogos.add(JmMaterial);

        JmProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/prensauser.png"))); // NOI18N
        JmProveedor.setText("Proveedores");
        Catalogos.add(JmProveedor);

        JmCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/User_Group-80_icon-icons.com_57247.png"))); // NOI18N
        JmCliente.setText("Clientes");
        JmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmClienteActionPerformed(evt);
            }
        });
        Catalogos.add(JmCliente);

        JmTpu.add(Catalogos);

        Jmreportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/books_21813.png"))); // NOI18N
        Jmreportes.setText("Reportes");
        JmTpu.add(Jmreportes);

        JtFacturaciontpu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/surtir.png"))); // NOI18N
        JtFacturaciontpu.setText("Facturacion");
        JtFacturaciontpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtFacturaciontpuActionPerformed(evt);
            }
        });
        JmTpu.add(JtFacturaciontpu);

        JmRemision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/surtirR.png"))); // NOI18N
        JmRemision.setText("Pedidos");
        JmRemision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmRemisionActionPerformed(evt);
            }
        });
        JmTpu.add(JmRemision);

        JmPedimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/construction_project_plan_building_architect_design_develop-61_icon-icons.com_60253.png"))); // NOI18N
        JmPedimento.setText("Pedimento");
        JmPedimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmPedimentoActionPerformed(evt);
            }
        });
        JmTpu.add(JmPedimento);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produccion ATH ");
        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(java.awt.Color.white);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(82, 82, 229));
        jPanel1.setForeground(new java.awt.Color(120, 152, 237));

        JlSerie.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JlSerie.setForeground(new java.awt.Color(255, 0, 51));
        JlSerie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JlSerieMousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        JrEmpresa.setBackground(new java.awt.Color(82, 82, 229));
        JrEmpresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JrEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        JrEmpresa.setText("Athletic");
        JrEmpresa.setToolTipText("Emisor a facturar");
        JrEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JrEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrEmpresaActionPerformed(evt);
            }
        });

        JrEmpresa1.setBackground(new java.awt.Color(82, 82, 229));
        JrEmpresa1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JrEmpresa1.setForeground(new java.awt.Color(255, 255, 255));
        JrEmpresa1.setText("Uptown");
        JrEmpresa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JrEmpresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrEmpresa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(JrEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JrEmpresa1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(JrEmpresa)
                .addComponent(JrEmpresa1))
        );

        JlUsuario.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        JlUsuario.setForeground(new java.awt.Color(255, 255, 255));
        JlUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        JlUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JlUsuarioMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/seleccionblanco.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(JlSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JlSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        JdPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        JdPanel.setForeground(new java.awt.Color(255, 255, 255));
        JdPanel.setAutoscrolls(true);
        JdPanel.setBackground(new java.awt.Color(255, 255, 255));
        JdPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JdPanelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout JdPanelLayout = new javax.swing.GroupLayout(JdPanel);
        JdPanel.setLayout(JdPanelLayout);
        JdPanelLayout.setHorizontalGroup(
            JdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 942, Short.MAX_VALUE)
        );
        JdPanelLayout.setVerticalGroup(
            JdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JdPanel)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JdPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JlSerieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlSerieMousePressed
        cerrartodo();
    }//GEN-LAST:event_JlSerieMousePressed
    private void conexiones() {//Conexiones a lite
        try {
            Serverylite l = new Serverylite();
            litecfdi = l.getconexioncfdi();
            liteempresa = l.getconexionC();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Facturacion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Facturacion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Facturacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setinicio() {
        JmVentas.setVisible(false);
        JmCobranza.setVisible(false);
        JmCES.setVisible(false);
        JmRespaldos.setVisible(false);
        JmEmpresas.setVisible(false);
        JmConf.setVisible(false);
        JmProd.setVisible(false);
        JmOut.setVisible(false);
        JmTpu.setVisible(false);
    }

    private void iniciartray() {
        if (SystemTray.isSupported()) {
            try {
                ttray.add(Ticon);
                this.setVisible(false);
            } catch (AWTException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void popup() {
        mi.setLabel("Abrir");
        mi2.setLabel("Cerrar");
        mi3.setLabel("Activar Administracion");
        //Imagen para el icono en la barra
        ImageIcon image = new ImageIcon(this.getClass().getResource("/Recursos/programacion.png"));
        JpClose.add(mi3);
        JpClose.add(mi);//Añadir al pop cada menu una ves iconificado en la barra
        JpClose.add(mi2);
        Ticon = new TrayIcon(image.getImage(), "Ath Produccion", JpClose);//Asignando recursos a icono y control de la barra
        Ticon.setImageAutoSize(true);
        ttray = SystemTray.getSystemTray();
        mi.addActionListener(new ActionListener() {//control de maximizar ventana
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(true);
                ttray.remove(Ticon);
            }
        });
        mi2.addActionListener(new ActionListener() {//Cerrar 
            @Override
            public void actionPerformed(ActionEvent e) {
                cerrartodo();
            }
        });
        mi3.addActionListener(new ActionListener() {//Activar administracion 
            @Override
            public void actionPerformed(ActionEvent e) {
                String a = JOptionPane.showInputDialog("Introduce contraseña");
                admin = (a.equals("0505")) ? "1" : "0";
                if (admin.equals("1")) {
                    setconexiones();
                    JmRespaldos.setVisible(true);
                    JmCES.setVisible(true);
                    JmEmpresas.setVisible(true);
                    JmConf.setVisible(true);
                    JmVentas.setVisible(true);
                    JmCobranza.setVisible(true);
                } else {

                }
            }
        });

    }
//Obtener todas las conecciones para realizar operaciones extras(kardex, pedidos, facturas)

    private void setconexiones() {
        try {
            JOptionPane.showMessageDialog(null, "Activado!");
            ServerProccpt proccpts = new ServerProccpt();//Clase que solo se usara para estos procesos
            arr.add(proccpts.getconexioncpt());
            arr.add(proccpts.getconexionrcpt());
            arr.add(proccpts.getconexionCptup());
            arr.add(proccpts.getconexionRcptup());
            Procserie p = new Procserie();
            p.setConnecxiones(arr);// asignar valores de coneccion a la clase
            p.start();//iniciar hilo

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cerrarconexiones() {//Cerrar todas las conexiones de base de datos
        try {
            if (admin.equals("1")) {
                arr.get(0).close();
                arr.get(1).close();
                arr.get(2).close();
                arr.get(3).close();
                System.out.println("Cerrando conexiones");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        iniciartray();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    }//GEN-LAST:event_formWindowClosing

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        PopMenu.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_jLabel1MousePressed

    private void JmCatalogoprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmCatalogoprodActionPerformed

    }//GEN-LAST:event_JmCatalogoprodActionPerformed

    private void JmFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmFichaActionPerformed
        try {
            Fichatecnica f = new Fichatecnica();
            this.JdPanel.add(f);
            f.setMaximum(true);
            f.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JmFichaActionPerformed

    private void JmCESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmCESActionPerformed
        try {//Abre la aplicacion de entradas y salidas
            String path = "C:\\Users\\GATEWAY1-\\Documents\\NetBeansProjects\\factura2.0\\dist\\";
            Process process = Runtime.getRuntime().exec("java -jar " + path + "factura2.0.jar");
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JmCESActionPerformed

    private void JmRespaldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmRespaldosActionPerformed
        try {//Abrir app de respaldos
            Respaldos f = new Respaldos();
            this.JdPanel.add(f);
//            f.setMaximum(true);
            f.show();
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JmRespaldosActionPerformed

    private void JmClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmClientesActionPerformed
        try {
            Clientes c = new Clientes();
            this.JdPanel.add(c);
            c.JtBuscar.requestFocus();
            c.setMaximum(true);
            c.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JmClientesActionPerformed

    private void JmVerfactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmVerfactsActionPerformed
        try {//Abre la aplicacion de entradas y salidas
            String path = "C:\\af\\bin\\";
            Process process = Runtime.getRuntime().exec("java -jar " + path + "Facturas.jar");
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JmVerfactsActionPerformed

    private void JmModcajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmModcajaActionPerformed
        try {
            Modcaja c = new Modcaja();
            this.JdPanel.add(c);
            c.setMaximum(true);
            c.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JmModcajaActionPerformed

    private void JmSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmSalidasActionPerformed
        try {
            Salidas c = new Salidas();
            this.JdPanel.add(c);
            c.setMaximum(true);
            c.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JmSalidasActionPerformed

    private void JmFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmFacturacionActionPerformed
        try {
            conexion.setLiteusuario(liteusuario);
            Facturacion c = new Facturacion(conexion, u);
//            c.liteusuario = liteusuario;
            this.JdPanel.add(c);
//            c.JtBuscar.requestFocus();
            c.setMaximum(true);
            c.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JmFacturacionActionPerformed

    private void JmEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmEmpresasActionPerformed
        try {//Abrir app de respaldos
            Empresarfc f = new Empresarfc();
            this.JdPanel.add(f);
//            f.setMaximum(true);
            f.show();
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JmEmpresasActionPerformed

    private void JmNotascrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmNotascrActionPerformed
        try {
            Notascr c = new Notascr(conexion, u);
            this.JdPanel.add(c);
//            c.JtBuscar.requestFocus();
            c.setMaximum(true);
            c.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JmNotascrActionPerformed

    private void JmPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmPagosActionPerformed
        try {
            Pagos c = new Pagos(conexion);
            this.JdPanel.add(c);
//            c.JtBuscar.requestFocus();
            c.setMaximum(true);
            c.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JmPagosActionPerformed

    private void JrEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrEmpresaActionPerformed
        actualizaempresa();
    }//GEN-LAST:event_JrEmpresaActionPerformed

    private void JrEmpresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrEmpresa1ActionPerformed
        actualizaempresa();
    }//GEN-LAST:event_JrEmpresa1ActionPerformed

    private void JmSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmSesionActionPerformed
        if (JrEmpresa.isSelected() || JrEmpresa1.isSelected() || prod.equals("0")) {
            verificausuariolite();
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona la empresa a usar!");
            JrEmpresa.requestFocus();
        }
    }//GEN-LAST:event_JmSesionActionPerformed

    private void JlUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlUsuarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JlUsuarioMousePressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped

    }//GEN-LAST:event_formKeyTyped

    private void JdPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JdPanelKeyPressed

    }//GEN-LAST:event_JdPanelKeyPressed

    private void JmOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmOutActionPerformed
        cerrartodo();
    }//GEN-LAST:event_JmOutActionPerformed

    private void JmFacturacionEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmFacturacionEActionPerformed
        try {
            FacturacionE c = new FacturacionE(conexion, u);
            this.JdPanel.add(c);
//            c.JtBuscar.requestFocus();
            c.setMaximum(true);
            c.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JmFacturacionEActionPerformed

    private void JmAvancesPtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmAvancesPtActionPerformed
        try {
            Serverprod s = new Serverprod();
            Connection av = s.getconexionserver8("Avances");
            Reporteavancept c = new Reporteavancept(null, true);
            c.av = av;
            c.liteav = liteusuario;
            c.empresacob = conexion.getEmpresacob();
            c.empresarcpt = conexion.getEmpresarcpt();
            c.setVisible(true);
            av.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_JmAvancesPtActionPerformed

    private void JmMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmMaterialActionPerformed
        try {

            Materialestpu c = new Materialestpu(conexion, u);
//            c.liteusuario = liteusuario;
            this.JdPanel.add(c);
//            c.JtBuscar.requestFocus();
            c.setMaximum(true);
            c.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JmMaterialActionPerformed

    private void JmPedimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmPedimentoActionPerformed
        try {
            Pedimento p = new Pedimento(conexion, u);
            this.JdPanel.add(p);
            p.setMaximum(true);
            p.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JmPedimentoActionPerformed

    private void JmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmClienteActionPerformed
        try {
            ClientesTpu p = new ClientesTpu(conexion, u);
            this.JdPanel.add(p);
            p.setMaximum(true);
            p.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JmClienteActionPerformed

    private void JtFacturaciontpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtFacturaciontpuActionPerformed
        try {
            FacturacionTpu p = new FacturacionTpu(conexion, u);
            this.JdPanel.add(p);
            p.setMaximum(true);
            p.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JtFacturaciontpuActionPerformed

    private void JmRemisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmRemisionActionPerformed
        try {
            Remisiontpu p = new Remisiontpu(conexion, u);
            this.JdPanel.add(p);
            p.setMaximum(true);
            p.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JmRemisionActionPerformed

    private void verificausuario() {
        jp.setVisible(true);
        jp.requestFocus();
        jp.isFocusable();
        JOptionPane.showMessageDialog(null, jp);
        String a = jp.getText();
        if (a.equals("")) {
            JOptionPane.showMessageDialog(null, "El campo no debe ir vacio");
            jp.requestFocus();
        } else {
            System.out.println(a);
            u = new Usuarios();
            if (a.equals("0605")) {
                JlUsuario.setText("Michel Admin");
                u.setUsuario("Michel");
                u.setGrado("2");
                modoadmin();
                JmSesion.setEnabled(false);
                jLabel1.requestFocus();
            } else {
                String res = "";
                daoPrincipal dp = new daoPrincipal();
                u = dp.getUsers(conexion.getRcpt(), "", a, "ñ");
                if (u.getGrado().equals("2")) {
                    JlUsuario.setText(u.getUsuario() + " Admin");
                    modoadmin();
                    JmSesion.setEnabled(false);
                    JmOut.setVisible(true);
                    res = "a";
                }
                if (!u.getUsuario().equals("") && !u.getGrado().equals("2")) {
                    JmVentas.setVisible(true);
                    JlUsuario.setText(u.getUsuario() + " Cpt facs");
                    res = "a";
                }
                if (res.equals("")) {
                    u = dp.getUsers(conexion.getCobranza(), "", a, "n");
                    if (!u.getUsuario().equals("")) {
                        JmCobranza.setVisible(true);
                        JlUsuario.setText(u.getUsuario() + " Cobranza");
                    }
                }
                JmOut.setVisible(true);
                JmSesion.setEnabled(false);
                jLabel1.requestFocus();
                timbrarXML t = new timbrarXML();
                if (!t.getprod()) {
                    JOptionPane.showMessageDialog(null, "Cuidado!, no estas en modo produccion");
                }
            }
        }

    }

    private void verificausuariolite() {
        jp.setVisible(true);
        jp.requestFocus();
        jp.isFocusable();
        JOptionPane.showMessageDialog(null, jp);
        String a = jp.getText();
        if (a.equals("")) {
            JOptionPane.showMessageDialog(null, "El campo no debe ir vacio");
            jp.requestFocus();
        } else {
            try {
                Serverylite s = new Serverylite();
                liteusuario = s.getconexionusuarios();
                if (a.equals("0605")) {
                    u.setAth("1");
                    JlUsuario.setText("Michel Admin");
                    u.setUsuario("");
                    u.setGrado("2");
                    u.setTurno("0");
                    u.setTipo_usuario("1");
                    modoadmin();
                    JmSesion.setEnabled(false);
                    jLabel1.requestFocus();
//                    actualizaempresa();
                    actualizaadmin();
                    setTpucon();
                } else {
                    daoPrincipal dp = new daoPrincipal();
                    u = dp.getUserlite(liteusuario, a, a);
                    if (!u.getUsuario().equals("")) {
//                        checkempresa();
                        actualizaempresa();
                        if (u.getTipo_usuario().equals("1")) {
                            setTpucon();
                        }
                    }

                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private boolean checkempresa() {
        boolean band = true;
        if (!u.getAth().equals("")) {
            if (JrEmpresa.isSelected()) {
                if (!u.getAth().equals("1")) {
                    band = false;
                }
            }
            if (JrEmpresa1.isSelected()) {
                if (!u.getUptown().equals("1")) {
                    band = false;
                }
            }
            if (band) {
                if (u.getVentas().equals("1")) {
                    JmVentas.setVisible(true);
                }
                if (u.getCobranza().equals("1")) {
                    JmCobranza.setVisible(true);
                }
                if (u.getTipo_usuario().equals("1")) {
//                    JmConf.setVisible(true);
                    modoadmin();
                }

                if (u.getProduccion().equals("1")) {
                    JmProd.setVisible(true);
                }
                if (u.getAvances().equals("1")) {
                    JmAvances.setVisible(true);
                    JmFicha.setVisible(false);
                }
                if (u.getTurno().equals("5")) {
                    JmFacturacion.setVisible(true);
                    JmVerfacts.setVisible(false);
                    JmModcaja.setVisible(false);
                    JmSalidas.setVisible(false);
                    JmTpu.setVisible(true);
                    JmTpu.setEnabled(false);
                }
                JmOut.setVisible(true);
                JmSesion.setEnabled(false);
                JlUsuario.setText(u.getNombre() + " " + u.getUsuario());
            } else {
                JOptionPane.showMessageDialog(null, "No puedes usar esta empresa, intentalo de nuevo");
                jp.setText("");
            }
        }

        return band;
    }

    private void modoadmin() {
        JmRespaldos.setVisible(true);
        JmCES.setVisible(true);
        JmEmpresas.setVisible(true);
        JmConf.setVisible(true);
        JmVentas.setVisible(true);
        JmCobranza.setVisible(true);
        JmProd.setVisible(true);
        JmOut.setVisible(true);
        JmTpu.setVisible(true);
    }

    private void actualizaempresa() {
        boolean band = checkempresa();
        if (!u.getUsuario().equals("")) {
            if (u.getTurno().equals("5")) {
                setTpucon();
                setconexionesglobal();//provicional
                conexion.setLitecfdi(litecfdi);
                conexion.setEmpresa(empresa);
                conexion.setCpt(concpt);
                conexion.setRcpt(conrcpt);
                conexion.setCobranza(concob);
                conexion.setEmpresa("CPT");
                conexion.setEmpresacob("ACobranza");
                conexion.setEmpresarcpt("RCPT");
            } else {
                setconexionesglobal();
                conexion.setLiteusuario(liteusuario);
                if (band) {
                    if (JrEmpresa.isSelected()) {
                        conexion.setCpt(concpt);
                        conexion.setRcpt(conrcpt);
                        conexion.setCobranza(concob);
                        conexion.setEmpresa("CPT");
                        conexion.setEmpresacob("ACobranza");
                        conexion.setEmpresarcpt("RCPT");
                    } else {
                        conexion.setCpt(conupcpt);
                        conexion.setRcpt(conrcptup);
                        conexion.setCobranza(concobup);
                        conexion.setEmpresa("UptownCPT");
                        conexion.setEmpresacob("ACobranzauptown");
                        conexion.setEmpresarcpt("UptownRCPT");
                    }
                    System.out.println(conexion.getEmpresa());
                }
            }
        }

        //conexiones de prueba
//        setconexiones("FATIMACPT","FATIMARCPT","ACobranzaFH");
    }

    public void actualizaadmin() {
        setconexionesglobal();
        if (JrEmpresa.isSelected()) {
            conexion.setCpt(concpt);
            conexion.setRcpt(conrcpt);
            conexion.setCobranza(concob);
            conexion.setEmpresa("CPT");
            conexion.setEmpresacob("ACobranza");
            conexion.setEmpresarcpt("RCPT");
        } else {
            conexion.setCpt(conupcpt);
            conexion.setRcpt(conrcptup);
            conexion.setCobranza(concobup);
            conexion.setEmpresa("UptownCPT");
            conexion.setEmpresacob("ACobranzauptown");
            conexion.setEmpresarcpt("UptownRCPT");
        }
    }

    private void setconexionesglobal() {
        if (prod.equals("1")) {
            Serverprod s = new Serverprod();
            try {//    Connection concpt, conupcpt, conrcpt, conrcptup, concob, concobup;
//            Asignar a una variable cada conexion
                concpt = s.getconexionserver8("CPT");
                conrcpt = s.getconexionserver8("RCPT");
                concob = s.getconexionserver8("ACobranza");
                conupcpt = s.getconexionserver8("UptownCPT");
                conrcptup = s.getconexionserver8("UptownRCPT");
                concobup = s.getconexionserver8("ACobranzaUptown");
            } catch (ClassNotFoundException | IOException | SQLException ex) {
                Logger.getLogger(pago1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    private void setTpucon() {
        try {
            Serverprod s = new Serverprod();
            conexion.setCpttpu(s.getconexionserver8("Tpucpt"));
            conexion.setCobranzatpu(s.getconexionserver8("ACobranzatpu"));
//            conexion.setRcpttpu(s.getconexionserver8("Tpurcpt"));
        } catch (ClassNotFoundException | IOException | SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setconexionprueba() {

        if (prod.equals("0")) {
            Serverprod s = new Serverprod();
            Serverylite s1 = new Serverylite();
            try {//    Connection concpt, conupcpt, conrcpt, conrcptup, concob, concobup;
//            Asignar a una variable cada conexion
                conexion.setCpt(s.getconexionpruebacpt());
                conexion.setRcpt(s.getconexionpruebarcpt());
                conexion.setCobranza(s.getconexionpruebacob());
                conexion.setEmpresa("FATIMACPT");
                conexion.setEmpresacob("ACobranzaFH");
                conexion.setEmpresarcpt("FATIMARCPT");
                conexion.setCpttpu(s.getconexionserver8("Tpucpt"));
                conexion.setCobranzatpu(s.getconexionserver8("ACobranzatpu"));
//                conexion.setRcpttpu(s.getconexionserver8("Tpurcpt"));
                liteusuario = s1.getconexionusuarios();
                conexion.setLiteusuario(liteusuario);
                conexion.setLitecfdi(litecfdi);
                conexion.setLiteempresa(liteempresa);

            } catch (ClassNotFoundException | IOException | SQLException ex) {
                Logger.getLogger(pago1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    private void cerrartodo() {
        if (admin.equals("1")) {
            cerrarconexiones();
        }
        cerrarbd();
        System.exit(0);
    }

    public void cerrarbd() {
        try {
//            Allsingleton.getC().close();
            //JOptionPane.showMessageDialog(null, Allsingleton.getC());

            if (prod.equals("1")) {
                concpt.close();
                conrcpt.close();
                concob.close();
                conupcpt.close();
                conrcptup.close();
                concobup.close();
                liteusuario.close();
                if (u.getTurno().equals("5") || u.getTipo_usuario().equals("1")) {
                    conexion.getCpttpu().close();
//                    conexion.getRcpttpu().close();
                    conexion.getCobranzatpu().close();
                }
            } else {
                conexion.getCpt().close();
                conexion.getCobranza().close();
                conexion.getRcpt().close();
                conexion.getCpttpu().close();
//                conexion.getRcpttpu().close();
                conexion.getCobranzatpu().close();
                liteusuario.close();
            }

            System.out.println("cerrar paneles");
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            System.exit(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Catalogos;
    private javax.swing.JDesktopPane JdPanel;
    private javax.swing.JLabel JlSerie;
    private javax.swing.JLabel JlUsuario;
    private javax.swing.JMenu JmAvances;
    private javax.swing.JMenuItem JmAvancesPt;
    private javax.swing.JMenuItem JmCES;
    private javax.swing.JMenuItem JmCatalogoprod;
    private javax.swing.JMenuItem JmCerrar;
    private javax.swing.JMenuItem JmCliente;
    private javax.swing.JMenuItem JmClientes;
    private javax.swing.JMenu JmCobranza;
    private javax.swing.JMenu JmConf;
    private javax.swing.JMenuItem JmEmpresas;
    private javax.swing.JMenuItem JmFacturacion;
    private javax.swing.JMenuItem JmFacturacionE;
    private javax.swing.JMenuItem JmFicha;
    private javax.swing.JMenuItem JmMaterial;
    private javax.swing.JMenuItem JmModcaja;
    private javax.swing.JMenuItem JmNotascr;
    private javax.swing.JMenuItem JmOut;
    private javax.swing.JMenuItem JmPagos;
    private javax.swing.JMenuItem JmPedimento;
    private javax.swing.JMenu JmProd;
    private javax.swing.JMenuItem JmProveedor;
    private javax.swing.JMenuItem JmRemision;
    private javax.swing.JMenu JmReportes;
    private javax.swing.JMenuItem JmRespaldos;
    private javax.swing.JMenuItem JmSalidas;
    private javax.swing.JMenuItem JmSesion;
    private javax.swing.JMenu JmTpu;
    private javax.swing.JMenu JmVentas;
    private javax.swing.JMenuItem JmVerfacts;
    private javax.swing.JMenuItem Jmabrir;
    private javax.swing.JMenu Jmreportes;
    private java.awt.PopupMenu JpClose;
    private javax.swing.JRadioButton JrEmpresa;
    private javax.swing.JRadioButton JrEmpresa1;
    private javax.swing.JMenuItem JtFacturaciontpu;
    private javax.swing.JPopupMenu PopMenu;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
