/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package athprod;

import DAO.daoAgentes;
import DAO.daoClientes;
import DAO.daoConceptos;
import DAO.daokardexrcpt;
import Modelo.Agentes;
import Modelo.Cliente;
import Modelo.ConceptosES;
import Modelo.Kardexrcpt;
import Modelo.Producto;
import Paneles.Paresremision;
import Server.Serverprod;
import java.awt.Color;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GATEWAY1-
 */
public class Salidas extends javax.swing.JInternalFrame {

    String var = "0";
    public String name;
    Connection rcpt, cobranza;
    Serverprod server68 = new Serverprod();
    ArrayList<Cliente> arrclientes = new ArrayList<>();
    ArrayList<Agentes> arragentes = new ArrayList<>();
    ArrayList<ConceptosES> arrconceptos = new ArrayList<>();
    ArrayList<Producto> arrprod = new ArrayList<>();
    daoClientes dcliente;
    daoConceptos dconceptos;
    daoAgentes dagentes;
    String serie = "A";
    String marca;

    /**
     * Creates new form Clientes
     */
    public Salidas() {
        initComponents();
        setbds();//Connecciones a la bd
        setcombos();//setea combos y tabla con datos
        JtBuscar.requestFocus();
        JlEstatus.setText("A");
        JlEstatus.setForeground(Color.blue);
    }

    private void setbds() {
        try {
//            rcpt = server68.getconexionserver8("RCPT");
            rcpt = server68.getconexionpruebarcpt();
            cobranza = server68.getconexionserver8("ACobranza");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Salidas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Salidas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Salidas.class.getName()).log(Level.SEVERE, null, ex);
        }
        dcliente = new daoClientes();
        dconceptos = new daoConceptos();
        dagentes = new daoAgentes();
        generatabla();
    }

    private void setcombos() {
        arrclientes = dcliente.getClientes(cobranza);
        arragentes = dagentes.getAgentes(cobranza);
        arrconceptos = dconceptos.getConceptos(rcpt);
        for (Cliente arrcliente : arrclientes) {
            JcCliente.addItem(arrcliente.getNombre());
        }
        for (Agentes arragente : arragentes) {
            JcAgente.addItem(arragente.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        JlEstatus = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JcCliente = new javax.swing.JComboBox<>();
        JcAgente = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        JtCuenta = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JtSubcuenta = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        JtEstilos = new javax.swing.JLabel();
        JlNombrec = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtMovimientos = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Salidas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        JtBuscar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JtBuscar.setForeground(new java.awt.Color(102, 102, 102));
        JtBuscar.setBorder(null);
        JtBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Magnifier_29783.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/1486485588-add-create-new-math-sign-cross-plus_81186.png"))); // NOI18N
        jLabel2.setToolTipText("Nuevo movimiento");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/applicationsgraphicsdrawing_103768.png"))); // NOI18N
        jLabel3.setToolTipText("Editar registro");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Cancel_icon-icons.com_54824.png"))); // NOI18N
        jLabel4.setToolTipText("Deshabilitar cliente");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/file_pdf_download_icon-icons.com_68954.png"))); // NOI18N
        jLabel5.setToolTipText("Reporte de clientes");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(124, 124, 124)
                .addComponent(jLabel3)
                .addGap(124, 124, 124)
                .addComponent(jLabel4)
                .addGap(117, 117, 117)
                .addComponent(jLabel5)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jList1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jList1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jList1);

        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(JtBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JtBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        JlEstatus.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JlEstatus.setForeground(new java.awt.Color(255, 51, 51));
        JlEstatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlEstatus.setText("B");
        JlEstatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JlEstatusMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Cliente ");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Agente");

        JtCuenta.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JtCuenta.setForeground(new java.awt.Color(102, 102, 102));
        JtCuenta.setBorder(null);
        JtCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtCuentaActionPerformed(evt);
            }
        });

        jSeparator3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Movimiento");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Concepto");

        JtSubcuenta.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JtSubcuenta.setForeground(new java.awt.Color(102, 102, 102));
        JtSubcuenta.setBorder(null);
        JtSubcuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtSubcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtSubcuentaActionPerformed(evt);
            }
        });

        jSeparator4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JtEstilos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/1491313949-fast-forward_82990.png"))); // NOI18N
        JtEstilos.setToolTipText("Añadir Estilos");
        JtEstilos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JtEstilos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtEstilosMousePressed(evt);
            }
        });

        JlNombrec.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JlNombrec.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JlEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator4)
                                    .addComponent(JtSubcuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                                .addGap(42, 42, 42)
                                .addComponent(JlNombrec, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JtEstilos))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JcCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(79, 79, 79)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(JcAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(JtCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                            .addComponent(jSeparator3))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(JlEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(JcCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(JcAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(JtSubcuenta))
                                .addGap(5, 5, 5)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JlNombrec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JtEstilos)
                        .addContainerGap())))
        );

        JtMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(JtMovimientos);

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Movimientos de Salida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        Kardexrcpt ka = new Kardexrcpt();
        Calendar fecha = Calendar.getInstance();
        int rowcliente = JcCliente.getSelectedIndex();
        ///////Formateo de fechas y hrs
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH) + 1;
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        int hora = fecha.get(Calendar.HOUR_OF_DAY);
        int minuto = fecha.get(Calendar.MINUTE);
        String month = (mes < 10) ? "0" + mes : "" + mes;
        String day = (dia < 10) ? "0" + dia : "" + dia;
        String fechas = año +"-"+ month +"-"+ day + "T" + formatohr(hora, minuto) + ":00";
        //////// Fin de formateo de fechas
        daokardexrcpt dk = new daokardexrcpt();
        ka.setFolio(dk.maxkardex(rcpt) + 1);
        ka.setPedido((dk.maxpedido(rcpt)+1)+ " " + arrprod.get(0).getMarca());
        ka.setCuenta(JtCuenta.getText());
        ka.setSubcuenta(JtSubcuenta.getText());
        ka.setFecha(fechas);
        ka.setRegistro(fechas);
        ka.setPrv(arrclientes.get(rowcliente).getCvecliente());
        ka.setVale(1);
        ka.setDocref("1");
        ka.setSerie(serie);
        ka.setAgente(arragentes.get(JcAgente.getSelectedIndex()).getIdagente());
        ka.setMarca(marca);
        ka.setArr(arrprod);
        daokardexrcpt dkardex = new daokardexrcpt();
        
        if(dkardex.nuevokardex(rcpt, ka)){
            JOptionPane.showMessageDialog(null, "Completo");
            vaciado();
        }else
            JOptionPane.showMessageDialog(null, "Ocurrio algo, vuelve a intentarlo o llama a sistemas c:");
        
        
    }//GEN-LAST:event_jLabel2MousePressed

    private void JtCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtCuentaActionPerformed
        for (int i = 0; i < arrconceptos.size(); i++) {
            String cuenta = arrconceptos.get(i).getCuenta();
            if (cuenta.equals(JtCuenta.getText()) && cuenta.equals("60")) {
//                System.out.println("cuenta " + JtCuenta.getText());
                JtSubcuenta.requestFocus();
                break;
            }
        }

    }//GEN-LAST:event_JtCuentaActionPerformed

    private void JtEstilosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtEstilosMousePressed
        setrenglones();
    }//GEN-LAST:event_JtEstilosMousePressed

    private void JtSubcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtSubcuentaActionPerformed
        boolean resp=false;
        for (int i = 0; i < arrconceptos.size(); i++) {
            String scuenta = arrconceptos.get(i).getSubcuenta();
            String cuenta = arrconceptos.get(i).getCuenta();
            if (scuenta.equals(JtSubcuenta.getText()) && cuenta.equals(JtCuenta.getText())) {
//                System.out.println("scuenta " + JtCuenta.getText());
                JtEstilos.requestFocus();
                JlNombrec.setText(arrconceptos.get(i).getNombre());
                resp =true;
                break;
            }
        }
        if(resp){
            setrenglones();
        }   
    }//GEN-LAST:event_JtSubcuentaActionPerformed

    private void JlEstatusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlEstatusMousePressed
        if (serie.equals("B")) {
            JlEstatus.setForeground(Color.blue);
            JlEstatus.setText("A");
            serie = "A";
        } else {
            JlEstatus.setForeground(Color.red);
            JlEstatus.setText("B");
            serie = "B";
        }
    }//GEN-LAST:event_JlEstatusMousePressed
    public final void generatabla() {

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Tipo");//0
        model.addColumn("Almacen");//1
        model.addColumn("Estilo");//2
        model.addColumn("Combinacion");//3
        model.addColumn("Corrida");//4
        model.addColumn("Cantidad");//5
        model.addColumn("Precio");//6
        if (!arrprod.isEmpty()) {// rellena de datos de acuerdo a las lineas que se capturen
            model.setRowCount(arrprod.size());
            for (int i = 0; i < arrprod.size(); i++) {
                model.setValueAt(arrprod.get(i).getTipo(), i, 0);
                model.setValueAt(arrprod.get(i).getAlmacen(), i, 1);
                model.setValueAt(arrprod.get(i).getEstilo(), i, 2);
                model.setValueAt(arrprod.get(i).getDesccombinacion(), i, 3);
                model.setValueAt(arrprod.get(i).getCordesc(), i, 4);
                model.setValueAt(arrprod.get(i).getCantidad(), i, 5);
                model.setValueAt(arrprod.get(i).getPrecio(), i, 6);
            }
        }
        JtMovimientos.setModel(model);
    }

    private void setrenglones() {
        Paresremision p = new Paresremision(null, true);
//        p.setAlwaysOnTop(true);
        p.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        p.setVisible(true);
        if (!p.prod.getDesccombinacion().equals("")) {
//            System.out.println("");
            arrprod.add(p.prod);
            marca=p.prod.getMarca();
            generatabla();
//            System.out.println("aqui");
        }
    }

    private String formatohr(int hora, int minuto) {
        String horas = "";
        if (hora > 9) {
            horas = hora + ":";
        }
        if (hora < 10) {
            horas = "0" + hora + ":";
        }
        if (minuto < 10) {
            horas = horas + "0" + minuto;
        }
        if (minuto > 9) {
            horas += minuto;
        }
////                System.out.println(horas);
        horas = (horas.length() == 5) ? horas : "0" + horas;
        return horas;
    }

    private void vaciado() {// reinicia todos los componentes y datos
        arrprod.clear();
        setcombos();
        generatabla();
        JtCuenta.setText("");
        JtSubcuenta.setText("");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcAgente;
    private javax.swing.JComboBox<String> JcCliente;
    private javax.swing.JLabel JlEstatus;
    private javax.swing.JLabel JlNombrec;
    public javax.swing.JTextField JtBuscar;
    public javax.swing.JTextField JtCuenta;
    private javax.swing.JLabel JtEstilos;
    private javax.swing.JTable JtMovimientos;
    public javax.swing.JTextField JtSubcuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
