/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tpu;

import DAO.daoantiguedadnotas;
import Modelo.Agentes;
import Modelo.AntiguedadNota;
import Modelo.Cliente;
import Server.Serverprod;
import Server.Serverylite;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author GATEWAY1-
 */
public class Antiguedad extends javax.swing.JFrame {

    public Connection s68, s90, lite;
    private ArrayList<Agentes> arr = new ArrayList<>();
    private ArrayList<Cliente> arrc = new ArrayList<>();

    /**
     * Inicio de la clase con los componentes y funciones necesarios para el
     * primer funcionamiento
     */
    public Antiguedad() {
        initComponents();
        setLocationRelativeTo(null);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/antique.png"));
        setIconImage(icon);
        Jra.setSelected(true);
        grupo.add(Jra);
        grupo.add(JrB);
//        getcon();
//        cargacombos();
    }

    /**
     * Setear conexion necesarias para la consulta y despliegue del reporte(cpt,
     * cobranza y lite)
     */
    private void getcon() {
        try {
            Serverprod s = new Serverprod();
            Serverylite l = new Serverylite();
            s68 = s.getconexionserver8("ACobranza");
            s90 = s.getconexionB("RACobranza");
            lite = l.getconexionusuarios();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Antiguedad.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error con la bd " + ex);
        } catch (IOException ex) {
            Logger.getLogger(Antiguedad.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Antiguedad.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error con la bd " + ex);
        }
    }

    public void cargacombos() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        daoantiguedadnotas d = new daoantiguedadnotas();
//        Se obtienen todos los agentes y se agrega uno extra llamado todos para englobarlos
        arr = d.getagentes(s68);
        model.addElement("TODOS");
//        Se añaden a la estructura del combo
        for (Agentes arr1 : arr) {
            model.addElement(arr1.getNombre() + ", " + arr1.getIdagente());
        }
        JcAgente.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        f1 = new com.toedter.calendar.JDateChooser();
        f2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JcAgente = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        JcSerie = new javax.swing.JComboBox<>();
        JtC2 = new javax.swing.JTextField();
        JtC3 = new javax.swing.JTextField();
        JtC1 = new javax.swing.JTextField();
        JtC4 = new javax.swing.JTextField();
        JtC5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JcCliente = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Jra = new javax.swing.JRadioButton();
        JrB = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Antigüedad de notas de venta");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("Fecha Final");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setText("Fecha inicio");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setText("Seleccion de Agente");

        JcAgente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        JcAgente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JcAgenteMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel4.setText("Serie");

        JcSerie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JcSerie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "Ambos" }));

        JtC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtC2ActionPerformed(evt);
            }
        });

        JtC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtC3ActionPerformed(evt);
            }
        });

        JtC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtC1ActionPerformed(evt);
            }
        });

        JtC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtC4ActionPerformed(evt);
            }
        });

        JtC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtC5ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ic_send_128_28719.png"))); // NOI18N
        jLabel6.setToolTipText("Ejecutar reporte");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel7.setText("Seleccion de Cliente");

        JcCliente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel9.setText("Rangos");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Jra.setBackground(new java.awt.Color(255, 255, 255));
        Jra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jra.setText("Por antigüedad");
        Jra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JraActionPerformed(evt);
            }
        });

        JrB.setBackground(new java.awt.Color(255, 255, 255));
        JrB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JrB.setText("Por fecha vencimiento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JrB)
                    .addComponent(Jra))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Jra)
                .addGap(18, 18, 18)
                .addComponent(JrB)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(f1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(JcAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JcSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JcCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JtC1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JtC2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JtC3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JtC4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JtC5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JcAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JcCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JcSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JtC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JtC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JtC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JtC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JtC5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            System.out.println("Cerrar conexiones");
            s68.close();
            s90.close();
            lite.close();
        } catch (SQLException ex) {
            Logger.getLogger(Antiguedad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void JtC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtC1ActionPerformed
        JtC2.requestFocus();
    }//GEN-LAST:event_JtC1ActionPerformed

    private void JtC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtC2ActionPerformed
        JtC3.requestFocus();
    }//GEN-LAST:event_JtC2ActionPerformed

    private void JtC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtC3ActionPerformed
        JtC4.requestFocus();
    }//GEN-LAST:event_JtC3ActionPerformed

    private void JtC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtC4ActionPerformed
        JtC5.requestFocus();
    }//GEN-LAST:event_JtC4ActionPerformed

    private void JtC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtC5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtC5ActionPerformed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        ejecutareporte();
    }//GEN-LAST:event_jLabel6MousePressed

    private void JraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JraActionPerformed

    private void JcAgenteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JcAgenteMousePressed
        DefaultComboBoxModel model1 = new DefaultComboBoxModel();
        daoantiguedadnotas d = new daoantiguedadnotas();
        String ag=(JcAgente.getSelectedIndex()==0)?"":arr.get(JcAgente.getSelectedIndex()-1).getIdagente()+"";
        arrc = d.getclientes(s68, ag);
        model1.addElement("TODOS");
        for (Cliente arr1 : arrc) {
            model1.addElement(arr1.getNombre() + ", " + arr1.getId_cliente());
        }
        JcCliente.setModel(model1);
    }//GEN-LAST:event_JcAgenteMousePressed

    /**
     * Funcion para ejecutar los procesos y despliegue del reporte
     */
    private void ejecutareporte() {
//        System.out.println(verificafechas() + " " + verificacampos());
        if (!verificacampos() && !verificafechas()) {
            JOptionPane.showMessageDialog(null, "Alguno de los rangos esta mal o no es un numero, intentelo de nuevo ");
            JtC1.requestFocus();
        } else {
            AntiguedadNota n = new AntiguedadNota();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyy");
            n.setF1(sdf.format(f1.getDate()));
            n.setF2(sdf.format(f2.getDate()));
            n.setC1(Integer.parseInt(JtC1.getText()));
            n.setC2(Integer.parseInt(JtC2.getText()));
            n.setC3(Integer.parseInt(JtC3.getText()));
            n.setC4(Integer.parseInt(JtC4.getText()));
            n.setC5(Integer.parseInt(JtC5.getText()));
            n.setTurno1(5);
//            Obtiene los datos del agente y cliente desde los arrays
            int row = JcAgente.getSelectedIndex();
//            Es importate saber que puede ser solo uno o todos, por lo tanto hay
//            que idenetificar ambos escenarios
            n.setAgente((row == 0) ? "" : arr.get(row - 1).getIdagente() + "");
            int row1 = JcCliente.getSelectedIndex();
            n.setCliente((row1 == 0) ? "" : arrc.get(row1 - 1).getId_cliente() + "");
            daoantiguedadnotas d = new daoantiguedadnotas();
//            Seleccion de la columna a usar como  principal y reutilizar el reporte sin hacer uno nuevo
            String fechat = (Jra.isSelected()) ? "Fecha" : "FechaVencimiento";
            ArrayList<AntiguedadNota> arra = new ArrayList<>();
            switch (JcSerie.getSelectedItem().toString()) {
                case "A": {
                    /**
                     * Funcion para obtener todos los registros necesarios
                     */
                    arra = d.getantiguedad(s68, n, fechat);
//                    Realliza la insercion de todos los registros encontrados a la bd de sqlite
                    d.newregistros(lite, arra);
                    break;
                }
                case "B": {
                    arra = d.getantiguedad(s90, n, fechat);
                    d.newregistros(lite, arra);
                    break;
                }
                default:
                    arra = d.getantiguedad(s68, n, fechat);
                    d.newregistros(lite, arra);
                    d.newregistros(lite, d.getantiguedad(s90, n, fechat));
                    break;
            }
//            Validar de que aun que no haya registros no entre a la generacion del reporte
            if (arra.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No se ha encontrado ningun registro!");
            } else {
                setreport();
            }
        }
    }

    /**
     * Despliegue a jasperreports
     */
    private void setreport() {
        try {
            Map parametros = new HashMap();
//            Agregar los rangos de cada uno de los campos
            parametros.put("c1", JtC1.getText());
            parametros.put("c2", JtC2.getText());
            parametros.put("c3", JtC3.getText());
            parametros.put("c4", JtC4.getText());
            parametros.put("c5", JtC5.getText());
            parametros.put("c6", JtC5.getText());
            JasperReport jasper = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportestpu/Indexantiguedad.jasper"));
            JasperPrint print = JasperFillManager.fillReport(jasper, parametros, lite);
            JasperViewer ver = new JasperViewer(print, false); //despliegue de reporte
            ver.setTitle("Antiguedad Notas de venta");
            ver.setVisible(true);

            daoantiguedadnotas d = new daoantiguedadnotas();
//            Elimina cada registro insertado de sqlite
            d.vaciartabla(lite);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            Logger.getLogger(Antiguedad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Verifica cada uno de los campos que sean enteros y no cualquier otro dato
     *
     * @return
     */
    private boolean verificacampos() {
        String c1 = JtC1.getText();
        String c2 = JtC2.getText();
        String c3 = JtC3.getText();
        String c4 = JtC4.getText();
        String c5 = JtC5.getText();
        return (verificaint(c1) && verificaint(c2) && verificaint(c3) && verificaint(c4) && verificaint(c5));
    }

    /**
     * Funcion que valida que las fechas no sean nulas y mandar un dato
     * incorrecto
     *
     * @return
     */
    private boolean verificafechas() {
        return (f1.getDate() != null && f2.getDate() != null);
    }

    /**
     * Funcion para validar que el campo sea un entero
     *
     * @param cad
     * @return
     */
    public boolean verificaint(String cad) {
        boolean resp = false;
        String patt = "[0-9]+";
        Pattern pat = Pattern.compile(patt);
        Matcher match = pat.matcher(cad);
        if (match.matches()) {
            resp = true;
        }
        return resp;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Antiguedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Antiguedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Antiguedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Antiguedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Antiguedad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcAgente;
    private javax.swing.JComboBox<String> JcCliente;
    private javax.swing.JComboBox<String> JcSerie;
    private javax.swing.JRadioButton JrB;
    private javax.swing.JRadioButton Jra;
    private javax.swing.JTextField JtC1;
    private javax.swing.JTextField JtC2;
    private javax.swing.JTextField JtC3;
    private javax.swing.JTextField JtC4;
    private javax.swing.JTextField JtC5;
    private com.toedter.calendar.JDateChooser f1;
    private com.toedter.calendar.JDateChooser f2;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
