/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panelavances;

import DAO.daoAvances;
import Modelo.Falla;
import Modelo.pantalla;
import Persistencia.sqlpantallas;
import Server.EnviarArchivo;
import Server.Serverprod;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author GATEWAY1-
 */
public class Nuevafalla extends javax.swing.JDialog {

    public Connection avances;
    public Connection litecfdi;
    public String usuario;
    private JFileChooser filechooser = new JFileChooser();
    ArrayList<pantalla> arr = new ArrayList<>();
    File archivo = null;
    File archivo2 = null;
    File archivo3 = null;
    File archivo4 = null;
    File archivo5 = null;
    File archivo6 = null;

    /**
     * Creates new form Nuevomaterial
     */
    public Nuevafalla(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JtNombre.requestFocus();
        setLocationRelativeTo(null);
        getconexion();
        llenacombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JcPantalla = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Jlimagen = new javax.swing.JLabel();
        JtNombre1 = new javax.swing.JTextField();
        JtNombre2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Jlimagen1 = new javax.swing.JLabel();
        JtNombre3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Jlimagen2 = new javax.swing.JLabel();
        Jlimagen5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JtNombre4 = new javax.swing.JTextField();
        Jlimagen4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JtNombre5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Jlimagen3 = new javax.swing.JLabel();
        JtNombre6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/Recursos/bordemorado.png")))); // NOI18N

        JtNombre.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        JtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtNombre.setBorder(null);
        JtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtNombreMousePressed(evt);
            }
        });
        JtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtNombreActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Asunto");

        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ic_send_128_28719.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Cancel_icon-icons.com_54824.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Capturar nuevo fallo de produccion");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Seleccion y captura de imagenes");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/add_plus_interface_icon_181584.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        JcPantalla.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Seleccion de pantalla");

        JtNombre1.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        JtNombre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtNombre1.setBorder(null);
        JtNombre1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtNombre1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtNombre1MousePressed(evt);
            }
        });
        JtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtNombre1ActionPerformed(evt);
            }
        });

        JtNombre2.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        JtNombre2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtNombre2.setBorder(null);
        JtNombre2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtNombre2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtNombre2MousePressed(evt);
            }
        });
        JtNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtNombre2ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/add_plus_interface_icon_181584.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        JtNombre3.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        JtNombre3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtNombre3.setBorder(null);
        JtNombre3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtNombre3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtNombre3MousePressed(evt);
            }
        });
        JtNombre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtNombre3ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/add_plus_interface_icon_181584.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/add_plus_interface_icon_181584.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });

        JtNombre4.setColumns(5);
        JtNombre4.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        JtNombre4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtNombre4.setBorder(null);
        JtNombre4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtNombre4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtNombre4MousePressed(evt);
            }
        });
        JtNombre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtNombre4ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/add_plus_interface_icon_181584.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });

        JtNombre5.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        JtNombre5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtNombre5.setBorder(null);
        JtNombre5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtNombre5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtNombre5MousePressed(evt);
            }
        });
        JtNombre5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtNombre5ActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/add_plus_interface_icon_181584.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });

        JtNombre6.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        JtNombre6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtNombre6.setBorder(null);
        JtNombre6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtNombre6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtNombre6MousePressed(evt);
            }
        });
        JtNombre6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtNombre6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Jlimagen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel3))
                                    .addComponent(JtNombre, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Jlimagen1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel4))
                                    .addComponent(JtNombre2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Jlimagen2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel5))
                                    .addComponent(JtNombre3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel6)
                                        .addGap(266, 266, 266))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(JtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(JcPantalla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Jlimagen3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel12))
                                    .addComponent(JtNombre6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Jlimagen4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel11))
                                    .addComponent(JtNombre5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Jlimagen5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel10))
                                    .addComponent(JtNombre4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JcPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jlimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jlimagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JtNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jlimagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JtNombre6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jlimagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JtNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jlimagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JtNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jlimagen5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     */
    private void getconexion() {
        try {
            Serverprod s = new Serverprod();
            avances = s.getconexionTPU("Avances");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Nuevafalla.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Nuevafalla.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Nuevafalla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void llenacombo() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        sqlpantallas s = new sqlpantallas();
        arr = s.getpantalla(avances);
        JcPantalla.setModel(model);
        for (pantalla arr1 : arr) {
            model.addElement(arr1.getNombre());
        }
        JtNombre1.requestFocus();
    }

    private void cerrar() {
        dispose();
    }

    /**
     * Funcion repetitiva para los 6 botones que seleccionan una imagen
     *
     * @return
     */
    private File getimgen() {
        File a = null;
        filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        filechooser.addChoosableFileFilter(new FileNameExtensionFilter("Images(jpg,png,bmp,gif)", "jpg", "png", "bmp", "gif"));
        filechooser.setAcceptAllFileFilterUsed(true);
        int returnval = filechooser.showOpenDialog(this);
        if (returnval == JFileChooser.APPROVE_OPTION) {
            a = filechooser.getSelectedFile();
        }
        return a;
    }

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        dispose();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        if (validacampos()) {
            nuevoasunto();
        }
    }//GEN-LAST:event_jLabel1MousePressed

    private void JtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtNombreActionPerformed
        JtNombre2.requestFocus();
    }//GEN-LAST:event_JtNombreActionPerformed

    private void JtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtNombreMousePressed
        JtNombre.setText("");
    }//GEN-LAST:event_JtNombreMousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        archivo = getimgen();
        Jlimagen.setText(archivo.getName());
    }//GEN-LAST:event_jLabel3MousePressed

    private void JtNombre1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtNombre1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtNombre1MousePressed

    private void JtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtNombre1ActionPerformed
        JtNombre.requestFocus();
    }//GEN-LAST:event_JtNombre1ActionPerformed

    private void JtNombre2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtNombre2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtNombre2MousePressed

    private void JtNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtNombre2ActionPerformed
        JtNombre3.requestFocus();
    }//GEN-LAST:event_JtNombre2ActionPerformed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        archivo2 = getimgen();
        Jlimagen1.setText(archivo2.getName());
    }//GEN-LAST:event_jLabel4MousePressed

    private void JtNombre3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtNombre3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtNombre3MousePressed

    private void JtNombre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtNombre3ActionPerformed
        JtNombre6.requestFocus();
    }//GEN-LAST:event_JtNombre3ActionPerformed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        archivo3 = getimgen();
        Jlimagen2.setText(archivo3.getName());
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        archivo6 = getimgen();
        Jlimagen5.setText(archivo6.getName());
    }//GEN-LAST:event_jLabel10MousePressed

    private void JtNombre4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtNombre4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtNombre4MousePressed

    private void JtNombre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtNombre4ActionPerformed
        validacampos();
    }//GEN-LAST:event_JtNombre4ActionPerformed

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        archivo5 = getimgen();
        Jlimagen4.setText(archivo5.getName());
    }//GEN-LAST:event_jLabel11MousePressed

    private void JtNombre5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtNombre5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtNombre5MousePressed

    private void JtNombre5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtNombre5ActionPerformed
        JtNombre4.requestFocus();
    }//GEN-LAST:event_JtNombre5ActionPerformed

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        archivo4 = getimgen();
        Jlimagen3.setText(archivo4.getName());
    }//GEN-LAST:event_jLabel12MousePressed

    private void JtNombre6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtNombre6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtNombre6MousePressed

    private void JtNombre6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtNombre6ActionPerformed
        JtNombre5.requestFocus();
    }//GEN-LAST:event_JtNombre6ActionPerformed

    private boolean validacampos() {
        boolean flag = true;
        if (JtNombre.getText().length() > 28 || JtNombre2.getText().length() > 28 || JtNombre2.getText().length() > 28
                || JtNombre3.getText().length() > 28 || JtNombre4.getText().length() > 28 || JtNombre5.getText().length() > 28) {
            JtNombre.requestFocus();
            JOptionPane.showMessageDialog(null, "EL texto de los campos no puede sobrepasar 28 caracteres");
            flag = false;
        }
        return flag;
    }

    private void nuevoasunto() {
        if (archivo != null) {
            daoAvances d = new daoAvances();
            java.util.Date date = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
            Falla f = new Falla();
            f.setPantalla(arr.get(JcPantalla.getSelectedIndex()).getPantalla());
            f.setFecha(sdf.format(date));
            f.setObservaciones(JtNombre1.getText().toUpperCase());
            f.setImagen1("fallas/" + archivo.getName());
            f.setDescimag1(JtNombre.getText().toUpperCase());
            f.setUsuario(usuario);
            f = validafalla(f);
//            Inserta una nueva falla, y si todo esta bien envia los archivos al servidor
            if (d.newfalla(avances, f)) {
                validenviarchivo();
                JOptionPane.showMessageDialog(null, "Exito al publicar un nueva falla");
                cerrar();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo agregar el nueva falla, intentelo de nuevo");
                JtNombre.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo agregar la nueva falla, seleccione una imagen antes de continuar");
        }

    }

    /**
     * Verifica que no haya nada nulos en las imagenes y no mostrarse en la
     * pantalla ell archivo llamado blank es para
     *
     * @param a
     * @return
     */
    private Falla validafalla(Falla a) {
        if (archivo2 != null) {
            a.setImagen2("fallas/" + archivo2.getName());
            a.setDescimag2(JtNombre2.getText().toUpperCase());
        } else {
            a.setImagen2("fallas/blank.png");
            a.setDescimag2("");
        }
        if (archivo3 != null) {
            a.setImagen3("fallas/" + archivo3.getName());
            a.setDescimag3(JtNombre3.getText().toUpperCase());
        } else {
            a.setImagen3("fallas/blank.png");
            a.setDescimag3("");
        }
        if (archivo4 != null) {
            a.setImagen4("fallas/" + archivo4.getName());
            a.setDescimag4(JtNombre6.getText().toUpperCase());
        } else {
            a.setImagen4("fallas/blank.png");
            a.setDescimag4("");
        }
        if (archivo5 != null) {
            a.setImagen5("fallas/" + archivo5.getName());
            a.setDescimag5(JtNombre5.getText().toUpperCase());
        } else {
            a.setImagen5("fallas/blank.png");
            a.setDescimag5("");
        }
        if (archivo6 != null) {
            a.setImagen6("fallas/" + archivo6.getName());
            a.setDescimag6(JtNombre4.getText().toUpperCase());
        } else {
            a.setImagen6("fallas/blank.png");
            a.setDescimag6("");
        }
        return a;
    }

    /**
     * Envia los archivos hacia el servidor solamente los que hayan sido
     * seleccionados y manda al servidor aquellos que no sean nulos
     */
    private void validenviarchivo() {
        try {
            EnviarArchivo e1 = new EnviarArchivo(archivo.getCanonicalPath(), 5001);
            e1.enviarArchivo();
            if (archivo2 != null) {
                EnviarArchivo e2 = new EnviarArchivo(archivo2.getCanonicalPath(), 5001);
                e2.enviarArchivo();
            }
            if (archivo3 != null) {
                EnviarArchivo e3 = new EnviarArchivo(archivo3.getCanonicalPath(), 5001);
                e3.enviarArchivo();
            }
            if (archivo4 != null) {
                EnviarArchivo e4 = new EnviarArchivo(archivo4.getCanonicalPath(), 5001);
                e4.enviarArchivo();
            }
            if (archivo5 != null) {
                EnviarArchivo e5 = new EnviarArchivo(archivo5.getCanonicalPath(), 5001);
                e5.enviarArchivo();
            }
            if (archivo6 != null) {
                EnviarArchivo e6 = new EnviarArchivo(archivo6.getCanonicalPath(), 5001);
                e6.enviarArchivo();
            }
        } catch (IOException ex) {
            Logger.getLogger(Nuevafalla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevafalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevafalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevafalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevafalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Nuevafalla dialog = new Nuevafalla(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcPantalla;
    private javax.swing.JLabel Jlimagen;
    private javax.swing.JLabel Jlimagen1;
    private javax.swing.JLabel Jlimagen2;
    private javax.swing.JLabel Jlimagen3;
    private javax.swing.JLabel Jlimagen4;
    private javax.swing.JLabel Jlimagen5;
    public javax.swing.JTextField JtNombre;
    public javax.swing.JTextField JtNombre1;
    public javax.swing.JTextField JtNombre2;
    public javax.swing.JTextField JtNombre3;
    public javax.swing.JTextField JtNombre4;
    public javax.swing.JTextField JtNombre5;
    public javax.swing.JTextField JtNombre6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
