/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import DAO.daocfdi;
import DAO.daoempresa;
import DAO.daofactura;
import DAO.daoxmlE;
import Modelo.Cliente;
import Modelo.Conexiones;
import Modelo.Dfactura;
import Modelo.Empresas;
import Modelo.Formadepago;
import Modelo.Formateo_Nempresas;
import Modelo.Formateodedatos;
import Modelo.Kardexrcpt;
import Modelo.Nocolision;
import Modelo.Poliza;
import Modelo.Sellofiscal;
import Modelo.Usuarios;
import Modelo.cargo;
import Modelo.convertirNumeros;
import Modelo.convertnum;
import Modelo.factura;
import Modelo.metodopago;
import Modelo.usocfdi;
import Server.Serverprod;
import Server.Serverylite;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import mx.sat.cfd40.timbrarXML;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author GATEWAY1-
 */
public class fac2E extends javax.swing.JPanel {

    public String nombre, empresa, empresarcpt, empresacob;
    public Connection sqlcfdi, sqlempresa;
    public Connection ACobranza, rcpt, cpt;
    Serverylite slite = new Serverylite();
    Serverprod prod = new Serverprod();
    public ArrayList<Formadepago> arrfpago = new ArrayList<>();
    public ArrayList<usocfdi> arruso = new ArrayList<>();
    public ArrayList<metodopago> arrmetodo = new ArrayList<>();
    daocfdi dcfdi = new daocfdi();
    double descuentos;
    double impuestos;
    double subtotal;
    double total;
    int cantidadtotal;
    String relacion = "";
    public Usuarios u;
    public ArrayList<Cliente> arrcliente = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();

    //kardex para fac
    ArrayList<Kardexrcpt> k = new ArrayList<>();
    //para factura relacionada
    ArrayList<cargo> arrcargo = new ArrayList<>();
    ArrayList<cargo> arrcargoseleccion = new ArrayList<>();//cargos seleccionados

    /**
     * Creates new form Cliente1
     */
    public fac2E() {
        initComponents();
        setdolar();
        generatabla();
        JcPublico.setVisible(false);
//        JsRel.setVisible(false);

//        iniciarconexiones();  Solo si se usa solo la clase si no se pasan directamente desde facturacion
// carga en combos los catalogos del sat
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        pop = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        JtDescuento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JtCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        JtFolio1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        JcMetodo = new javax.swing.JComboBox<>();
        JcForma = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        JcUso = new javax.swing.JComboBox<>();
        Jlfp = new javax.swing.JLabel();
        JlUso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtDetalle = new javax.swing.JTable();
        JcPublico = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Jlsub = new javax.swing.JLabel();
        JlDesc = new javax.swing.JLabel();
        JlIva = new javax.swing.JLabel();
        JlTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtObs = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JcUsd = new javax.swing.JCheckBox();
        JtTCambio = new javax.swing.JTextField();
        JlTcambio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        JsRel = new javax.swing.JScrollPane();
        JlRel = new javax.swing.JList<>();
        JlTcambio1 = new javax.swing.JLabel();

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/eraser_icon-icons.com_60679.png"))); // NOI18N
        jMenuItem1.setText("Eliminar linea");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        pop.add(jMenuItem1);

        setBackground(new java.awt.Color(255, 255, 255));

        JtDescuento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JtDescuento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtDescuento.setText("0");
        JtDescuento.setBorder(null);
        JtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtDescuentoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Descuento");

        JtCliente.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        JtCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtCliente.setBorder(null);
        JtCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtClienteMousePressed(evt);
            }
        });
        JtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtClienteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("# Cliente");

        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JtFolio1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JtFolio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtFolio1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Metodo de Pago");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jLabel15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel15KeyPressed(evt);
            }
        });

        JcMetodo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JcMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcMetodoActionPerformed(evt);
            }
        });

        JcForma.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JcForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcFormaActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Forma de Pago");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Uso Cfdi");

        JcUso.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JcUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcUsoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JcMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JcForma, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Jlfp, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JcUso, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlUso, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JcMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(JcForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(JcUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jlfp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlUso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        JtDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JtDetalle.setGridColor(new java.awt.Color(255, 255, 255));
        JtDetalle.setSelectionBackground(new java.awt.Color(213, 215, 250));
        JtDetalle.setSelectionForeground(new java.awt.Color(0, 0, 0));
        JtDetalle.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JtDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtDetalleMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(JtDetalle);

        JcPublico.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JcPublico.setText("Sin iva");
        JcPublico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcPublicoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Subtotal");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Descuento");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Iva");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Total");

        Jlsub.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Jlsub.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        JlDesc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JlDesc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        JlIva.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JlIva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        JlTotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JlTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jlsub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlIva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jlsub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JlDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JlIva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(JlTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ic_send_128_28719.png"))); // NOI18N
        jLabel2.setToolTipText("Procesar factura");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        JtObs.setColumns(20);
        JtObs.setRows(5);
        jScrollPane2.setViewportView(JtObs);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Observaciones");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Refresh_36729.png"))); // NOI18N
        jLabel3.setToolTipText("Actualiza datos");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        JcUsd.setText("USD - Dolares");
        JcUsd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcUsdActionPerformed(evt);
            }
        });

        JtTCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtTCambioActionPerformed(evt);
            }
        });

        JlTcambio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JlTcambio.setText("Tipo de cambio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JcUsd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JtTCambio)
                    .addComponent(JlTcambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JcUsd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(JlTcambio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JtTCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/new.png"))); // NOI18N
        jLabel5.setToolTipText("Añadir Renglones");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/propagation_calculator_calc_6110.png"))); // NOI18N
        jLabel13.setToolTipText("Relacion de facturas");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        JlRel.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        JlRel.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JsRel.setViewportView(JlRel);

        JlTcambio1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        JlTcambio1.setText("Relacion de factura");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JlTcambio1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(JsRel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JlTcambio1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JsRel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JtDescuento)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addComponent(JcPublico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JtCliente)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(JtFolio1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel2)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JtFolio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JcPublico)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void cargacombos() {//catalogos de Sat
        DefaultComboBoxModel metodo = new DefaultComboBoxModel();
        DefaultComboBoxModel forma = new DefaultComboBoxModel();
        DefaultComboBoxModel uso = new DefaultComboBoxModel();
        for (Formadepago arrfpago1 : arrfpago) {
            forma.addElement(arrfpago1.getFormapago() + " - " + arrfpago1.getConcepto());
        }
        for (metodopago arrmetodo1 : arrmetodo) {
            metodo.addElement(arrmetodo1.getMetodopago() + " - " + arrmetodo1.getDescripcion());
        }
        for (usocfdi arruso1 : arruso) {
            uso.addElement(arruso1.getusocfdi() + " - " + arruso1.getDescripcion());
        }
        JcForma.setModel(forma);
        JcMetodo.setModel(metodo);
        JcUso.setModel(uso);
    }

    private void setcombos() {
        boolean band = false;
        boolean band1 = false;
        int row = JtFolio1.getSelectedIndex();
        for (int i = 0; i < arrfpago.size(); i++) {
            if (arrcliente.get(row).getFormapago().equals(arrfpago.get(i).getFormapago())) {
                JcForma.setSelectedIndex(i);
                Jlfp.setText("");
                band = true;
                break;
            }
        }

        for (int i = 0; i < arruso.size(); i++) {
            if (arrcliente.get(row).getUsocfdi().equals(arruso.get(i).getusocfdi())) {
                JcUso.setSelectedIndex(i);
                JlUso.setText("");
                band1 = true;
                break;
            }
        }
        if (!band) {
            Jlfp.setText("No se encontro la forma de pago");
        }
        if (!band1) {
            JlUso.setText("No se encontro el uso cfdi");
        }
    }

    private void JtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtDescuentoActionPerformed
        if (verificafloat(JtDescuento.getText())) {
//            generatabla();
        } else {
            JOptionPane.showMessageDialog(null, "Error, solo colocar numeros enteros en el descuento");
        }
    }//GEN-LAST:event_JtDescuentoActionPerformed

    private void JtClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtClienteMousePressed
        JtCliente.setText("");
    }//GEN-LAST:event_JtClienteMousePressed

    private void JtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtClienteActionPerformed
        String r = JtCliente.getText();
        daofactura df = new daofactura();
        arrcliente = df.getClienteface(ACobranza, r);
        cargaclientes();

    }//GEN-LAST:event_JtClienteActionPerformed

    private void JcMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcMetodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcMetodoActionPerformed

    private void JcFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcFormaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcFormaActionPerformed

    private void JcUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcUsoActionPerformed
        int row = JtFolio1.getSelectedIndex();
        String regimen = arrcliente.get(row).getRegimen();
        String uso = arruso.get(JcUso.getSelectedIndex()).getusocfdi();
        verificaregimen(sqlcfdi, regimen, uso);
    }//GEN-LAST:event_JcUsoActionPerformed

    private void JtFolio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtFolio1ActionPerformed
        seleccionfolio();
    }//GEN-LAST:event_JtFolio1ActionPerformed

    private void JcPublicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcPublicoActionPerformed
//        generatabla();
    }//GEN-LAST:event_JcPublicoActionPerformed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        int t = JtDetalle.getRowCount();
        if (t != 0) {
            boolean a = verificafloat(JtDescuento.getText());
            boolean a1 = verificadetalle();
            boolean a2 = verificaclaveunidad();
            boolean a3 = verificafloat(JtTCambio.getText());
            if (!a) {
                JOptionPane.showMessageDialog(null, "Error, solo colocar numeros enteros en el descuento");
            }
            if (!a1) {
                JOptionPane.showMessageDialog(null, "Error, Verifica los precios");
            }
            if (!a2) {
                JOptionPane.showMessageDialog(null, "Error, Verifica las Claves del SAT");
            }
            if (!a3) {
                JOptionPane.showMessageDialog(null, "Error, Introduce un valor valido en el tipo de cambio");
            }
//            System.out.println(a + " - " + a1);
            if (!a && !a1 && a2 && a3) {
                JtDetalle.requestFocus();
            } else {
                Formateo_Nempresas fn= new Formateo_Nempresas();
                factura f = new factura();
                int row = JtFolio1.getSelectedIndex();
                String condicion;
                java.util.Date date = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
                daofactura dfac = new daofactura();
                ArrayList<Dfactura> arrf = new ArrayList<>();
                DecimalFormat formateador = new DecimalFormat("####.##");//para los decimales
                if (JcPublico.isSelected()) {//Setear impuestos
                    f.setIva(0);
                    f.setImpuestos(0);
                } else {
                    f.setImpuestos(Double.parseDouble(formateador.format(impuestos)));
                    f.setIva(16);
                }
                // fin setear impuestos

                Nocolision n = new Nocolision();
                f.setFolio(dfac.getmaxfolio(rcpt, "FAC"));//Obtiene y setea el foliomaximo de *documentos
                n.setConnecxiones(rcpt, f.getFolio());
                n.start();
//                JOptionPane.showMessageDialog(null, "Espera al msj de Aceptacion de folio "+n.isAlive());
                do {//ciclo hasta que termine la busqueda y asignacion, no es lo ideal pero es temporal y reduce colisiones

                } while (n.isAlive());
                f.setExportacion("01");
                f.setFolio(n.getfolio());
                f.setClaveusuario("");
                f.setSerie("FAC");
                f.setTurno(u.getTurno());
                f.setFecha(sdf.format(date));
                f.setPedido("");
                f.setFechasolicitado(sdf.format(date));
                f.setFechaentrega(sdf.format(date));
                f.setFoliokardex(0);
                f.setIdcliente(arrcliente.get(row).getCvecliente());
                f.setNombre(arrcliente.get(row).getNombre());
                f.setRfc(arrcliente.get(row).getRfc());
                f.setCalle(arrcliente.get(row).getCalle());
                f.setNexterior("0");
                f.setNinterior("0");
                f.setColonia(arrcliente.get(row).getColonia());
                f.setMunicipio(arrcliente.get(row).getCiudad());
                f.setEstado(arrcliente.get(row).getEstado());
                f.setPais(arrcliente.get(row).getEstado());
                f.setCp(arrcliente.get(row).getCp());
                f.setRegimen(arrcliente.get(row).getRegimen());
                f.setObservaciones(JtObs.getText().toUpperCase());
                f.setTotalcajas(0);
                f.setCantidadxcaja(0);
                f.setTiposerie("FACTURA");
                if (JcUsd.isSelected()) {
                    f.setMoneda("USD");
                    f.setTipocambio(Double.parseDouble(JtTCambio.getText()));
                } else {
                    f.setMoneda("MXN");
                    f.setTipocambio(1);
                }

                f.setFormapago(arrfpago.get(JcForma.getSelectedIndex()).getFormapago());
                f.setMetodopago(arrmetodo.get(JcMetodo.getSelectedIndex()).getMetodopago());
                f.setDescmetodop(arrmetodo.get(JcMetodo.getSelectedIndex()).getDescripcion());
                f.setUsocfdi(arruso.get(JcUso.getSelectedIndex()).getusocfdi());
                condicion = (f.getMetodopago().equals("PUE")) ? "Contado" : "Credito";
                f.setCondicion(condicion);
                f.setLugarexpedicion(fn.getLugar_exp());
                f.setAgente(arrcliente.get(row).getAgente());
                f.setPlazo(arrcliente.get(row).getPlazo());
                f.setMarca("O");
                f.setTiporelacion(relacion);
                f.setEmpresa(fn.getEmpresa(u.getTurno(), empresa));
                String folios = "";
                String facturas = "";
                ArrayList<String> arruuid = new ArrayList<>();
                if (!relacion.equals("")) {
                    for (int i = 0; i < arrcargoseleccion.size(); i++) {
                        if (i == 0) {
                            folios = arrcargoseleccion.get(i).getFoliofiscal();
                            facturas = arrcargoseleccion.get(i).getReferencia();
                        } else {
                            folios += ", " + arrcargoseleccion.get(i).getFoliofiscal();
                            facturas += ", " + arrcargoseleccion.get(i).getReferencia();

                        }
                        arruuid.add(arrcargoseleccion.get(i).getFoliofiscal());
                    }
                    f.setRefncredito(facturas);
                    f.setSeriefoliofiscalorig(folios);
                    f.setArruuid(arruuid);
                }
                double iva = 0.00;
                if (!JcPublico.isSelected()) {// verifica 
                    iva = 0.16;
                }
                int totalpares = 0;// Se usa para la tabla facturas
                impuestos = 0;
                descuentos = 0;
                subtotal=0;
                for (int i = 0; i < t; i++) {
                    Dfactura df = new Dfactura();
                    daocfdi d = new daocfdi();
                    double precio = Double.parseDouble(formateador.format(Double.parseDouble(JtDetalle.getValueAt(i, 3).toString())));
                    double tpares = Double.parseDouble(formateador.format(Double.parseDouble(JtDetalle.getValueAt(i, 2).toString())));
//                        float precio = Float.parseFloat(JtDetalle.getValueAt(i, 3).toString());
//                        int tpares = k.get(i).getTotalpares();
                    double desc = Double.parseDouble(JtDescuento.getText()) / 100;
                    double descuento = (tpares * precio) * desc;
                    df.setRenglon(i + 1);
                    df.setProducto(0);
                    df.setCantidadfloat(tpares);
                    df.setDescripcion(JtDetalle.getValueAt(i, 0).toString());
                    df.setCodigo(JtDetalle.getValueAt(i, 1).toString());
                    df.setUmedida(JtDetalle.getValueAt(i, 7).toString());
                    df.setDescumedida(d.getdescunidad(sqlcfdi, JtDetalle.getValueAt(i, 7).toString()));
                    df.setPrecio(Double.parseDouble(formateador.format(precio)));
                    df.setBase(Double.parseDouble(formateador.format((precio * tpares))));
                    df.setImpuesto("002");
                    df.setTipofactor("Tasa");
                    String as = formateador.format(((tpares * precio) - descuento) * iva);
                    df.setImporta(Double.parseDouble(as));
                    String as1 = formateador.format(descuento);
                    df.setDescuento(Double.parseDouble(as1));
//                    df.setDescuento(Double.parseDouble(formateador.format(descuento)));
                    df.setTasaocuota(iva + "");
//                    System.out.println("detalle " + df.getBase() + " " + df.getDescuento() + " " + df.getImpuesto());
                    arrf.add(df);
                    totalpares += tpares;
                    impuestos += Double.parseDouble(as);
                    descuentos += Double.parseDouble(as1);
                    subtotal +=formatdecimal(precio * tpares);
                }
                total = subtotal - descuentos + impuestos;
                f.setTotalpares(totalpares);
                f.setArr(arrf);
//                f.setImpuestos(Double.parseDouble(formateador.format(impuestos)));
                f.setImpuestos(formatdecimal(impuestos));
                f.setDescuento(formatdecimal(descuentos));
                f.setSubtotal(formatdecimal(subtotal));
                f.setTotal(formatdecimal(total));
//                f.setDescuento(Double.parseDouble(formateador.format(descuentos)));
//                f.setSubtotal(Double.parseDouble(formateador.format(subtotal)));
//                f.setTotal(Double.parseDouble(formateador.format(total)));
                ArrayList<Poliza> arrpoliza = dfac.getasientoscontable(ACobranza);
                ArrayList<Poliza> arrpolizas = new ArrayList<>();

                int conta = 0;
                Formateodedatos fd = new Formateodedatos();
                for (int i = 0; i < arrpoliza.size(); i++) {
                    String c = arrpoliza.get(i).getCuentalarga();
                    String cuenta = fd.convertcliente(c + fd.formatclientedigito(arrcliente.get(row).getCvecliente() + ""));
                    Poliza p = new Poliza();
                    p.setCuenta(1);
                    p.setSub(5);
                    p.setFecha(sdf.format(date));
                    p.setFolio(f.getFolio() + " O");
                    p.setIdcliente(arrcliente.get(row).getCvecliente());
                    p.setIdentificacion("M");
                    p.setCuentalarga(cuenta);
                    p.setCa(arrpoliza.get(i).getCa());
                    p.setOrden(arrpoliza.get(i).getOrden());
                    p.setDiario("000");
                    p.setMext("            0.00");
                    p.setAcumulativo(arrpoliza.get(i).getAcumulativo());
                    p.setConcepto(arrpoliza.get(i).getConcepto() + f.getFolio() + " O");
                    if (arrpoliza.get(i).getCuentalarga().equals("4005")) {
                        p.setReferencia(arrcliente.get(row).getClave() + "1" + fd.convierteagente(String.valueOf(arrcliente.get(row).getAgente())) + " 4.001");
                    } else {
                        p.setReferencia("4.001");
                    }
                    switch (conta) {
                        case 0:
                            p.setImporte(fd.ftotal(String.valueOf(formatdecimal(total))));
                            conta++;
                            break;
                        case 1:
                            p.setImporte(fd.ftotal(String.valueOf(formatdecimal(impuestos))));
                            conta++;
                            break;
                        case 2:
                            p.setImporte(fd.ftotal(String.valueOf(formatdecimal(subtotal - descuentos))));
                            conta = 0;
                            break;
                    }
                    arrpolizas.add(p);
                }
                f.setArrpolizas(arrpolizas);
                //id del documento recien añadido
//                Tiene 3 procesos de commit, 1. la fatura. 2. los sellos y cadena original, 3. sellos fiscales
//                int id = dfac.nuevafac(cpt, f, ACobranza, rcpt);
                int id = dfac.nuevafacE(cpt, f, ACobranza, rcpt);
                if (id != 0) {
//                    System.out.println("Exito");
                    daoxmlE dx = new daoxmlE();
                    f.setId(id);
                    dx.generarfac(f, cpt, sqlempresa);
                    timbrarXML tim = new timbrarXML();
                    Sellofiscal s = tim.timbrar(f.getSerie() + "_" + f.getFolio(), nombre, sqlempresa, f.getEmpresa());
//                    Sellofiscal s = tim.timbrar(f.getSerie() + "_" + f.getFolio(), "", sqlempresa, "2");
                    dfac.Updatesellofiscal(cpt, s, id);
                    setreport(f.getFolio(), f.getRegimen(), f.getMoneda());
                    JOptionPane.showMessageDialog(null, "Proceso terminado: \n " + s.getEstado());
                    vaciarcampos();
                    JtCliente.requestFocus();
                }
//                }
            }
        }
    }//GEN-LAST:event_jLabel2MousePressed

    private void Exectrans(daofactura dfac, factura f) {
        Conexiones cn = dfac.nuevafacEconex(cpt, f, ACobranza, rcpt);
        int id = cn.getResp();
        if (id != 0) {
//            System.out.println("Exito");
            daoxmlE dx = new daoxmlE();
            f.setId(id);
//                    dx.generarfac(f, cpt, sqlempresa);
            dx.generarfac(f, cn.getCpt(), sqlempresa);
            timbrarXML tim = new timbrarXML();
            Sellofiscal s = tim.timbrar(f.getSerie() + "_" + f.getFolio(), nombre, sqlempresa, f.getEmpresa());
//                    Sellofiscal s = tim.timbrar(f.getSerie() + "_" + f.getFolio(), "", sqlempresa, "2");
//                    dfac.Updatesellofiscal(cpt, s, id);
            dfac.Updatesellofiscal(cn.getCpt(), s, id);
            setreport(f.getFolio(), f.getRegimen(), f.getMoneda());
            JOptionPane.showMessageDialog(null, "Proceso terminado: \n " + s.getEstado());
            vaciarcampos();
            JtCliente.requestFocus();
        } else {

        }
    }

    /**
     * Funcion para determinar si la cantidad decimal es redondeada o truncada
     *
     * @param cant cantidad en decimal
     * @return Cantidad redondeada o truncada
     */
    private double formatdecimal(double cant) {
        int dato = 0;
        int punto = 0;
        boolean band = false;
        double resp;
        String c = String.valueOf(cant);
//        String cadena = "";
        for (int i = 0; i < c.length(); i++) {
//            Empieza a tomar datos despues del punto
            if (c.charAt(i) == '.') {
                band = true;
            }
            if (band) {
//                3 digitos de decimal para saber qe hacer con los decimales
                if (punto == 3) {
                    dato = Integer.parseInt(c.charAt(i) + "");
                    i = c.length();
                    break;
                }
//                cadena += c.charAt(i);
                punto++;
            }
        }
        if ((dato <= 5)) {
            resp = BigDecimal.valueOf(cant).setScale(2, RoundingMode.FLOOR).doubleValue();
        } else {
            resp = BigDecimal.valueOf(cant).setScale(2, RoundingMode.HALF_UP).doubleValue();
        }
        return resp;
    }

    /**
     *
     * @param folio Folio de la factura
     * @param arrmetodo Array que contiene el metodo de pago
     * @param arruso Array que contiene el uso de cfdi
     * @see Despliegue y creacion del archivo pdf con los datos previamente
     * creados El reporte fue previamente creado en un modulo anterior que solo
     * creaba el pdf el proyecto se llama "Facturas"
     *
     */
    private void setreport(int folio, String regimen, String moneda) {
        try {
            daoempresa d = new daoempresa();
//            Identificar si es de ath o uptown
            Formateo_Nempresas fn= new Formateo_Nempresas();
            String conformidad=(!moneda.equals("MXN"))?"De conformidad con el Art. 20 del C.F.F., informamos que "
                    + "para convertir moneda extranjera a su equivalente en moneda nacional, el tipo de cambio a "
                    + "utilizar para efectos de pagos será el que publique el Banco de México en el Diario Oficial "
                    + "de la Federación el día habil anterior al día de pago. Para su consulta: www.banxico.org.mx "
                    + "(sección: Mercado cambiario/Tipos de cambio para solventar obligaciones denominadas en dólares de los Ee.Uu:A., pagaderas en la República Mexicana)":" ";
            String n = fn.getEmpresa(u.getTurno(), empresa);
            String logo = (empresa.equals("UptownCPT")) ? "Uptown.jpg" : "AF.png";
            Empresas e = d.getempresarfc(sqlempresa, n);
            String lugar=(empresa.equals("UptownCPT")) ? e.getCp() : "BLVD LAS TORRES 516  DEL VALLE  SAN FRANCISCO DEL RINCON  GUANAJUATO "+e.getCp();
//             fin identificar empresa
            Map parametros = new HashMap();
            convertirNumeros cnum = new convertirNumeros();
            DecimalFormat formateador = new DecimalFormat("####.##");//para los decimales
            String numeros = formateador.format(total);
//            Agregar parametros al reporte
            parametros.put("folio", folio);
//            parametros.put("totalletra", conv.controlconversion(total).toUpperCase()); String.valueOf(total)
            parametros.put("totalletra", cnum.Convertir(numeros, true, moneda));
            parametros.put("nombre", e.getNombre());
            parametros.put("rfc", e.getRfc());
            parametros.put("regimen", e.getRegimen());
            parametros.put("lugar", lugar);
            parametros.put("comprobante", e.getNumcertificado());
            parametros.put("logo", "C:\\af\\bin\\" + logo);// direcion predefinida, posible cambiar en un futuro
            parametros.put("metodo", arrmetodo.get(JcMetodo.getSelectedIndex()).getDescripcion());
            parametros.put("uso", arruso.get(JcUso.getSelectedIndex()).getDescripcion());
            parametros.put("serie", "FAC");
            parametros.put("regimencliente", regimen);
            parametros.put("confo", conformidad);

            JasperReport jasper = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportes/index.jasper"));
            JasperPrint print = JasperFillManager.fillReport(jasper, parametros, cpt);
            JasperViewer ver = new JasperViewer(print, false); //despliegue de reporte
            ver.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            ver.setTitle("FAC " + folio);
            ver.setVisible(true);
//            Exportacion al archivo pdf
            JRExporter exporter = new JRPdfExporter();
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, print);
            exporter.setParameter(JRExporterParameter.OUTPUT_FILE, new java.io.File(e.getXml() + "\\FAC_" + folio + ".pdf"));
            exporter.exportReport();
        } catch (JRException ex) {
            Logger.getLogger(fac1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void JtDetalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtDetalleMousePressed
        if (evt.getButton() == 3) {// activar con clic derecho
            pop.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_JtDetalleMousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        actualizaimportes();
    }//GEN-LAST:event_jLabel3MousePressed

    private void JcUsdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcUsdActionPerformed
        setdolar();
    }//GEN-LAST:event_JcUsdActionPerformed

    private void JtTCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtTCambioActionPerformed
        if (!verificafloat(JtTCambio.getText().toUpperCase())) {
            JOptionPane.showMessageDialog(null, "Error, Introduce un valor valido en el tipo de cambio");
            JtTCambio.requestFocus();
        }
    }//GEN-LAST:event_JtTCambioActionPerformed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
//        System.out.println("index " + JtFolio1.getSelectedIndex());
        if (arrcliente.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error, No puedes agregar lineas sin haber seleccionado un cliente");
        } else {
            String[] rowt = {"", "", "", "", "", "", "", ""};
            model.addRow(rowt);
//            JtDetalle.setModel(model);
        }
    }//GEN-LAST:event_jLabel5MousePressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (!arrcliente.isEmpty()) {
            int row = JtDetalle.getSelectedRow();
            JtDetalle.setValueAt("", row, 0);
            JtDetalle.setValueAt("", row, 1);
            JtDetalle.setValueAt("", row, 2);
            JtDetalle.setValueAt("", row, 3);
            JtDetalle.setValueAt("", row, 4);
            JtDetalle.setValueAt("", row, 5);
            JtDetalle.setValueAt("", row, 6);
            JtDetalle.setValueAt("", row, 7);
            model.removeRow(JtDetalle.getSelectedRow());
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
//        System.out.println(JtFolio1.getSelectedIndex());
        if (arrcliente.isEmpty() && JtFolio1.getSelectedIndex() == -1) {

        } else {
            FactsRel f = new FactsRel(null, true);
            daofactura df = new daofactura();
            arrcargo = df.getfactstoFACRel(cpt, arrcliente.get(JtFolio1.getSelectedIndex()).getCvecliente() + "", empresacob);
            f.arrcargo = arrcargo;
            f.setVisible(true);
            arrcargoseleccion = f.arrcargoseleccion;
            if (!arrcargoseleccion.isEmpty()) {
//            DefaultListModel<String> model = new DefaultListModel<>();
//            for (cargo arrcargoseleccion1 : arrcargoseleccion) {
//                model.addElement(arrcargoseleccion1.getReferencia() + " - " + arrcargoseleccion1.getDescuento());
//            }
//            JlRel.setModel(model);
                llenalista();
                relacion = "07";
            }
        }
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel15KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel15KeyPressed

    }//GEN-LAST:event_jLabel15KeyPressed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked

    }//GEN-LAST:event_jLabel15MouseClicked

    private void setdolar() {
        if (JcUsd.isSelected()) {
            JlTcambio.setVisible(true);
            JtTCambio.setVisible(true);
            JtTCambio.requestFocus();
        } else {
            JlTcambio.setVisible(false);
            JtTCambio.setVisible(false);
        }
    }

    private void vaciarcampos() {
        arrcliente.clear();
        arrcargo.clear();
        arrcargoseleccion.clear();
        JtObs.setText("");
        JtTCambio.setText("");
        JcUsd.setSelected(false);
        JtDescuento.setText("0");
        JlIva.setText("");
        Jlsub.setText("");
        JlDesc.setText("");
        JlTotal.setText("");
        Jlfp.setText("");
        JlUso.setText("");
        relacion = "";
        cargacombos();
        llenalista();
        cargaclientes();
//        generatabla();
        JtCliente.setText("");
        JtCliente.requestFocus();
        for (int i = 0; i < JtDetalle.getRowCount(); i++) {
            model.removeRow(i);
        }
        model.setNumRows(0);

    }

    private void llenalista() {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (cargo arrcargoseleccion1 : arrcargoseleccion) {
            model.addElement(arrcargoseleccion1.getReferencia() + " - " + arrcargoseleccion1.getDescuento());
        }
        JlRel.setModel(model);
    }

    private void seleccionfolio() {
        setcombos();
    }
//Carga de la busqueda de clientes

    private void cargaclientes() {
        DefaultComboBoxModel models = new DefaultComboBoxModel();
        for (int i = 0; i < arrcliente.size(); i++) {
            models.addElement(arrcliente.get(i).getNombre());
        }
        JtFolio1.setModel(models);
        JtFolio1.requestFocus();
        cargacombos();
    }

    public final void generatabla() {//Tabla actualizable con respecto al descuento e iva
        model.addColumn("Descripcion");//0  estilo combinacion corrida
        model.addColumn("Clave SAT");//1
        model.addColumn("Cantidad");//2
        model.addColumn("Precio");//3
        model.addColumn("Descuento");//4
        model.addColumn("Impuestos");//5
        model.addColumn("Importe");//6
        model.addColumn("Unidad SAT");//7
        JtDetalle.setModel(model);

        //Variables para manejo de totales
//        descuentos = subtotal * Float.parseFloat(JtDescuento.getText()) / 100;
//        impuestos = (float) ((subtotal - descuentos) * iva);
//        total = subtotal - descuentos + impuestos;
//        //Solo para despliqgue de informacion
//        JlIva.setText(formateador.format(impuestos));
//        Jlsub.setText(formateador.format(subtotal));
//        JlDesc.setText(formateador.format(descuentos));
//        JlTotal.setText(formateador.format(total));
//        JtDetalle.setModel(model);
    }

    private void actualizaimportes() {
        subtotal = 0;
        impuestos = 0;
        descuentos = 0;
        double iva = 0;
        int t = JtDetalle.getRowCount();
        boolean resp = true;
        if (!JcPublico.isSelected()) {// verifica 
            iva = 0.16;
        }
        DecimalFormat formateador = new DecimalFormat("####.##");
        if (!arrcliente.isEmpty()) {// rellena de datos de acuerdo a las lineas que se capturen
            for (int i = 0; i < t; i++) {
//                valida Precio
                if (!verificafloat(JtDetalle.getValueAt(i, 3).toString())
                        || !verificafloat(JtDetalle.getValueAt(i, 2).toString())) {// que no se pase algo que no sea un numero
                    JOptionPane.showMessageDialog(null, "Error, Verifica las cantidades");
                    JtDetalle.setValueAt("0", i, 3);
                    JtDetalle.setValueAt("0", i, 2);
                    resp = false;
                    break;
                } else {
                    // tomara en cuanta todo lo que encuentre en la tabla
                    double tpares = Double.parseDouble(JtDetalle.getValueAt(i, 2).toString());
//                    int tpares = Integer.parseInt(JtDetalle.getValueAt(i, 2).toString());
                    double desc = Double.parseDouble(JtDescuento.getText()) / 100;
                    double precio = Double.parseDouble(JtDetalle.getValueAt(i, 3).toString());
                    double descuento = (tpares * precio) * desc;
                    JtDetalle.setValueAt(precio, i, 3);
                    JtDetalle.setValueAt(formateador.format(descuento), i, 4);
                    JtDetalle.setValueAt(formateador.format(((tpares * precio) - descuento) * iva), i, 5);
                    JtDetalle.setValueAt(formateador.format((tpares * precio)), i, 6);
                    //suma de totales
                    cantidadtotal += tpares;
                    String as1 = formateador.format(descuento);
                    descuentos += Double.parseDouble(as1);
                    subtotal += tpares * precio;
                    impuestos += ((tpares * precio) - descuento) * iva;
                }
                if (resp) {// Si, y solo si es un entero o decimal
                    //Variables para manejo de totales
                    //impuestos =(float) ((subtotal - descuentos) * iva);
//                    descuentos = subtotal * Double.parseDouble(JtDescuento.getText()) / 100;
                    impuestos = ((subtotal - descuentos) * iva);
                    total = subtotal - descuentos + impuestos;
//                    total = subtotal - descuentos + impuestos;
//                    System.out.println(impuestos + " -" + subtotal + " - " + total);
                    //Solo para despliqgue de informacion
                    JlIva.setText(formateador.format(impuestos));
                    Jlsub.setText(formateador.format(subtotal));
                    JlDesc.setText(formateador.format(descuentos));
                    JlTotal.setText(formateador.format(total));
                }
            }
//            Valida las claves y las unidades
            if (!verificaclaveunidad()) {
                JOptionPane.showMessageDialog(null, "Error, Verifica las Claves del SAT");
            }
        }
    }

    private boolean verificaint(String cad) {
//        System.out.println("int -" + cad + "-");
        boolean resp = false;
        String patt = "[0-9]+";
        Pattern pat = Pattern.compile(patt);
        Matcher match = pat.matcher(cad);
        if (match.matches()) {
            resp = true;
        }
        return resp;
    }

    private boolean verificafloat(String cad) {
////        System.out.println("float -" + cad + "-");
        boolean resp = false;
        String patt = "[0-9]+||[0-9]+.[0-9]+";
        Pattern pat = Pattern.compile(patt);
        Matcher match = pat.matcher(cad);
        if (match.matches()) {
            resp = true;
        }
        return resp;
    }

    private boolean verificaregimen(Connection cfdi, String regimen, String uso) {
        daocfdi df = new daocfdi();
        boolean a = true;
        String resp = df.getRegimenxuso(cfdi, regimen, uso);
        if (resp.equals("")) {
            JOptionPane.showMessageDialog(null, "Error, El regimen del cliente no se puede usar con este uso cfdi");
            a = false;
        }
        return a;
    }

    /**
     *
     * @return Verificacion de la clave de producto y de unidad del sat
     */
    private boolean verificaclaveunidad() {
        daocfdi d = new daocfdi();
        boolean resp = false;
        int t = JtDetalle.getRowCount();
        for (int i = 0; i < t; i++) {
            if (d.getclave(sqlcfdi, JtDetalle.getValueAt(i, 1).toString()) && d.getunidad(sqlcfdi, JtDetalle.getValueAt(i, 7).toString())) {
                resp = true;
            } else {
                JtDetalle.setValueAt("", i, 1);
                JtDetalle.setValueAt("", i, 7);
                resp = false;
                break;
            }
        }
        return resp;
    }

    /**
     *
     * @return
     */
    private boolean verificadetalle() {
        boolean resp = true;
        for (int i = 0; i < k.size(); i++) {
            String precio = JtDetalle.getValueAt(i, 3).toString();
            if (!verificafloat(precio)) {
                resp = false;
                break;
            }
        }
        return resp;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcForma;
    private javax.swing.JComboBox<String> JcMetodo;
    private javax.swing.JCheckBox JcPublico;
    private javax.swing.JCheckBox JcUsd;
    private javax.swing.JComboBox<String> JcUso;
    private javax.swing.JLabel JlDesc;
    private javax.swing.JLabel JlIva;
    private javax.swing.JList<String> JlRel;
    private javax.swing.JLabel JlTcambio;
    private javax.swing.JLabel JlTcambio1;
    private javax.swing.JLabel JlTotal;
    private javax.swing.JLabel JlUso;
    private javax.swing.JLabel Jlfp;
    private javax.swing.JLabel Jlsub;
    private javax.swing.JScrollPane JsRel;
    public javax.swing.JTextField JtCliente;
    private javax.swing.JTextField JtDescuento;
    private javax.swing.JTable JtDetalle;
    private javax.swing.JComboBox<String> JtFolio1;
    private javax.swing.JTextArea JtObs;
    private javax.swing.JTextField JtTCambio;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu pop;
    // End of variables declaration//GEN-END:variables
}
