/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import DAO.daocfdi;
import DAO.daoempresa;
import DAO.daofactura;
import DAO.daoxmlncr;
import Modelo.ConceptosES;
import Modelo.Dfactura;
import Modelo.Empresas;
import Modelo.Formadepago;
import Modelo.Formateo_Nempresas;
import Modelo.Kardexrcpt;
import Modelo.Sellofiscal;
import Modelo.Usuarios;
import Modelo.cargo;
import Modelo.convertnum;
import Modelo.factura;
import Modelo.metodopago;
import Modelo.relacion;
import Modelo.usocfdi;
import Server.Serverprod;
import Server.Serverylite;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import mx.sat.cfd40.timbrarXML;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author GATEWAY1-
 */
public class ncr2 extends javax.swing.JPanel {

    public String nombre, empresa;
    public Connection sqlcfdi, sqlempresa;
    public Connection ACobranza, rcpt, cpt;
    Serverylite slite = new Serverylite();
    Serverprod prod = new Serverprod();
    public ArrayList<Formadepago> arrfpago = new ArrayList<>();
    public ArrayList<usocfdi> arruso = new ArrayList<>();
    public ArrayList<metodopago> arrmetodo = new ArrayList<>();
    public ArrayList<ConceptosES> arrcuentas = new ArrayList<>();
    public ArrayList<relacion> arrrelacion = new ArrayList<>();
    ArrayList<cargo> arrcargo = new ArrayList<>();
    ArrayList<cargo> arrcargoseleccion = new ArrayList<>();//cargos seleccionados
    daocfdi dcfdi = new daocfdi();
    DefaultTableModel model = new DefaultTableModel();
    double descuentos;
    double impuestos;
    double subtotal;
    double total;
    public Usuarios u;

    //kardex para fac
    ArrayList<Kardexrcpt> k = new ArrayList<>();
    ArrayList<Kardexrcpt> k0 = new ArrayList<>();

    /**
     * Creates new form Cliente1
     */
    public ncr2() {
        initComponents();
        cargatabla();
        JlTcambio.setVisible(false);
        JtTCambio.setVisible(false);
//        iniciarconexiones();  Solo si se usa solo la clase si no se pasan directamente desde facturacion
// carga en combos los catalogos del sat

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        pop = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        JlNombre = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        JtCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        JcMetodo = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        JcForma = new javax.swing.JComboBox<>();
        JcUso = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        JtRelacion = new javax.swing.JComboBox<>();
        JcCuenta = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtDetalle = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtObs = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        JcUsd = new javax.swing.JCheckBox();
        JtTCambio = new javax.swing.JTextField();
        JlTcambio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Jlcargofac = new javax.swing.JList<>();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Jlsub = new javax.swing.JLabel();
        JlDesc = new javax.swing.JLabel();
        JlIva = new javax.swing.JLabel();
        JlTotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        pop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                popMousePressed(evt);
            }
        });

        jMenuItem1.setText("Elimina linea");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        pop.add(jMenuItem1);

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        JlNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JlNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JtCliente.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        JtCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtCliente.setBorder(null);
        JtCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtClienteMousePressed(evt);
            }
        });
        JtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtClienteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("# Cliente");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Metodo de Pago");

        JcMetodo.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        JcMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcMetodoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Forma de Pago");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Uso Cfdi");

        JcForma.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        JcForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcFormaActionPerformed(evt);
            }
        });

        JcUso.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        JcUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcUsoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JcForma, 0, 441, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(JcUso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JcMetodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(JcMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(JcForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(JcUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        JtRelacion.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JtRelacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtRelacionActionPerformed(evt);
            }
        });

        JcCuenta.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JcCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcCuentaActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Cuentas");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Relacion");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JcCuenta, 0, 341, Short.MAX_VALUE)
                    .addComponent(JtRelacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(JcCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(JtRelacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JtDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "clave sat", "Descuento"
            }
        ));
        JtDetalle.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JtDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtDetalleMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(JtDetalle);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Refresh_36729.png"))); // NOI18N
        jLabel3.setToolTipText("Actualiza datos");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/new.png"))); // NOI18N
        jLabel5.setToolTipText("Actualiza datos");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ic_send_128_28719.png"))); // NOI18N
        jLabel2.setToolTipText("Procesar Nota de Credito");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        JtObs.setColumns(20);
        JtObs.setRows(5);
        jScrollPane2.setViewportView(JtObs);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        JcUsd.setText("USD - Dolares");
        JcUsd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcUsdActionPerformed(evt);
            }
        });

        JtTCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtTCambioActionPerformed(evt);
            }
        });

        JlTcambio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JlTcambio.setText("Tipo de cambio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JcUsd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JtTCambio)
                    .addComponent(JlTcambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JcUsd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(JlTcambio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JtTCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/flat-style-circle-save_icon-icons.com_66942.png"))); // NOI18N
        jLabel4.setToolTipText("Actualiza datos");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        Jlcargofac.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(Jlcargofac);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Facturas en Uso");

        jPanel3.setBackground(new java.awt.Color(10, 78, 160));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Subtotal");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Descuento");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Iva");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total");

        Jlsub.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Jlsub.setForeground(new java.awt.Color(255, 255, 255));
        Jlsub.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        JlDesc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JlDesc.setForeground(new java.awt.Color(255, 255, 255));
        JlDesc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        JlIva.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JlIva.setForeground(new java.awt.Color(255, 255, 255));
        JlIva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        JlTotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JlTotal.setForeground(new java.awt.Color(255, 255, 255));
        JlTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jlsub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlIva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jlsub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JlDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JlIva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(JlTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Observaciones");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(JtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 138, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addComponent(jScrollPane1))))
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addGap(29, 29, 29)
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6))
                                                    .addGap(6, 6, 6)
                                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(JlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addGap(66, 66, 66)
                                            .addComponent(jLabel2)))
                                    .addGap(71, 71, 71))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel21)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cargatabla() {
        model.addColumn("Descripcion");
        model.addColumn("Clave sat");
        model.addColumn("Descuento");
        model.addColumn("Cantidad");
        model.addColumn("Unidad");
        JtDetalle.setModel(model);
    }

    public void cargacombos() {//catalogos de Sat
        DefaultComboBoxModel metodo = new DefaultComboBoxModel();
        DefaultComboBoxModel forma = new DefaultComboBoxModel();
        DefaultComboBoxModel uso = new DefaultComboBoxModel();
        DefaultComboBoxModel relacion = new DefaultComboBoxModel();
        DefaultComboBoxModel cuentas = new DefaultComboBoxModel();
        for (Formadepago arrfpago1 : arrfpago) {
            forma.addElement(arrfpago1.getFormapago() + " - " + arrfpago1.getConcepto());
        }
        for (metodopago arrmetodo1 : arrmetodo) {
            metodo.addElement(arrmetodo1.getMetodopago() + " - " + arrmetodo1.getDescripcion());
        }
        for (usocfdi arruso1 : arruso) {
            uso.addElement(arruso1.getusocfdi() + " - " + arruso1.getDescripcion());
        }
        for (relacion arruso1 : arrrelacion) {
            relacion.addElement(arruso1.getRelacion() + " - " + arruso1.getConcepto());
        }
        JcForma.setModel(forma);
        JcMetodo.setModel(metodo);
        JcUso.setModel(uso);
        JtRelacion.setModel(relacion);
        // Cuentas
        daofactura d = new daofactura();
        arrcuentas = d.getalcuentas(ACobranza, "60");
        for (ConceptosES arruso1 : arrcuentas) {
            cuentas.addElement(arruso1.getCuenta() + ", " + arruso1.getSubcuenta() + " - " + arruso1.getNombre());
        }
        JcCuenta.setModel(cuentas);
    }

    private void JtClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtClienteMousePressed
        JtCliente.setText("");
    }//GEN-LAST:event_JtClienteMousePressed

    private void JtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtClienteActionPerformed
        String r = JtCliente.getText();
        daofactura df = new daofactura();
        arrcargo = df.getfactstoncr(ACobranza, r, empresa);// cpt a usar
        if (arrcargo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay cargos con ese cliente");
            JtCliente.setText("");
            JtCliente.requestFocus();
        } else {
            JlNombre.setText(arrcargo.get(0).getNombre());
//            Carga y despliega la informacion de los combobox
            cargacombos();
        }
    }//GEN-LAST:event_JtClienteActionPerformed

    private void JcMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcMetodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcMetodoActionPerformed

    private void JcFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcFormaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcFormaActionPerformed

    private void JcUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcUsoActionPerformed
        String regimen = arrcargo.get(0).getRegimen();
        String uso = arruso.get(JcUso.getSelectedIndex()).getusocfdi();
        verificaregimen(sqlcfdi, regimen, uso);
    }//GEN-LAST:event_JcUsoActionPerformed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        boolean band = true;
        boolean band1 = checkunidad();
        for (int i = 0; i < model.getRowCount(); i++) {
            String col2 = JtDetalle.getValueAt(i, 1).toString();
            if (col2.equals("")) {
                band = false;
            }
        }
        if (band && band1) {
            setfactura();
        } else {
            JOptionPane.showMessageDialog(null, "Error, Alguna de las claves de producto o unidad esta vacia o erronea, verificalo");
        }
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        actualizaimportes();
    }//GEN-LAST:event_jLabel3MousePressed

    private void JtRelacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtRelacionActionPerformed
        relaciones();
    }//GEN-LAST:event_JtRelacionActionPerformed

    private void JcCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcCuentaActionPerformed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        if (!arrcargo.isEmpty()) {
            cargacargos();
        }
    }//GEN-LAST:event_jLabel4MousePressed

    private boolean verificaregimen(Connection cfdi, String regimen, String uso) {
        daocfdi df = new daocfdi();
        boolean a = true;
        String resp = df.getRegimenxuso(cfdi, regimen, uso);
        if (resp.equals("")) {
            JOptionPane.showMessageDialog(null, "Error, El regimen del cliente no se puede usar con este uso cfdi");
            a = false;
        }
        return a;
    }

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        String rel = arrrelacion.get(JtRelacion.getSelectedIndex()).getRelacion();
        if (!rel.equals("03")) {
            JOptionPane.showMessageDialog(null, "No puedes usar este tipo de relacion para agregar renglones, cambialo e intentalo de nuevo");
            JtRelacion.requestFocus();
        } else {
            String[] rowt = {"", "", "", "", ""};
            model.addRow(rowt);
            JtDetalle.setModel(model);
        }


    }//GEN-LAST:event_jLabel5MousePressed

    private void popMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popMousePressed

    }//GEN-LAST:event_popMousePressed

    private void JtDetalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtDetalleMousePressed
        if (evt.getButton() == 3) {// activar con clic derecho
            pop.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_JtDetalleMousePressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        model.removeRow(JtDetalle.getSelectedRow());
//        System.out.println("Elimine linea y total de lineas " + model.getRowCount());

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseReleased

    private void JcUsdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcUsdActionPerformed
        setdolar();
    }//GEN-LAST:event_JcUsdActionPerformed

    private void JtTCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtTCambioActionPerformed
        if (!verificafloat(JtTCambio.getText().toUpperCase())) {
            JOptionPane.showMessageDialog(null, "Error, Introduce un valor valido en el tipo de cambio");
            JtTCambio.requestFocus();
        }
    }//GEN-LAST:event_JtTCambioActionPerformed

    private void setdolar() {
        if (JcUsd.isSelected()) {
            JlTcambio.setVisible(true);
            JtTCambio.setVisible(true);
            JtTCambio.requestFocus();
        } else {
            JlTcambio.setVisible(false);
            JtTCambio.setVisible(false);
        }
    }

    private void relaciones() {
        String se = arrrelacion.get(JtRelacion.getSelectedIndex()).getRelacion();
        if (se.equals("03")) {
            JtObs.setText("");
        }
        if (se.equals("01")) {
            JtObs.setText("SERVICIOS DE FACTURACION");
            JtObs.requestFocus();
        }
        if (se.equals("07")) {
            JtObs.setText("SERVICIOS DE FACTURACION APLICACION DE ANTICIPO");
            JtObs.requestFocus();
        }
    }

    private void actualizaempresa() {
        arrcargoseleccion.clear();
        JtCliente.setText("");
        JtCliente.requestFocus();
        llenalistafac();
    }

    private void cargacargos() {
        if (!arrcargo.isEmpty()) {
            Cargosncr p = new Cargosncr(null, true);
//        p.setAlwaysOnTop(true);
            p.relacion = arrrelacion.get(JtRelacion.getSelectedIndex()).getRelacion();
            p.arrcargo = arrcargo;
            p.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            p.setVisible(true);
            arrcargoseleccion = p.arrcargoseleccion;
            llenalistafac();
            actualizaimportes();
            relaciones();
//            if (!p.prod.getDesccombinacion().equals("")) {
//                System.out.println("");
//                System.out.println("aqui");
//            }
        }

    }

    private void llenalistafac() {
        DefaultListModel<String> model = new DefaultListModel<>();
        DecimalFormat formateador = new DecimalFormat("####.##");
        for (cargo arrcargoseleccion1 : arrcargoseleccion) {
            model.addElement(arrcargoseleccion1.getReferencia() + " - " + formateador.format(arrcargoseleccion1.getDescuento()));
        }
        Jlcargofac.setModel(model);
    }

    private void setfactura() {
//        Si no hay nada en los cargos de seleccion regresa al campo original
        if (arrcargoseleccion.isEmpty()) {
            JtCliente.requestFocus();
        } else {
            double totalrev = 0;
            //Se obtiene el total de las facturas que anter se capturaron
            for (int i = 0; i < arrcargoseleccion.size(); i++) {
                totalrev += formatdecimal(arrcargoseleccion.get(i).getDescuento());
            }
//            System.out.println(total + " " + totalrev);
//            System.out.println(total + " " + formateador.format(totalrev));
//            if (totalrev != total) {
//            System.out.println(formatdecimal(total) + " ** " + formatdecimal(totalrev));
            if (formatdecimal(total) != formatdecimal(totalrev)) {
                JOptionPane.showMessageDialog(null, "El total de las lineas debe de ser igual al seleccionado en las facturas");
                JtDetalle.requestFocus();
            } else {
                Formateo_Nempresas fn = new Formateo_Nempresas();
                factura f = new factura();
//            int row = JtFolio1.getSelectedIndex();
                String condicion;
                java.util.Date date = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
                daofactura dfac = new daofactura();
                ArrayList<Dfactura> arrf = new ArrayList<>();
//                DecimalFormat formateador = new DecimalFormat("####.##");//para los decimales

//                Nocolisionncr n = new Nocolisionncr();
                f.setFolio(dfac.getmaxfolio(cpt, "NCR"));//Obtiene y setea el foliomaximo de *documentos
//                n.setConnecxiones(rcpt, f.getFolio());
//                n.start();
////                JOptionPane.showMessageDialog(null, "Espera al msj de Aceptacion de folio "+n.isAlive());
//                do {//ciclo hasta que termine la busqueda y asignacion, no es lo ideal pero es temporal y reduce colisiones
//
//                } while (n.isAlive());
//                System.out.println(n.getfolio());
//                f.setFolio(n.getfolio());
                if (JcUsd.isSelected()) {
                    f.setMoneda("USD");
                    f.setTipocambio(Float.parseFloat(JtTCambio.getText()));
                } else {
                    f.setMoneda("MXN");
                    f.setTipocambio(1);
                }
                // fin setear impuestos
//                f.setImpuestos(Double.parseDouble(formateador.format(impuestos)));
//                f.setImpuestos(formatdecimal(subtotal*0.16));
//                f.setImpuestos(Double.parseDouble(formateador.format(impuestos)));
                f.setImpuestos(formatdecimal(impuestos));
                f.setExportacion("01");
                f.setTiporelacion(arrrelacion.get(JtRelacion.getSelectedIndex()).getRelacion());
                f.setIva(16);
//                condicion = "Contado";
                f.setEmpresa(fn.getEmpresa(u.getTurno(), empresa));
//                f.setEmpresa("1");
                f.setClaveusuario(u.getUsuario());
                f.setTurno(u.getTurno());
                f.setSerie("NCR");
//                f.setFolio(dfac.getmaxfolio(rcpt,"NCR"));//Obtiene y setea el foliomaximo NCR de *documentos
                f.setFecha(sdf.format(date));
                f.setDescuento(0);
                f.setPedido("");
                f.setFechasolicitado(sdf.format(date));
//                f.setCondicion(condicion);
                f.setFechaentrega(sdf.format(date));
                f.setSubtotal(formatdecimal(subtotal));
                f.setTotal(formatdecimal(total));
                f.setIdcliente(arrcargoseleccion.get(0).getCliente());
                f.setNombre(arrcargoseleccion.get(0).getNombre());
                f.setRfc(arrcargoseleccion.get(0).getRfc());
                f.setCalle(arrcargoseleccion.get(0).getCalle());
                f.setNexterior("0");
                f.setNinterior("0");
                f.setColonia(arrcargoseleccion.get(0).getColonia());
                f.setMunicipio(arrcargoseleccion.get(0).getMunicipio());
                f.setEstado(arrcargoseleccion.get(0).getEstado());
                f.setPais(arrcargoseleccion.get(0).getPais());
                f.setCp(arrcargoseleccion.get(0).getCp());
                f.setRegimen(arrcargoseleccion.get(0).getRegimen());
                f.setTotalcajas(0);
                f.setCantidadxcaja(0);
                f.setTiposerie("NOTA DE CREDITO");
                f.setFormapago(arrfpago.get(JcForma.getSelectedIndex()).getFormapago());
//                f.setMetodopago(arrmetodo.get(JcMetodo.getSelectedIndex()).getMetodopago());
//                f.setDescmetodop(arrmetodo.get(JcMetodo.getSelectedIndex()).getDescripcion());
                f.setMetodopago("PUE");
                f.setDescmetodop("PAGO EN UNA SOLA EXHIBICION");
                f.setUsocfdi(arruso.get(JcUso.getSelectedIndex()).getusocfdi());
                condicion = (f.getMetodopago().equals("PUE")) ? "Contado" : "Credito";
                f.setCondicion(condicion);
                f.setAgente(arrcargoseleccion.get(0).getAgente());
                f.setPlazo(arrcargoseleccion.get(0).getPlazo());
                f.setMarca(arrcargoseleccion.get(0).getRef());
                f.setLugarexpedicion(fn.getLugar_exp());
                f.setCuentaabono(arrcuentas.get(JcCuenta.getSelectedIndex()).getCuenta());
                f.setSubabono(arrcuentas.get(JcCuenta.getSelectedIndex()).getSubcuenta());
                f.setDesccuenta(arrcuentas.get(JcCuenta.getSelectedIndex()).getNombre());
                String folios = "";
                String facturas = "";
                //Mandar un string con los folios fiscales

                ArrayList<String> arruuid = new ArrayList<>();
//                Funcion que obtiene y almacena los folios y facturas en un String 
//                Ademas de agregar en un Array Los folios fiscal de cada factura afectada
                for (int i = 0; i < arrcargoseleccion.size(); i++) {
                    if (i == 0) {
                        folios = arrcargoseleccion.get(i).getFoliofiscal();
                        facturas = arrcargoseleccion.get(i).getReferencia();
                    } else {
                        folios += "," + arrcargoseleccion.get(i).getFoliofiscal();
                        facturas += ", " + arrcargoseleccion.get(i).getReferencia();
                    }
                    arruuid.add(arrcargoseleccion.get(i).getFoliofiscal());
                }

//                System.out.println("cargo seleccion " + arrcargoseleccion.size());
                f.setRefncredito(facturas);
                f.setObservaciones(JtObs.getText().toUpperCase() + " " + facturas);
                f.setFoliofiscalorig(folios);
                String rel = arrrelacion.get(JtRelacion.getSelectedIndex()).getRelacion();// seobtiene tipo de relacion
                int tamaño = (!rel.equals("03")) ? 1 : model.getRowCount();// Numero de conceptos de acuerdo a la relacion
                ArrayList<cargo> arrayc = new ArrayList<>();
                double sumatotal = 0;
                //control interno de las lineas de seleccion
                int x = 0;
                //Tamaño define el numero de renglones que el ciclo tomara
                int aux = 0;
                double unidad = 0;
                for (int i = 0; i < tamaño; i++) {
                    Dfactura df = new Dfactura();
                    double precio = 0;
                    int pares = 0;
                    String descripcion = "";
                    String codigosat = "";
                    String umedida = "";
                    double impuesto;
                    double pre = 0;
                    if (rel.equals("03")) {//numero de renglones tambien para detalle docs
                        pre = Double.parseDouble(JtDetalle.getValueAt(i, 2).toString());
                        unidad = formatdecimal(pre);
//                        unidad = Double.parseDouble(formateador.format(pre));
                        pares = Integer.parseInt(JtDetalle.getValueAt(i, 3).toString());
                        precio = formatdecimal((pre * pares) * 0.16 + (pre * pares));
//                        precio = Double.parseDouble(formateador.format((pre * pares) * 0.16 + (pre * pares)));
                        descripcion = JtDetalle.getValueAt(i, 0).toString();
                        codigosat = JtDetalle.getValueAt(i, 1).toString();
                        umedida = JtDetalle.getValueAt(i, 4).toString().toUpperCase();
                        arrayc = getcargosfacs();
                    } else {
                        //Detalle solo para 1 renglon que es la relacion 01 y 07
//                        precio = Float.parseFloat(formateador.format(arrcargoseleccion.get(i).getDescuento() / 1.16));
                        precio = formatdecimal(total / 1.16);
                        pares = 1;
                        descripcion = JtObs.getText().toUpperCase() + " " + facturas;
                        codigosat = "84111506";
                        umedida = "ACT";
                        //Se hace la operacion aqui ya que solo se ejecutara 1 vez
                        for (int j = 0; j < arrcargoseleccion.size(); j++) {
                            cargo car = new cargo();
//                            arruuid.add(arrcargoseleccion.get(j).getFoliofiscal());
                            car.setDescuento(arrcargoseleccion.get(j).getDescuento());// importe a descontar de cargos
                            car.setFoliofiscal(folios);
                            car.setCuenta(arrcargoseleccion.get(j).getCuenta());
                            car.setSubcuenta(arrcargoseleccion.get(j).getSubcuenta());
                            car.setCliente(arrcargoseleccion.get(j).getCliente());
                            car.setReferencia(arrcargoseleccion.get(j).getReferencia());
                            car.setFecha(arrcargoseleccion.get(j).getFecha());
                            car.setDescnota(JtObs.getText().toUpperCase() + " " + facturas);
                            car.setCantidad(1);
                            arrayc.add(car);
                        }
                    }
                    if (rel.equals("03")) {
//                        df.setPrecioant(Double.parseDouble(formateador.format(precio)));
//                        df.setBase(Double.parseDouble(formateador.format(precio / 1.16)));
//                        precio = Double.parseDouble(formateador.format(precio / 1.16));
                        df.setPrecioant(formatdecimal(precio));
                        df.setBase(formatdecimal(precio / 1.16));
                        precio = formatdecimal(precio / 1.16);
                        df.setPrecio(unidad);
                        impuesto = formatdecimal((precio * 0.16));
                    } else {
                        df.setPrecio(formatdecimal(subtotal));
                        df.setBase(formatdecimal(subtotal));
                        df.setPrecioant(formatdecimal(subtotal * 0.16));
//                        df.setPrecio(Double.parseDouble(formateador.format(precio)));
//                        df.setBase(Double.parseDouble(formateador.format(precio)));
//                        df.setPrecioant(Double.parseDouble(formateador.format(impuestos)));
                        impuesto = formatdecimal(impuestos);
                    }

//                    System.out.println((float) precio * pares);
                    df.setRenglon(i + 1);
                    df.setProducto(0);
                    df.setCantidadfloat(pares);
                    df.setDescripcion(descripcion);
                    df.setCodigo(codigosat);
                    df.setUmedida(umedida);
                    df.setImpuesto("002");
                    df.setTipofactor("Tasa");
                    df.setImporta(impuesto);
                    df.setDescuento(0);
                    df.setTasaocuota("0.16");
                    arrf.add(df);
                }
                f.setArrcargo(arrayc);
                f.setArr(arrf);
                f.setArruuid(arruuid);
                //id del documento recien añadido
//                int verifica=dfac.getbuscafolio(cpt, "NCR");
                int verifica = dfac.getbuscafolioncr(cpt, f.getFolio() + "");
                if (verifica != 0) {
                    JOptionPane.showMessageDialog(null, "Error!,- El folio ya se encuentra en uso, contacta a sistemas ");
                } else {
                    int id = dfac.nuevancr(cpt, f, ACobranza, rcpt);
                    if (id != 0) {
//                        System.out.println("Exito");
                        daoxmlncr dx = new daoxmlncr();
                        f.setId(id);
                        dx.generarfac(f, cpt, sqlempresa);
                        timbrarXML tim = new timbrarXML();
                        Sellofiscal s = tim.timbrar(f.getSerie() + "_" + f.getFolio(), nombre, sqlempresa, f.getEmpresa());
                        dfac.Updatesellofiscal(cpt, s, id);
                        setreport(f.getFolio(), f.getRegimen(), f.getMoneda());
                        JOptionPane.showMessageDialog(null, "Proceso terminado- " + s.getEstado());
                        vaciarcampos();
                        JtCliente.requestFocus();
                    }
                }
//                Tiene 3 procesos de commit, 1. la fatura. 2. los sellos y cadena original, 3. sellos fiscales

            }

        }
    }

    private double formatdecimal(double cant) {
        int dato = 0;
        int punto = 0;
        boolean band = false;
        double resp;
        String c = String.valueOf(cant);
//        String cadena = "";
        for (int i = 0; i < c.length(); i++) {
//            Empieza a tomar datos despues del punto
            if (c.charAt(i) == '.') {
                band = true;
            }
            if (band) {
//                3 digitos de decimal para saber qe hacer con los decimales
                if (punto == 3) {
                    dato = Integer.parseInt(c.charAt(i) + "");
//                    i = c.length();
                    break;
                }
//                Para un cuarto decimal, si es mayor a
//                if (punto == 4) {
//                    int datoaux = Integer.parseInt(c.charAt(i) + "");
//                    if (datoaux > 5) {
//                        dato += 1;
//                    }
//                    i = c.length();
//                    break;
//                }
//                cadena += c.charAt(i);
                punto++;
            }
        }
        if ((dato < 5)) {
            resp = BigDecimal.valueOf(cant).setScale(2, RoundingMode.FLOOR).doubleValue();
        } else {
            resp = BigDecimal.valueOf(cant).setScale(2, RoundingMode.HALF_UP).doubleValue();
        }
        return resp;
    }

    public ArrayList<cargo> getcargosfacs() {
        ArrayList<cargo> arr = new ArrayList<>();
        DecimalFormat formateador = new DecimalFormat("####.##");
        for (int y = 0; y < arrcargoseleccion.size(); y++) {
            cargo car = new cargo();
            double desc = Double.parseDouble(formateador.format(arrcargoseleccion.get(y).getDescuento()));
            car.setDescuento(Double.parseDouble(formateador.format(desc)));
            car.setFoliofiscal(arrcargoseleccion.get(y).getFoliofiscal());
            car.setCuenta(arrcargoseleccion.get(y).getCuenta());
            car.setSubcuenta(arrcargoseleccion.get(y).getSubcuenta());
            car.setCliente(arrcargoseleccion.get(y).getCliente());
            car.setReferencia(arrcargoseleccion.get(y).getReferencia());
            car.setFecha(arrcargoseleccion.get(y).getFecha());
            arr.add(car);
        }
        return arr;
    }

    /**
     *
     * @param folio Folio de la factura
     * @param arrmetodo Array que contiene el metodo de pago
     * @param arruso Array que contiene el uso de cfdi
     * @see Despliegue y creacion del archivo pdf con los datos previamente
     * creados El reporte fue previamente creado en un modulo anterior que solo
     * creaba el pdf el proyecto se llama "Facturas"
     *
     */
    private void setreport(int folio, String regimen, String moneda) {
        try {
            Formateo_Nempresas fn = new Formateo_Nempresas();
            String conformidad = (!moneda.equals("MXN")) ? "De conformidad con el Art. 20 del C.F.F., informamos que "
                    + "para convertir moneda extranjera a su equivalente en moneda nacional, el tipo de cambio a "
                    + "utilizar para efectos de pagos será el que publique el Banco de México en el Diario Oficial "
                    + "de la Federación el día habil anterior al día de pago. Para su consulta: www.banxico.org.mx "
                    + "(sección: Mercado cambiario/Tipos de cambio para solventar obligaciones denominadas en dólares de los Ee.Uu:A., pagaderas en la República Mexicana)" : " ";
            daoempresa d = new daoempresa();
//            Identificar si es de ath o uptown
            String n = fn.getEmpresa(u.getTurno(), empresa);
            String logo = (empresa.equals("UptownCPT")) ? "Uptown.jpg" : "AF.png";
            Empresas e = d.getempresarfc(sqlempresa, n);
            String lugar = (empresa.equals("UptownCPT")) ? e.getCp() : "BLVD LAS TORRES 516 DEL VALLE SAN FRANCISCO DEL RINCON GUANAJUATO " + e.getCp();
//             fin identificar empresa
            Map parametros = new HashMap();
//            Clase que contiene el numero convertido a caracter
            convertnum conv = new convertnum();
//            Agregar parametros al reporte
            parametros.put("folio", folio);
            parametros.put("totalletra", conv.controlconversion(total).toUpperCase());
            parametros.put("nombre", e.getNombre());
            parametros.put("rfc", e.getRfc());
            parametros.put("regimen", e.getRegimen());
            parametros.put("lugar", lugar);
            parametros.put("comprobante", e.getNumcertificado());
            parametros.put("logo", "C:\\af\\bin\\" + logo);// direcion predefinida, posible cambiar en un futuro
            parametros.put("metodo", arrmetodo.get(JcMetodo.getSelectedIndex()).getDescripcion());
            parametros.put("uso", arruso.get(JcUso.getSelectedIndex()).getDescripcion());
            parametros.put("serie", "NCR");
            parametros.put("regimencliente", regimen);
            parametros.put("confo", conformidad);

            JasperReport jasper = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportes/indexncr.jasper"));
            JasperPrint print = JasperFillManager.fillReport(jasper, parametros, cpt);
            JasperViewer ver = new JasperViewer(print, false); //despliegue de reporte
            ver.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            ver.setTitle("NCR " + folio);
            ver.setVisible(true);
//            Exportacion al archivo pdf
            JRExporter exporter = new JRPdfExporter();
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, print);
            exporter.setParameter(JRExporterParameter.OUTPUT_FILE, new java.io.File(e.getXml() + "\\NCR_" + folio + ".pdf"));
            exporter.exportReport();
        } catch (JRException ex) {
            Logger.getLogger(fac1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void vaciarcampos() {
        arrcargoseleccion.clear();
        JtTCambio.setText("");
        JlDesc.setText("0");
        Jlsub.setText("0");
        JlIva.setText("0");
        JlTotal.setText("0");
        arrcargo.clear();
        JtCliente.setText("");
        JlNombre.setText("");
        JtObs.setText(nombre);
        llenalistafac();
        actualizaimportes();
        cargacombos();
        for (int i = 0; i < model.getRowCount(); i++) {
            model.removeRow(i);
        }
    }

    private void actualizaimportes() {
        subtotal = 0;
        impuestos = 0;
        descuentos = 0;
        double iva = 0;
        boolean resp = true;
        iva = 0.16;
        String rel = arrrelacion.get(JtRelacion.getSelectedIndex()).getRelacion();
        if (rel.equals("03")) {// Verifica el tipo de relacion y que no se pueda agregar renglones en los que no sean '03'
            //verirfica de que no tenga facturas
            if (!arrcargoseleccion.isEmpty()) {
                int rows = model.getRowCount();
                for (int i = 0; i < rows; i++) {
                    //Verifica de que sea un numero y no cualquier cosa
                    if ((verificafloat(JtDetalle.getValueAt(i, 2).toString()) || verificaint(JtDetalle.getValueAt(i, 2).toString())
                            || verificaflotante(JtDetalle.getValueAt(i, 2).toString())) && !JtDetalle.getValueAt(i, 4).toString().isEmpty()) {
                        double precio = Double.parseDouble(JtDetalle.getValueAt(i, 2).toString());
                        int can = Integer.parseInt(JtDetalle.getValueAt(i, 3).toString());
//                        subtotal += Double.parseDouble(formateador.format((precio) * can));
//                        impuestos += Double.parseDouble(formateador.format(((precio) * can) * 0.16));
                        subtotal += formatdecimal((precio) * can);
                        impuestos += formatdecimal((precio * can) * 0.16);
                    } else {
                        JOptionPane.showMessageDialog(null, "Introduce solo numeros e intentalo de nuevo");
                        break;

                    }

                }

                total = subtotal + impuestos;
//                System.out.println(impuestos);
                //Solo para despliqgue de informacion
                JlIva.setText(formatdecimal(impuestos)+"");
                Jlsub.setText(formatdecimal(subtotal)+"");
                JlDesc.setText(formatdecimal(descuentos)+"");
                JlTotal.setText(formatdecimal(total)+"");
            } else {
                JtCliente.requestFocus();// regresa al campo inicial del cliente
            }
        } else {
            if (!arrcargoseleccion.isEmpty()) {// rellena de datos de acuerdo a las lineas que se capturen
                for (int i = 0; i < arrcargoseleccion.size(); i++) {
                    double precio = arrcargoseleccion.get(i).getDescuento();
                    //suma de totales
//                    subtotal += Double.parseDouble(formateador.format(precio / 1.16));
//                    impuestos += Double.parseDouble(formateador.format((precio / 1.16) * 0.16));
                    subtotal += formatdecimal(precio / 1.16);
                    impuestos += formatdecimal((precio / 1.16) * 0.16);
//                    System.out.println("01 " + impuestos + " " + subtotal);
                }
                if (resp) {// Si, y solo si es un entero o decimal
                    //Variables para manejo de totales
//                descuentos = subtotal * Float.parseFloat(JtDescuento.getText()) / 100;
                    //impuestos =(float) ((subtotal - descuentos) * iva);
//                    total = subtotal + impuestos;
                    total = formatdecimal(subtotal + impuestos);
//                    System.out.println(impuestos);
                    //Solo para despliqgue de informacion
                    JlIva.setText(formatdecimal(impuestos) + "");
                    Jlsub.setText(formatdecimal(subtotal) + "");
                    JlDesc.setText(formatdecimal(descuentos) + "");
                    JlTotal.setText(formatdecimal(total) + "");
                }
            }
        }
        if (!arrcargo.isEmpty()) {
            String regimen = arrcargo.get(0).getRegimen();
            String uso = arruso.get(JcUso.getSelectedIndex()).getusocfdi();
            verificaregimen(sqlcfdi, regimen, uso);
        }

    }

    private boolean checkunidad() {
        boolean band = true;
        int t = model.getRowCount();

        for (int i = 0; i < t; i++) {
            if (JtDetalle.getValueAt(i, 4).toString().isEmpty()) {
                band = false;
                break;
            }
        }
        return band;
    }

    private boolean verificaint(String cad) {
        boolean resp = false;
        String patt = "[0-9]+";
        Pattern pat = Pattern.compile(patt);
        Matcher match = pat.matcher(cad);
        if (match.matches()) {
            resp = true;
        }
        return resp;
    }

    private boolean verificafloat(String cad) {
        boolean resp = false;
        String patt = "[0-9]+||[0-9]+.[0-9]+";
        Pattern pat = Pattern.compile(patt);
        Matcher match = pat.matcher(cad);
        if (match.matches()) {
            resp = true;
        }
        return resp;
    }

    private boolean verificaflotante(String cad) {
        boolean check = true;
        Character c;
        int control = 0;
        String cadena = cad;
        for (int i = 0; i < cad.length(); i++) {
            c = cadena.charAt(i);
            if (!Character.isDigit(c)) {
                if (c.equals('.') && control == 0) {
                    control++;
                } else if (control == 1) {
                    check = false;
                    break;
                }
                check = false;
                break;
            }
        }
        return check;
    }

    private boolean verificadetalle() {
        boolean resp = true;
        for (int i = 0; i < k.size(); i++) {
            String precio = JtDetalle.getValueAt(i, 3).toString();
            if (!verificafloat(precio)) {
                resp = false;
                break;
            }
        }
        return resp;
    }

    private void respcod() {
//                                pre = Double.parseDouble(JtDetalle.getValueAt(i, 2).toString());
//                        precioantes = Double.parseDouble(formateador.format((pre)));
//                        pares = Integer.parseInt(JtDetalle.getValueAt(i, 3).toString());
//
//                        precio = Double.parseDouble(formateador.format((pre) * pares));
//
//                        //Precio interno para valores enteros y sin desglose de iva
//                        preciointerno = Double.parseDouble(JtDetalle.getValueAt(i, 2).toString()) * pares;
//                        descripcion = JtDetalle.getValueAt(i, 0).toString();
//                        codigosat = JtDetalle.getValueAt(i, 1).toString();
//                        umedida = "PR";
//                        double dato = Double.parseDouble(formateador.format(sumatotal + preciointerno + (precio * 0.16)));
//                        double desc = arrcargoseleccion.get(x).getDescuento();
//                        System.out.println("precio " + preciointerno + ", desc" + desc + ", " + dato + ", sumatotal " + sumatotal);
//                        //Hacer operaciones con los importes y resetear si aplica la suma total
//                        if (dato >= desc) {
//
//                            car.setFoliofiscal(folios);
//                            car.setCuenta(arrcargoseleccion.get(x).getCuenta());
//                            car.setSubcuenta(arrcargoseleccion.get(x).getSubcuenta());
//                            car.setCliente(arrcargoseleccion.get(x).getCliente());
//                            car.setReferencia(arrcargoseleccion.get(x).getReferencia());
//                            car.setFecha(arrcargoseleccion.get(x).getFecha());
//                            car.setDescnota(descripcion);
//                            car.setCantidad(pares);
//                            //Condiciones para saber si la suma de importes son igual o distintos al de la factura
//                            if (dato == desc) {
////                                car.setDescuento(preciointerno + extra);// importe a descontar de cargos
//                                car.setDescuento(dato + extra);
////                                arruuid.add(arrcargoseleccion.get(x).getFoliofiscal());
//                                sumatotal = 0;
//                                x++;
//                            } else {
//                                double flotanteaux = desc - sumatotal;
//
//                                // importe inferior menos sumatotal Ej(500-400) considerando 500 como lo introducido y 400 como la suma
//                                if (flotanteaux < 0) {
//                                    car.setDescuento(flotanteaux * (-1));
//                                } else {
//                                    car.setDescuento(flotanteaux);
//                                }
//                                extra = dato - desc;
////                                if (i + 1 == tamaño || flotanteaux + extra == desc) {
//                                if (i + 1 == tamaño || dato == desc) {
////                                    car.setDescuento(flotanteaux + extra);
//                                    car.setDescuento(dato + extra);
//                                }
////                                arruuid.add(arrcargoseleccion.get(x).getFoliofiscal());
//                                sumatotal += preciointerno + (precio * 0.16);
//                                sumatotal -= desc;
//                                x++;
//                            }
//                            arrayc.add(car);
//                        } else {
//                            //Asignar directo ya que no interfiere con el total de una factura seleccionada
//                            //No aplica en reciclar codigo por el contador interno de la seleccion
////                            arruuid.add(arrcargoseleccion.get(x).getFoliofiscal());
////                            car.setDescuento(preciointerno + extra);// importe a descontar de cargos
//                            car.setDescuento(dato + extra);
//                            car.setFoliofiscal(folios);
//                            car.setCuenta(arrcargoseleccion.get(x).getCuenta());
//                            car.setSubcuenta(arrcargoseleccion.get(x).getSubcuenta());
//                            car.setCliente(arrcargoseleccion.get(x).getCliente());
//                            car.setReferencia(arrcargoseleccion.get(x).getReferencia());
//                            car.setFecha(arrcargoseleccion.get(x).getFecha());
//                            car.setDescnota(descripcion);
//                            car.setCantidad(pares);
////                            sumatotal += preciointerno;
//                            sumatotal += dato;
//                            extra = 0;
//                            arrayc.add(car);
//                        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcCuenta;
    private javax.swing.JComboBox<String> JcForma;
    private javax.swing.JComboBox<String> JcMetodo;
    private javax.swing.JCheckBox JcUsd;
    private javax.swing.JComboBox<String> JcUso;
    private javax.swing.JLabel JlDesc;
    private javax.swing.JLabel JlIva;
    private javax.swing.JLabel JlNombre;
    private javax.swing.JLabel JlTcambio;
    private javax.swing.JLabel JlTotal;
    private javax.swing.JList<String> Jlcargofac;
    private javax.swing.JLabel Jlsub;
    public javax.swing.JTextField JtCliente;
    private javax.swing.JTable JtDetalle;
    private javax.swing.JTextArea JtObs;
    private javax.swing.JComboBox<String> JtRelacion;
    private javax.swing.JTextField JtTCambio;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu pop;
    // End of variables declaration//GEN-END:variables
}
