/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import DAO.daoCorridas;
import DAO.daoalmacenes;
import DAO.daocombinaciones;
import DAO.daoproductos;
import Modelo.Almacen;
import Modelo.Combinacion;
import Modelo.Corridas;
import Modelo.Producto;
import Server.Serverprod;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GATEWAY1-
 */
public class Paresremision extends javax.swing.JDialog {

    Serverprod server68 = new Serverprod();
    public Connection rcpt;
    ArrayList<Almacen> arralma = new ArrayList<>();
    ArrayList<Corridas> arrcorrida = new ArrayList<>();
    ArrayList<Combinacion> arrcomb = new ArrayList<>();
    public Producto prod = new Producto();
    String marca="";

    /**
     * Creates new form Paresremision
     */
    public Paresremision(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/edit-validated_40458.png"));
        setIconImage(icon);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setLocationRelativeTo(null);
        setconexion();
        JlIniciar.setEnabled(false);
        JlIniciar.setVisible(false);
    }

    private void setconexion() {
        try {
//            rcpt = server68.getconexionserver8("RCPT");
            rcpt = server68.getconexionpruebarcpt();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Paresremision.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Paresremision.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Paresremision.class.getName()).log(Level.SEVERE, null, ex);
        }
        daoalmacenes a = new daoalmacenes();
        arralma = a.getalmacenes(rcpt);//lista de almacenes
    }

    public final void generatabla() {// Genera la tabla desde cero con cada actualizacion
        DefaultTableModel model = new DefaultTableModel();
        daoproductos d = new daoproductos();
        //En el titulo genera los puntos
        //Datos iniciales para carga de datos y tabla
        float pi = arrcorrida.get(JlCorrida.getSelectedIndex()).getPi();// punto inicial
        float pf = (float) (arrcorrida.get(JlCorrida.getSelectedIndex()).getPf() + 0.5);// punto final
        int corrida = arrcorrida.get(JlCorrida.getSelectedIndex()).getCorrida();
        int comb = arrcomb.get(JlCombinacion.getSelectedIndex()).getCombinacion();
        int estilo = Integer.parseInt(JtEstilo.getText());
        int almacen = Integer.parseInt(JtAlmacen.getText());
        String bd = (JtTipo.getText().toUpperCase().equals("P")) ? "ExistenciasPedidos" : "ExistenciasStock";//

        prod = d.getProducto(rcpt, estilo, corrida, comb, almacen, bd);
        marca=(prod.getMarca().equals("1")) ? "O" : "T";
        JlMarcas.setText(marca);
        if (prod.getProducto() != 0) {
            model.setNumRows(1);
            JtPares.setRequestFocusEnabled(true);
            int i = 0;
            while (pi <= pf) {
                model.addColumn(pi + "\t\t        : " + prod.getArr().get(i));
                pi += 0.5;
                i++;
            }
            JtPares.setDragEnabled(false);
            JtPares.setModel(model);
            for (int j = 0; j < prod.getArr().size(); j++) {
                JtPares.setValueAt("", 0, j);
            }
        } else {
            JtTipo.requestFocus();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtPares = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JlCombinacion = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        JlCorrida = new javax.swing.JList<>();
        JtCorrida = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        JtCombinacion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        JtEstilo = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JtTipo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        JtAlmacen = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        JlAlmacen = new javax.swing.JLabel();
        JtCantidad = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        JtPrecio = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        JlMarcas = new javax.swing.JLabel();
        JlIniciar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(102, 153, 255));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/Recursos/bordeazul16x16.png")))); // NOI18N
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        JtPares.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        JtPares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JtPares.setRowSelectionAllowed(true);
        JtPares.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, JlIniciar, org.jdesktop.beansbinding.ObjectProperty.create(), JtPares, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(JtPares);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        JlCombinacion.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        JlCombinacion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JlCombinacion.setToolTipText("Selecciona Combinacion");
        JlCombinacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlCombinacionMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(JlCombinacion);

        JlCorrida.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        JlCorrida.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JlCorrida.setToolTipText("Selecciona Corrida");
        JlCorrida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlCorridaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JlCorridaMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(JlCorrida);

        JtCorrida.setEditable(false);
        JtCorrida.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JtCorrida.setForeground(new java.awt.Color(102, 102, 102));
        JtCorrida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtCorrida.setBorder(null);
        JtCorrida.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtCorridaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Corrida");

        jSeparator6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JtCombinacion.setEditable(false);
        JtCombinacion.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JtCombinacion.setForeground(new java.awt.Color(102, 102, 102));
        JtCombinacion.setBorder(null);
        JtCombinacion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtCombinacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtCombinacionActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Combinacion");

        jSeparator7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JtEstilo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JtEstilo.setForeground(new java.awt.Color(102, 102, 102));
        JtEstilo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtEstilo.setBorder(null);
        JtEstilo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtEstilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtEstiloActionPerformed(evt);
            }
        });

        jSeparator5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Estilo");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Tipo");

        JtTipo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JtTipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtTipo.setBorder(null);
        JtTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtTipoActionPerformed(evt);
            }
        });

        jSeparator3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Almacen");

        JtAlmacen.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JtAlmacen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtAlmacen.setBorder(null);
        JtAlmacen.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtAlmacenActionPerformed(evt);
            }
        });

        jSeparator4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JlAlmacen.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        JlAlmacen.setForeground(new java.awt.Color(102, 102, 102));

        JtCantidad.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtCantidad.setBorder(null);
        JtCantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtCantidadActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Cantidad");

        jSeparator8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JtPrecio.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JtPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtPrecio.setBorder(null);
        JtPrecio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtPrecioActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Precio");

        jSeparator9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JlMarcas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JtEstilo)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3)
                            .addComponent(JtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JtAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JlAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JtCorrida)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JtCombinacion)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JtCantidad)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator9)
                            .addComponent(JtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JlMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(JtAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JlAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(JtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(JtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(JtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(JlMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(JtEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(JtCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(JtCombinacion, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        JlIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ic_send_128_28719.png"))); // NOI18N
        JlIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlIniciarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JlIniciarMousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Cancel_icon-icons.com_54824.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Estilo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(556, 556, 556)
                .addComponent(JlIniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JlIniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtTipoActionPerformed
        if (verificap(JtTipo.getText())) {
            JtAlmacen.requestFocus();
        }
    }//GEN-LAST:event_JtTipoActionPerformed

    private void JtAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtAlmacenActionPerformed
        for (int i = 0; i < arralma.size(); i++) {
            if (verificaint(JtAlmacen.getText())) {
                if (arralma.get(i).getAlmacen() == Integer.parseInt(JtAlmacen.getText())) {
                    JlAlmacen.setText(arralma.get(i).getNombre());
                    JtCantidad.requestFocus();
                    break;
                }
            } else {
                JtAlmacen.requestFocus();
                JtAlmacen.setText("");
            }

        }
    }//GEN-LAST:event_JtAlmacenActionPerformed

    private void JtEstiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtEstiloActionPerformed
        if (verificaint(JtEstilo.getText())) {
//            JtCorrida.requestFocus();
            DefaultListModel m = new DefaultListModel();
            daoCorridas d = new daoCorridas();
            arrcorrida = d.getCorridas(rcpt, Integer.parseInt(JtEstilo.getText()));
            for (int i = 0; i < arrcorrida.size(); i++) {
                m.addElement(arrcorrida.get(i).getDescripcion());
            }
            JlCorrida.setModel(m);
        } else {
            JtEstilo.requestFocus();
            JtEstilo.setText("");
        }
    }//GEN-LAST:event_JtEstiloActionPerformed

    private void JtCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtCorridaActionPerformed

    }//GEN-LAST:event_JtCorridaActionPerformed

    private void JtCombinacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtCombinacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtCombinacionActionPerformed

    private void JtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtCantidadActionPerformed
        if (verificaint(JtCantidad.getText())) {
            JtPrecio.requestFocus();
        } else {
            JtCantidad.requestFocus();
            JtCantidad.setText("");
        }
    }//GEN-LAST:event_JtCantidadActionPerformed

    private void JtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtPrecioActionPerformed
        if (verificafloat(JtPrecio.getText())) {
            JtEstilo.requestFocus();
        } else {
            JtPrecio.requestFocus();
            JtPrecio.setText("");
        }
    }//GEN-LAST:event_JtPrecioActionPerformed

    private void JlCorridaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlCorridaMouseClicked

//        JtCombinacion.requestFocus();
    }//GEN-LAST:event_JlCorridaMouseClicked

    private void JlCombinacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlCombinacionMouseClicked
        JtCombinacion.setText(arrcomb.get(JlCombinacion.getSelectedIndex()).getCombinacion() + "");//copia numero de combinacion al campo
        JlIniciar.setEnabled(true);
        JlIniciar.setVisible(true);
        generatabla();
    }//GEN-LAST:event_JlCombinacionMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrarbd();
    }//GEN-LAST:event_formWindowClosing

    private void JlIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlIniciarMouseClicked

    }//GEN-LAST:event_JlIniciarMouseClicked

    private void JlCorridaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlCorridaMousePressed
        int estilo = Integer.parseInt(JtEstilo.getText());
        int corrida = arrcorrida.get(JlCorrida.getSelectedIndex()).getCorrida();
        JtCorrida.setText(corrida + "");
        DefaultListModel m = new DefaultListModel();
        daocombinaciones d = new daocombinaciones();
        arrcomb = d.getCombinaciones(rcpt, estilo, corrida);
        for (int i = 0; i < arrcomb.size(); i++) {
            m.addElement(arrcomb.get(i).getCombinacion() + ", " + arrcomb.get(i).getMaterial() + " - " + arrcomb.get(i).getColor());
        }
        JlCombinacion.setModel(m);
    }//GEN-LAST:event_JlCorridaMousePressed

    private void JlIniciarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlIniciarMousePressed
        EjecutarPremovimiento();
    }//GEN-LAST:event_JlIniciarMousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        prod.setDesccombinacion("");
        cerrarbd();
        this.dispose();
    }//GEN-LAST:event_jLabel2MousePressed
    private void cerrarbd() {
        try {
            rcpt.close();
//            System.out.println("cerrarbd pares");
        } catch (SQLException ex) {
            Logger.getLogger(Paresremision.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void EjecutarPremovimiento() {
        String estilo = JtEstilo.getText();
        String almacen = JtAlmacen.getText();
        String cantidad = JtCantidad.getText();
        String precio = JtPrecio.getText();
        String tipo = JtTipo.getText().toLowerCase();
        if (estilo.equals("") || almacen.equals("") || cantidad.equals("") || precio.equals("") || tipo.equals("") || arrcomb.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Introducir correctamente los datos, intentarlo de nuevo");
            JtTipo.requestFocus();
        } else {
            if (!verificaint(estilo) && !verificaint(almacen) && !verificaint(cantidad) && !verificafloat(precio)
                    && (!tipo.equals("p") || !tipo.equals("s"))) {
                JOptionPane.showMessageDialog(null, "Introducir correctamente los datos, intentarlo de nuevo");
                JtEstilo.requestFocus();
            } else {
                if (verificadatostabla(Integer.parseInt(cantidad))) {
                    //ingresar lo faltante al objeto
                    int rowcomb = JlCombinacion.getSelectedIndex();
                    int rowcor = JlCorrida.getSelectedIndex();
                    String strcombi = arrcomb.get(rowcomb).getMaterial() + " - " + arrcomb.get(rowcomb).getColor();
                    prod.setCantidad(Integer.parseInt(cantidad));
                    prod.setPrecio(Float.parseFloat(precio));
                    prod.setTipo(tipo.toUpperCase());
                    prod.setDesccombinacion(strcombi);
                    prod.setCordesc(arrcorrida.get(rowcor).getDescripcion());
                    prod.setMarca(marca);
                    //añadir al kardex
                    cerrarbd();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Introducir correctamente los datos, intentarlo de nuevo");
                }
            }

        }
    }

    private boolean verificadatostabla(int cantidad) {// validacion de datos de tabla
        String resp = "";
        boolean r = false;
        boolean inicio = true;
        int punto = 1;
        int cant = 0;
        for (int i = 0; i < 12; i++) {// numero maximo de celdas
//            if (JtPares.getValueAt(0, i).equals("") || JtPares.getValueAt(0, i).equals("0")) {// verifica si es cero y saltarse la celda
            if (JtPares.getValueAt(0, i).equals("") || JtPares.getValueAt(0, i).equals("0")) {// verifica si es cero y saltarse la celda    
                setpuntos(punto, 0);
            } else {// distinta a 0 o vacio
                int celda = Integer.parseInt(JtPares.getValueAt(0, i).toString());// valor de la celda
                int p = Integer.parseInt(prod.getArr().get(i));// nvalor de existencia
//                System.out.println(JtPares.getRowCount() + " / " + JtPares.getSelectedRow());
                if (p >= celda && verificaint(String.valueOf(celda))) {//verifica punto x punto que exista y que no sea menos de cero
                    if (inicio) {
                        resp = " punto" + punto + "=punto" + punto + "-" + celda;
                        setpuntos(punto, celda);
                        inicio = false;
                    } else {
                        resp += ", punto" + punto + "=punto" + punto + "-" + celda;
                        setpuntos(punto, celda);
                    }

                    r = true;
                    cant += celda;
                } else {//cantidad de la celda mayor que la existencia
                    for (int j = 0; j < prod.getArr().size(); j++) {
                        JtPares.setValueAt("0", 0, j);
                    }
                    JOptionPane.showMessageDialog(null, "Alguna cantidad de pares esta mal, verificalo de nuevo");
                    resp = "";
                    break;
                }
            }
            punto++;
        }
        if (cantidad != cant) {
            r = false;
        }
//        System.out.println(resp + " - " + cantidad + " -| " + cant);
        return r;
    }

    private void setpuntos(int punto, int cant) {

        switch (punto) {
            case 1:
                prod.setP1(cant);
            case 2:
                prod.setP2(cant);
            case 3:
                prod.setP3(cant);
            case 4:
                prod.setP4(cant);
            case 5:
                prod.setP5(cant);
            case 6:
                prod.setP6(cant);
            case 7:
                prod.setP7(cant);
            case 8:
                prod.setP8(cant);
            case 9:
                prod.setP9(cant);
            case 10:
                prod.setP10(cant);
            case 11:
                prod.setP11(cant);
            case 12:
                prod.setP12(cant);

        }
    }

    private boolean verificafloat(String cad) {
        boolean resp = false;
        String patt = "[0-9]+||[0-9]+.[0-9]+";
        Pattern pat = Pattern.compile(patt);
        Matcher match = pat.matcher(cad);
        if (match.matches()) {
            resp = true;
        }
        return resp;
    }

    private boolean verificaint(String cad) {
        boolean resp = false;
        String patt = "[0-9]+";
        Pattern pat = Pattern.compile(patt);
        Matcher match = pat.matcher(cad);
        if (match.matches()) {
            resp = true;
        }
        return resp;
    }

    private boolean verificastring(String cad) {
        boolean resp = false;
        String patt = "[azAZ ]+";
        Pattern pat = Pattern.compile(patt);
        Matcher match = pat.matcher(cad);
        if (match.matches()) {
            resp = true;
        }
        return resp;
    }

    private boolean verificap(String cad) {
        boolean resp = false;
        String patt = "[p]||[s]";
        Pattern pat = Pattern.compile(patt);
        Matcher match = pat.matcher(cad);
        if (match.matches()) {
            resp = true;
        }
        return resp;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paresremision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paresremision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paresremision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paresremision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Paresremision dialog = new Paresremision(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlAlmacen;
    private javax.swing.JList<String> JlCombinacion;
    private javax.swing.JList<String> JlCorrida;
    private javax.swing.JLabel JlIniciar;
    private javax.swing.JLabel JlMarcas;
    public javax.swing.JTextField JtAlmacen;
    public javax.swing.JTextField JtCantidad;
    public javax.swing.JTextField JtCombinacion;
    public javax.swing.JTextField JtCorrida;
    public javax.swing.JTextField JtEstilo;
    private javax.swing.JTable JtPares;
    public javax.swing.JTextField JtPrecio;
    public javax.swing.JTextField JtTipo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
